version: '3.7'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/multi/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - flask
    networks:
      network:
        aliases:
          - aqra
    ports:
      - 5000:80
    volumes:
      - nginxdata:/var/log/nginx

  flask:
    build:
      context: .
      dockerfile: docker/multi/flask/Dockerfile
    container_name: flask
    depends_on:
      - mongodb
    environment:
      APP_ENV: ${APP_ENV}
      APP_NAME: ${APP_NAME}
      PYTHONPATH: ${PYTHONPATH}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_HOSTNAME: ${MONGODB_HOSTNAME}
      DARK_SKY_CREDENTIALS: ${DARK_SKY_CREDENTIALS}
      PULSE_ECO_CREDENTIALS: ${PULSE_ECO_CREDENTIALS}
    expose:
      - 5000
    networks:
      network:
        aliases:
          - aqra
    volumes:
      - flaskdata:/var/api

  mongodb:
    build:
      context: .
      dockerfile: docker/mongo/Dockerfile
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGODB_DATA_DIR: ${MONGODB_DATA_DIR}
      MONDODB_LOG_DIR: ${MONDODB_LOG_DIR}
    expose:
      - 27017
    networks:
      - network
    volumes:
      - mongodbdata:/data/db
networks:
  network:
    driver: bridge
volumes:
  nginxdata:
    driver: local
  flaskdata:
    driver: local
  mongodbdata:
    driver: local