version: '3.7'
services:
  flask:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: flask
    depends_on:
      - mongodb
    environment:
      APP_ENV: prod
      APP_NAME: air-quality-rest-api
      MONGODB_DATABASE: air-quality
      MONGODB_USERNAME: flaskuser
      MONGODB_PASSWORD: your_mongodb_password
      MONGODB_HOSTNAME: mongodb
      DARK_SKY_CREDENTIALS: /env/DarkSkyAPI.json
      PULSE_ECO_CREDENTIALS: /env/PulseEcoAPI.json
    networks:
      network:
        aliases:
          - aqra
    ports:
      - 5000:80
    volumes:
      - flaskdata:/var/api

  mongodb:
    image: mongo:latest
    container_name: mongodb
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: your_mongodb_root_password
      MONGO_INITDB_DATABASE: air-quality
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    expose:
      - 27017
    volumes:
      - mongodbdata:/data/db
    networks:
      - network
networks:
  network:
    driver: bridge
volumes:
  flaskdata:
    driver: local
  mongodbdata:
    driver: local