version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/multi/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - flask
    networks:
      network:
        aliases:
          - aqra
    ports:
      - 5000:80
    volumes:
      - nginxdata:/var/log/nginx

  flask:
    build:
      context: .
      dockerfile: docker/multi/flask/Dockerfile
    container_name: flask
    depends_on:
      - mongodb
    environment:
      APP_ENV: prod
      APP_NAME: air-quality-rest-api
      PYTHONPATH: /src
      MONGODB_DATABASE: air-quality
      MONGODB_USERNAME: flaskuser
      MONGODB_PASSWORD: your_mongodb_password
      MONGODB_HOSTNAME: mongodb
      DARK_SKY_CREDENTIALS: /env/DarkSkyAPI.json
      PULSE_ECO_CREDENTIALS: /env/PulseEcoAPI.json
    expose:
      - 5000
    networks:
      network:
        aliases:
          - aqra
    volumes:
      - flaskdata:/var/api

  mongodb:
    build:
      context: .
      dockerfile: docker/mongo/Dockerfile
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: your_mongodb_root_password
      MONGO_INITDB_DATABASE: air-quality
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    expose:
      - 27017
    networks:
      - network
    volumes:
      - mongodbdata:/data/db
networks:
  network:
    driver: bridge
volumes:
  nginxdata:
    driver: local
  flaskdata:
    driver: local
  mongodbdata:
    driver: local