version: '3.7'
services:
  nginx:
    build:
      context: .
      dockerfile: 'docker/nginx/Dockerfile'
    container_name: 'nginx'
    depends_on:
      - 'flask'
    networks:
      network:
        aliases:
          - aqra
    ports:
      - '5000:80'

  flask:
    build:
      context: .
      dockerfile: 'docker/flask/Dockerfile'
    container_name: 'flask'
    environment:
      - APP_NAME=air-quality-rest-api
    expose:
      - '5000'
    networks:
      network:
        aliases:
          - aqra
networks:
  network:
    driver: 'bridge'