apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  name: flask-ingress
  namespace: kube-system
spec:
  tls:
    - hosts:
        - aqra.com
      secretName: flask-tls
  rules:
    - host: aqra.com
      http:
        paths:
          - backend:
              service:
                name: flask
                port:
                  number: 80
            path: /
            pathType: Prefix