apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker/single/docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: flask
  name: flask
  namespace: kube-system
spec:
  ports:
    - name: '80'
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: flask
  type: ClusterIP