apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: flask
  name: flask
  namespace: aqra
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flask
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/aqra-network: "true"
        io.kompose.service: flask
    spec:
      automountServiceAccountToken: false
      containers:
        - envFrom:
            - secretRef:
                name: flask-secret
          image: aqra-flask
          imagePullPolicy: Never
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /api/v1/healthz/live
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 300
            timeoutSeconds: 60
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /api/v1/healthz/ready
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 300
            timeoutSeconds: 60
          name: flask
          ports:
            - containerPort: 80
          resources: { }
          volumeMounts:
            - mountPath: /var/api
              name: flask-data
      volumes:
        - name: flask-data
          persistentVolumeClaim:
            claimName: flask-data-pvc