apiVersion: v1
kind: ServiceAccount
metadata:
  name: certificate-renewal-sa
  namespace: aqra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: certificate-renewal
  namespace: aqra
rules:
  - apiGroups: [ "", "cert-manager.io" ]
    resources: [ "certificates", "secrets" ]
    verbs: [ "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: certificate-renewal-rolebinding
  namespace: aqra
subjects:
  - kind: ServiceAccount
    name: certificate-renewal-sa
    namespace: aqra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: certificate-renewal
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: certificate-renewal
  namespace: aqra
spec:
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - |
                  set -e
                  kubectl get certificate aqra-tls -n aqra || exit 0
                  kubectl get secret aqra-tls -n aqra || exit 0
                  kubectl delete certificate aqra-tls -n aqra
                  kubectl delete secret aqra-tls -n aqra
              image: bitnami/kubectl:latest
              name: cronjob
          restartPolicy: OnFailure
          serviceAccountName: certificate-renewal-sa
  schedule: 0 0 1 * *
  successfulJobsHistoryLimit: 1