apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-restart-sa
  namespace: aqra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flask-restart-role
  namespace: aqra
rules:
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "patch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flask-restart-rolebinding
  namespace: aqra
subjects:
  - kind: ServiceAccount
    name: flask-restart-sa
    namespace: aqra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flask-restart-role
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: flask-restart
  namespace: aqra
spec:
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - set -e; kubectl rollout restart deployment flask -n aqra
              name: kubectl
              image: bitnami/kubectl:latest
          restartPolicy: OnFailure
          serviceAccountName: flask-restart-sa
  schedule: 0 0 * * *
  successfulJobsHistoryLimit: 1