apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cronjob.yml
  - flask-deployment.yml
  - flask-service.yml
  - nginx-deployment.yml
  - nginx-ingress.yml
  - nginx-service.yml