apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker/multi/docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: nginx
  name: nginx
  namespace: aqra
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker/multi/docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      labels:
        io.kompose.network/network: "true"
        io.kompose.service: nginx
    spec:
      containers:
        - image: aqra_nginx
          imagePullPolicy: Never
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /healthz/live
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 900
            timeoutSeconds: 60
          name: nginx
          ports:
            - containerPort: 80
          resources: { }
          volumeMounts:
            - mountPath: /var/log/nginx
              name: nginxdata
      serviceAccountName: ""
      volumes:
        - name: nginxdata
          persistentVolumeClaim:
            claimName: nginxdata-pvc