version: "3.8"
services:
  nginx:
    build:
      args:
        BUILDKIT_PROGRESS: plain
      context: ../..
      dockerfile: docker/multi/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - flask
    deploy:
      replicas: 1
    image: aqra-nginx:latest
    networks:
      network:
        aliases:
          - aqra
    ports:
      - "80:80"
    volumes:
      - nginxdata:/var/log/nginx

  flask:
    build:
      args:
        BUILDKIT_PROGRESS: plain
      context: ../..
      dockerfile: docker/multi/flask/Dockerfile
    container_name: flask
    depends_on:
      - mongo
    deploy:
      replicas: 1
    env_file:
      - .env
    environment:
      APP_ENV: ${APP_ENV}
      DARK_SKY_TOKEN: ${DARK_SKY_TOKEN}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGODB_CONNECTION: ${MONGODB_CONNECTION}
      MONGODB_HOSTNAME: ${MONGODB_HOSTNAME}
      OPEN_WEATHER_TOKEN: ${OPEN_WEATHER_TOKEN}
      PYTHONPATH: ${PYTHONPATH}
      REPO_NAME: ${REPO_NAME}
      TZ: ${TZ}
      VOLUME_PATH: ${VOLUME_PATH}
    expose:
      - 5000
    image: aqra-flask:latest
    networks:
      network:
        aliases:
          - aqra
    volumes:
      - flaskdata:/var/api

  mongo:
    build:
      args:
        BUILDKIT_PROGRESS: plain
      context: ../..
      dockerfile: docker/mongo/Dockerfile
    container_name: mongo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - .env
    environment:
      MONDODB_LOG_DIR: ${MONDODB_LOG_DIR}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGODB_DATA_DIR: ${MONGODB_DATA_DIR}
    expose:
      - 27017
    image: aqra-mongo:latest
    networks:
      - network
    volumes:
      - mongodata:/data/db

networks:
  network:
    attachable: true
    driver: overlay

volumes:
  nginxdata:
    driver: local
  flaskdata:
    driver: local
  mongodata:
    driver: local