version: '3.8'
services:
  nginx:
    build:
      context: ../..
      dockerfile: docker/multi/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - flask
    deploy:
      placement:
        constraints: [ node.role == worker ]
      replicas: 1
      restart_policy:
        condition: on-failure
    image: air_quality_nginx:latest
    networks:
      network:
        aliases:
          - aqra
    ports:
      - 5000:80
    volumes:
      - nginxdata:/var/log/nginx

  flask:
    build:
      context: ../..
      dockerfile: docker/multi/flask/Dockerfile
    container_name: flask
    depends_on:
      - mongodb
    deploy:
      placement:
        constraints: [ node.role == worker ]
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      APP_ENV: ${APP_ENV}
      APP_NAME: ${APP_NAME}
      PYTHONPATH: ${PYTHONPATH}
      DARK_SKY_TOKEN: ${DARK_SKY_TOKEN}
      PULSE_ECO_USER_NAME_CREDENTIALS: ${PULSE_ECO_USER_NAME_CREDENTIALS}
      PULSE_ECO_USER_PASS_CREDENTIALS: ${PULSE_ECO_USER_PASS_CREDENTIALS}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_HOSTNAME: ${MONGODB_HOSTNAME}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
    env_file:
      - ../../.env
    expose:
      - 5000
    image: air_quality_flask:latest
    networks:
      network:
        aliases:
          - aqra
    volumes:
      - flaskdata:/var/api

  mongodb:
    build:
      context: ../..
      dockerfile: docker/mongo/Dockerfile
    container_name: mongodb
    deploy:
      placement:
        constraints: [ node.role == manager ]
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
      MONGODB_INITDB_DATABASE: ${MONGODB_INITDB_DATABASE}
      MONGODB_DATA_DIR: ${MONGODB_DATA_DIR}
      MONDODB_LOG_DIR: ${MONDODB_LOG_DIR}
    expose:
      - 27017
    env_file:
      - ../../.env
    image: air_quality_mongodb:latest
    networks:
      - network
    volumes:
      - mongodbdata:/data/db

networks:
  network:
    driver: bridge

volumes:
  nginxdata:
    driver: local
  flaskdata:
    driver: local
  mongodbdata:
    driver: local