apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-data-pvc
  namespace: aqra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: manual