apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-issuers/prod-issuer.yml
  - cluster-issuers/staging-issuer.yml
  - mongo-deployment.yml
  - mongo-service.yml
  - namespace.yml
  - network-networkpolicy.yml
  - persistent-volume-claims/flaskdata-persistentvolumeclaim.yml
  - persistent-volume-claims/mongodata-persistentvolumeclaim.yml
  - persistent-volumes/flaskdata-persistentvolume.yml
  - persistent-volumes/mongodata-persistentvolume.yml
  - sealed-secrets/flask-sealed-secret.yml
  - sealed-secrets/mongo-sealed-secret.yml