apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flask-sealed-secret.yml
  - flaskdata-persistentvolume.yml
  - flaskdata-persistentvolumeclaim.yml
  - mongo-deployment.yml
  - mongo-sealed-secret.yml
  - mongo-service.yml
  - mongodata-persistentvolume.yml
  - mongodata-persistentvolumeclaim.yml
  - namespace.yml
  - network-networkpolicy.yml