apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cronjob/certificate-cronjob.yml
  - cronjob/flask-cronjob.yml
  - ingress/flask-ingress.yml
  - issuer/prod-issuer.yml
  - issuer/staging-issuer.yml
  - namespace.yml
  - network-policy/network-policy.yml
  - persistent-volume/flask-data-pv.yml
  - persistent-volume/flask-data-pvc.yml
  - persistent-volume/mongo-data-pv.yml
  - persistent-volume/mongo-data-pvc.yml
  - sealed-secret/flask-sealed-secret.yml
  - sealed-secret/mongo-sealed-secret.yml
  - service/flask-service.yml
  - service/mongo-service.yml