apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
  namespace: aqra
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/network: 'true'
        io.kompose.service: mongo
    spec:
      containers:
        - name: mongo
          image: aqra_mongo
          imagePullPolicy: Never
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: mongo-secret
          resources: { }
          volumeMounts:
            - mountPath: /data/db
              name: mongodata
      serviceAccountName: ''
      volumes:
        - name: mongodata
          persistentVolumeClaim:
            claimName: mongodata-pvc
status: { }