apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mongo
  name: mongo
  namespace: aqra
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/network: 'true'
        io.kompose.service: mongo
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: mongo-secret
          image: aqra_mongo
          imagePullPolicy: Never
          livenessProbe:
            failureThreshold: 1
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - db.adminCommand('ping')
            initialDelaySeconds: 60
            periodSeconds: 300
            timeoutSeconds: 60
          name: mongo
          ports:
            - containerPort: 27017
          resources: { }
          volumeMounts:
            - mountPath: /data/db
              name: mongodata
      serviceAccountName: ''
      volumes:
        - name: mongodata
          persistentVolumeClaim:
            claimName: mongodata-pvc