apiVersion: v1
kind: Namespace
metadata:
  name: aqra
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mongo
  name: mongo
  namespace: aqra
spec:
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: flaskdata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: mongodata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: flaskdata-pvc
  name: flaskdata-pvc
  namespace: aqra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mongodata-pvc
  name: mongodata-pvc
  namespace: aqra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mongo
  name: mongo
  namespace: aqra
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/network: 'true'
        io.kompose.service: mongo
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: mongo-secret
          image: aqra_mongo
          imagePullPolicy: Never
          name: mongo
          ports:
            - containerPort: 27017
          resources: { }
          volumeMounts:
            - mountPath: /data/db
              name: mongodata
      serviceAccountName: ''
      volumes:
        - name: mongodata
          persistentVolumeClaim:
            claimName: mongodata-pvc
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: flask-secret
  namespace: aqra
spec:
  encryptedData:
    APP_ENV: AgCSObyp1LfiBKfk4AmaoV1Hn5vuyGGq4G6ULvRAmJFsbaIhOnmgU+9frG0bg+and2Mzg3haNsYZ9bU368se9U7npAGTlvu04BWFKwUSIiz283LuNA9HD9x8H63ePlc59HSD5uRbT6MZ7dlEJj2jYtJC0DynipFwD0Ap2RNjTiA7FtLhTI5qXrcfv2Hx4QovGWHwKLpipXsYyFkhyXRF1jszMQpIhTkJQJ+/CYvjw2feheN6O+G4f/h7E5vfpZ+A5FcKS6s/BR+h8Mpi3rb88OWi38aJImc+ngCz1/1B1tEgXv59NYOwRPwxWSo1lUruvZ3gZtq3NMAkM3p9THKzBi0zKmGRn/7+rBNVQrJ0zuVcS9/pNJmdAreu0QG4joKNcHG9spEarOPFQFxjH29JrHl1Hc6I4l5MHwMtYX07GSibbFqKa7d15d+PsVabkuLWicgbOt3h40A7ZvEPhcubYcl7MKZ7sa0VMN46yzLgCY8BwQELpGsxH6H2Sr6squFlDKn9zch6loX6bF4odoNV7y7y/J6py8goACZ1r9WMuEpnr4VmmXWSi1pldhpB6WNadb6SLy+7Vvu3zaLdeYfg726/xmaFTNSq2rXVRiOiLlk9KPjV03ABsjqquTvRwkfwVB2qOC1DaJFTzVIZqo4Sbfjwk4T7VAwe6/AqmXPhmW3SCSHNy1cs4csEy6DF/4kneZO/zkvqtJXF4Kfx
    GITHUB_TOKEN: AgAyFIHTgD2qAEQueeLLPYn5ybrF9Ti+vHOnnHz/lc7APZDRz6IFnYIlvUlxKpS2zTkhdjDevbYXVnMHOaWBCi91DtvMR/mlRS2eUjzQ+aqF2DpgLF49Kj332F0HEP+DI1ZhPGQoUV3DuuEjJO6R18+uDrWgjY33QFxEwITc1W+M794O6dMfZtNGMNp3KunPd/2uNcYRsmWUEhO3o9nekxjqPFmitarxWBjnL7KUuAkEsJAXoE6yJMcGl+ewK+JdTcjoD8dziSQCEikRNlvDmXjSliQJKIegOlF1LpD9XG+/AUyvIMPMesM99SOoa65ktUAJ7JeNRoC/auv5K6F9iR3UQ2qfkhv+lpm3uDYWb/hGP/UzDpqRRaX1RyuCz7IRYz75P10CGhcik9U4MBRXm2TPVtJ4A9m+OymDNXovp8o34KCaI+EsVSpFNxSE7XCqidI2WlB0k28rsJtmhxFPQQE0DXF0ZzMhpVo8fVkyNOPeteH9n00VQyS9TEmDFIjna5RNBD0AzB6Tds8iT3r3NEIyxlmoKCzGHM3gXsAtmQke+xTKcMH5beXDJYa9qYCrvhl7tDkcLq8vkxwW8KeUwTVYHLCwvzcKOGLDn8UfWRHW5M9WvryYoG8Zj+EXxLaWhbD7aEuZpMQ+e4yKi9uUaiL+8J0kPy7odpAMkY+eEmTVQ6uh3QVwZzQR2gBolUeGR4N0VLNT9oFvO+E0dNIO+ZiI0xs5i8LaZQcjtXlDdMZ5oTAE7jumnOU0
    MONGO_DATABASE: AgAa2VT8Bf0CwkNnBQ4Of8q7gzw7c9CKVuZX0zm1iG7X/XWyEoNhVE6DAg43twBeVodibrSTh7sdcMoBQxxajDAIVdGv7H9cZyZJLo0hm/pip2nhD+wJkCHAxPuP9N+P4Ua2vFNjH4DJD0DonzjvjSxUO7od+CckD3yEB3PljXTI3I0TqhAUi6ft5QJmGYZqcE92mmr7LF6JrJ6GAsuIbqRH6HYSbygmgxhmS204CFhKKCLeqXJ4FlIbv5cRrFkXV7UhJUpogKiTtn0NQhVlECzmf4dHQx+CG95vwUc2csIc8IdUosKWmRx956/2oq+76mSPK8GHUBjhowkhAqMvrcznVZxGLQkt6C2Yvp8q5o6/fV2VYPo1E8R8w5ePCTrtuON+Lfyd24iQWvmZtYE+e3+HNnaTLP+wUh7D879LmGNn0+nVaCR2nNhPsKsUbMIAIiDsdxTzwXyhc+JKcPZSBw/k5zoT4sb1wxhmVCiHB2R95p6vzEVbI+dxnJFEZL3XMIYqWtoKVkddyoUkdsdAmr1/UBc4zWg7QLGN2ZxHr6nGaKRYei/1rydeIvq8PZcg1jbPgCu7XzFtc9hLMl36PAciiqNUkGCuA20QCtc8eLoVABhNKNm5l2C8x0Zv4325r3sg3EZYuw6ONOuyPkCH/sVK9YjlJK5h/Chd9eTgjDqXgB+WCzsGqU4MjkHCf57quTM0MHM80do4/w/zZQ==
    MONGO_PASSWORD: AgB56hCGajvlucAs7UZhDngPzqdeyJur52h87NHVjENJA2foNCG4rTpXmVhB9MYfUjjBrAtBcP944PVJ4GdGtJDykyxjQRk3VVEOZiftJpcBq3SDuktHmXf6ccK6W60aCq0/4I8w6ye/SYvWb9Maq5ADYhBrGBpTHJlCwWWO8BLRlddpE9RsdVU9Uc8Ku6jKKL3nfFZFFfRbki4B+1/pHG74mDrLpYjdQQZ/ihz79rniNIKL21wZswS9UjEYhc022O0ljz+uEetlvF+5qnCKRoqSt5MMV6HwIXIyazy/Hgj2wUYjAZvDhRT71x1ot4Ju8GGmq07YeJSK6yifq56fCASUmfHaJBBDCgd5gEAZ2hHWQJoVyT0UqZFAauDKQB1XW8y5zdWwbm4o/0D8zyC5rXzx+Lw0QMM5R5jaVp2LdAOsJbml6fbe7C+ErR0xL4EiHLIvpubK28HB/+4P0KSudQ4VP8iJk1ISxDlK4zP8jceQZqaIo4D6joidmWrHSQKSN1ExtQVGxtlcx9JSk4IZPXjNb3E7A8lC5PAjsRJ9jt3l3rzbxy3vQcQ2XT1uSUJKQLkTp9nYA+NsvvEPfvDfjdxUX4ON9h2wpJS9r5kntEuDJLIWetheCpN8ihphfsyrurxI3gfq36mIOtszHhjLs7Eun6xUHnlG1jdTGDpBYEFeaueiNoVAI8sWlhUVm3zzufP6qPI/qpCdv6MuFjQ96j+XjGjwVsm8Fv6smA==
    MONGO_USERNAME: AgCs291T74aXiK3JCoSLpqssL2Pafxd9lUa1WTFmybXl3oN9S1wibal9eCQtZY70k59BUxMLJGv05AfS8SEjdl2is+mKyOt7jREG5UYKJJFwYFcbU9Y3W03quj/8As2aPTuSHpjejcpyKs5Ubqwz1CZfvW7YcCIFYZGq+HRX4UBPZkdVaFYVV+qxkvjtJpP+QZif4EuGsh/0EhGKynYDCERyzLyjMT5x3s4Vxa+LU3/jSMK+k0ipcTqou0G3wJgrIKYKdSJstBKpGhPiccJDrM+SFLr2XuM7i7CHXucucyb8Tc7yqEhcdQ6XVbmPNtjf0fCa9kJ3h0p3lE7/g3E5rD6vydV3O7bdhkW8vTUv2S9OI/ElgmofXnWZ2QFpyELTS9astEvAduNCDLsDbISt9OXJOXwPtTQT2BMn53xZ9HXgPTiw+a63cugffgT3EjFPlsDzCSebJRktlbxODBb5cM+02TBPka5XcKEE3rC0MkE22bU3KavxeSzm4JLQhTJA7P2ONGYW71hwJxKCMlthMb4Kkm0wvM4nqtVKFLd/+pCrDGarfs2p9gaVr6SDkRAa/yxoqXlmLkOlitOiZsKzY+38QcgF6BEsxAsrG3a57am7cpcmlTnXu4Y0AQt1ENL4uk2LvcJpOSqGNMLTN4faGn7Y+0z5HVT1+9pR8X/f2FPYBdcF/VTAyupbP9nKn7TyXB47ePjGJeDDEvZ1nw==
    MONGODB_CONNECTION: AgBsE/o0/JC2xiWRPaFLHJsSZaPvIAmrANkC8iz3xHW9yDdUHOCSk2vM6ouclZF4MnJMNZOc9A5nmtwaNUgVk6lbaH5Vo4YGWFb1zE7Bk5lLsidFKEY5to1XYKfqLYYadTqWBl6y8C5lt4V/GfQ/iw+RPpulsqcdo+cBr/Na1lsMT5NV76ZcerhcCNTGo9g5rHTsWo2tn5QNuclqRvCOl0tAOmW/0lATJd68ER5Z8tY6QwbyGkVv4BK71VeiA95j894mpX3IopNKhWVWHgU6x1UH3Tkd/xSYnfs8/fXKRh4E6iPJLHTcO5xxcrX7+YYhoaIUA712Y1tnRa/h7HYt1pCJtB76j7XzgLbRvZ1MmSw+SMMn9zqYZXT1uFYy8QNrlMLvZTaQkOhamILSut2PRRyqliKfDTwaTzgjvebnqed7aHuUALc72EJPQutm0UZAVCe9n5FBlV+UH/X2amK7do9OEDpYehXHMmsydXvGNwZ40B26mXV2wc1FZ2W7x5k1dpxbrdGAztfeVrNgPx+z9KBTCgeKsc7OW/thyW5ZbMxlFlKARgFtbttrWlI2AyA0Ht4IhaIcULj4xcJTEcvXhFGYP8zByhEpqGtIh2+LdwPFe/yRZFd1BG3c2oYq4tgFFmKspuYZXfOW1NEdttKU1GaxCdLO8709Kc+dn6r/8m4R6ZE5+sJO46cjedBK7sIC4Acy15ym4Xow
    MONGODB_HOSTNAME: AgCsfTWxs82PsYhmbfBEqjxBQuQJ9bZfzmrklGtp2vO4/Wz4WoakYdjxK9sr67IJhIZTOu8LUCL2o5dL+hHwU0GZ2D4hTYcNMKu/iv3SgAexWO2pclufFKNWatqv1Z2kmbHIqXEmTt+8C8vrKr6JInayz2FsDn8iydUqUavSet0VfcsHIk6LD/70tpIBPJnIp4KBhz0gahToniee9Ld82krqYkq4uiabVC/1Qq7eOcV64KywplZxcnvx48cKuyAIznvDgaBK9EjCvquD4stoSufHmxjmLAaHVlpYsqLD1uAEprmf7dFRdIC85reUbHPBJS2B80smZGMc5ENsmA23BCkrnvFgFjlbfzdlV832KCCmQ4G6hjzhvJ9cQUOQLwZv3VQqZhhrQnhdRuFIoJIpQEuisWUr+/t2vPUu97SVRZ3jhOCMm64MnjKlfI8FcHm0Zpv++2c45ITE7c2bsT/U+Ho8VctefzkwYJywEbw/SvZQ5yQV5Zf31lgrgL2K+92UTxaUqsOP3Y//WLNoCl2wNJG30mHt95ZsMrWKc67AClnKroxjpoy1yMuB8xKBn6xQ/bXFWPyGN+GEfONpuIDPvlMwhTjuCTGDOHFpd98kT8PPPQTCdKqLYXsnHCseZdKW9yNT80jOukBDvF+w7cWSF3Sv+fXniq19+ztsFL7BPAEQcCt26XPdF6tdSTq62NEsUp7q3MSSR07ZgAYnjA==
    OPEN_WEATHER_TOKEN: AgByTbvyJKAdQFojqH6u1liopbjxOpNnoKeXDZbxOQ60Z7ghA8DCvvT4ih0JPJ1vTuTvQCgP4jsW1kUJ7N7mhaMKlyj6OD4BB0ZryF/BT+shSn442DKfaezOCJhTpzOSZ9alKPQxCSLwYI0JTYMzVN1vmS9VSMxPmdSBPTKfByPmarb6917nes7st5oUe6m7/kSsAT5nlQN5U1C0hlzinwjoq3k7XQZYex1QrB+uq1dDpCZhy1cmVrIguQ25uKsihDDGR1WMz4HlqSAnt9jgS550lY3pDd6KnmIdPirHxzHC5uilyM+XMt83F1VWeVN4MA3QSYbLNpBWf0WT4ScX/GvX4v5ydVLyCwaHGdcGLXDxs+XjjKM6nCWQnkwevZHcuHRLoccsShmOcujB11VYkR54mAACzGXmUOLJwU89AAq5SR6QFwaoOkBN/dP/kpk2fqzh57R4nfLkb8aZ6F8hO0fVWFi6sm9n3h9cx4g4faHeEbgGmL4sB5egdHSk1Be6tbm03SbybPMPTB9vAlAuwmmBL6liNra9yEps5VWf1FQNEa3HXYZ+996bxRcsIhS8iusXju2ykOcGCNobIfiimuzN/o4+a6+97C3SsC5K87nvSeMCIDB+jTSQ3aWci95rXqvijLRau3ntVu1wn54QsnvRQOnysckjJw8y3r94SgQpFKR1tIDcvTdpflfKxmZ4gwh/mNl5Z5wbudLr7fClzWSzyfQBEY3Gwf9dtk1ElPNHog==
    PYTHONPATH: AgA2Fe7d40sM5hnM2orwA1Pvh6v4m0xMZa9nQN1Kt/wqx7Druqnb+vu2N+VWVEN86y+HOHskkidl8Ezu7+LVTWf9YrdyVO/Mj9Ugmyc9lDcxvXN9jHJHQ3OCt8SvdE/mEd5eNiaWFsfcbJBb1Hn4vXGB1klfM9mckwV595/XolXTvxfqiTYJ/Veigz3ozZeW+9SyQ5R3HsMWiq68SFXhH33qNCnujYuyPbB6WdVFXrq9pKxP9/IoJ5udI3MYD+uwXp5+A9/qHRK2bG0fnGwUtxuVSZacgx+8cHWM+5Z/9fG9B5IkWBg98cjDDcwfQ/ZBEh8Yf6/IQYTBsL3wm3vFYNLGr3TGVpjgV/A2jGoZ6pTrcEPzDEF39GKcxvHLpPmfw/Kx6Bf+B6a4Qp2aFQMZyOXbmWpCeLlyOHeuyyDJBZIVzik9G2EPN2QjIxsySTLz7zQA1D+Uh7GcyzEgi0Lc6/k7HHFDNv+dQNnL1op9T3zS23nOZfepHT/PYHG5Y313Q4lu69CbhlAOGemcvt3Aq5uUcWOEqQS4qKfO5CUVgTyRIke+iYxRVKj4PKwAYIc552jxJ7U1Qv+naJRVkWcCeOgEzAatcShKyUnLFoUsGx7GxldMQbFIr5s/D1nm0nmV3Aduqz+oYZS1o7VrgRBeahWpYvPl3oCrFrNOOPm5ggptXrEHhtRa2XvxHWhpO6DUP1Ytg1Wf
    REPO_NAME: AgAZ0TdUEp0ZUfajRC5YZVgckFSqA+hKvevsXbQnUD7UZonwfRKt5i0PVh74+wSpVmpZgVoJOOpSEt9SIFN4l5cg99PXvBPoLl+KjX1XeSAtEs7N/av2DEAlqM3W1EiD+M0hGTD1JGYB6XOTHCrb0BhpIFJ4FQwzWgX4EnrJAnMgjWk3Ifnlq8koz/ub/yQg/tTqpuOseFF8uz00HUIWLESW0qshlYt+naAdk4EmzPuxcEQg9Bs7/9TMZU7X6jdUB86WfKDSNGhdSHxvTLMwQYqHL6gscBtv+TGu0gllERYpnAadYAHl4l1SbHGCMZb/NtWFIeg22Lu31T7jjKZKrwuZY7iGDs5L3/f35yB/BXCZXNWE0Jmumz5TylOAowtpXqxO7XM/PnT0ImFBDHnDLdmsGnSXqaOsn7rNzz4dc3UC7p1GeC0NXcRcIuZIEMwryAT5NQdc6peodz1rabYzfLKrdQC6EPIn0domYaXCCjGUu71HRoHzrnbpm2IMqnN5TDrvakXJrecsIPQIKsX8rIz9EW8wZpcF7l5uYNNPu/PSTwJHyKAbMM0vPonhsMxTQlTkzHd4bfpfWeRUsq8aNhvZLnLSOhW9E94YGOtTUfFNIn3DMJIUoQ7FLvJXHRPrp19J+2ZMjecLcJ0cghZgRFs+RT5n4818atbDn81rQlztXQJaJkrsi9ZmQKta1dVgtsWqFu3LbJWy2ld0FaeeveDDJV5ZN4o=
    VOLUME_PATH: AgAq7K1Ne6R5Tso4cfCHbPbUa2gvck0QAhqpoWnQItPRnqlOwKm8JkWABBr2rqRZ1IzY3F3OU/hnBO3jZRtnjRx8/RWa7NsyEIEm+fJb07OcWfpwf8C0NhoTQ2GEF5zAC4f23CjkwCB+DwjZtWKZqPBy4WMKh1KeKgQOTuAZa3bok4NquzgHx1mflbfMqBL+aKETSMQxcbGiKQrgsu4FZx82RaU3ED8kgtV/Il0Vy12/aPXaVVBjuc14/hlTfNQNO8iuqNWlL+2s29MYn9uVGaMiXD/YV46rqvzI/GuhPSOdPgQVaNKNSMN852xmQz34fkosiASgCSby5E2fPEefiv76mq37+jwofZj3n2BbF072lUeCMJZeTqBAz9n6hZh9sZovNn9Rf10lemnmkO6Js0hqwYPix660moSz6TKV5LnwFwaqgwT2UKbMOdDoFtwG5rHg688hqDNIMwmYdx9qns3EUpSoSvxCNQMtaDFXDPRyOjIk9NiJ0b7oUZYRTQNpmf3NPL9GxyT5jyei5odKTOMicxRkMT51+ngZMaJwvoir5Bni1xxQLYND9A/5nbXhvjI3zlSB5aMqLtNbj751+4OIu9LLeNsiYKKyeHFBJZ2B8OvrUPelblcKOMb5iZn8ZQAJJw7ESekNZVuDxEVwKz28p7zUU8JjNb7z8neS1qHBROeJa+1SX11p0Rcr0XcYHETtaZz9GFHu0g==
  template:
    metadata:
      creationTimestamp: null
      name: flask-secret
      namespace: aqra
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secret
  namespace: aqra
spec:
  encryptedData:
    MONDODB_LOG_DIR: AgBdonU9vCOdmBjypfIMBj849IXzab+xQYZoSdHMOVqEyH5bvDGnpO16a4JHIommSVoLf5snP6NCO2Fg4+LrqkAokiAhLMlGHCtardaDF1FLUItfWAJS8Wvyn0d+kV1n8lzta/9+e05A62y8PgLfxySFjwxkN1RKBoWYpo4y0q6FY4RMQ2o4v3RSUYtcxK6bDHrGSEUy+yOwNNR9kNnFoS70+La4lCUTbH0Hjps9qRxe/f9qtNNWaGOV+U86GnZmkKNS4fRUsXo+xyL3PsGTjci4dTTEc/jsUtd7uUzbPP5aIijEWBsPt/HiFPEZkntIBb5TzqClkhLpwkg6y5VGY3aWSCm7eGhCE3bpPU68e32vQmP5IYRVic2w5EAxWNyrMWC5rtF/vKLpxt4KPHolDJwSAeKi+x/kIilfFgHqNSvxGJ46pxQ9GEf1FY/Btidx/721wGwyH/L4T7Xu7PLfAEGFWAl3+qcoG093/c4ZKgSwYvG2VCU1w4qtlfF06aEmd7GC8bmskIjmILA36KB1VRMc4AnJ82KHW7EqxNVsw4cA53NcjfHMNph1UkmYKySA0x9Q4csWBGgjP75dGwPV9puuR48ODT9SdTy7CWxQEH8Njp1/pfp+jtDWqECKteqhhbG2RWA6EPGis2IXt8DuLMrJEJgRGU4WXbEBhbS3X/DhS4QSjHe6LSktmuxb5gEB/Un7H90yIRIFhgE=
    MONGO_INITDB_DATABASE: AgA+eSlzsDFdxm4+iDSr5KXSfq21zJ5AODdAw/3uH3UY4k+FJcjw1GzgzD16CMC9HP5HLL39RAspe4mWVevbMwbG7A/CTGOVtMWRYF/R5kXDpYcsaXDJamfodV5WiVEDtL6e5z3w/kBDi33UGo/Y1TneirCGUGmdyL8hrTcwCpSGzLnVZpeP+3ZxVt/uSica8uxgdfkGjA48UH8JeNAPhIboLQ5m43xxrY0jwQJ1gyFKu7tBJU6LyL1Fy60MLnR19YnnEFVsYuoSeCBPSTsWpT4NL9bCiFx41G1VINDVUGmLWwer6YRtdkpQuJUblWBueC6Cpy7/YTYg5e6+L9Qq0iqQ4sTvHcXqeySCitwgYmYiczst56/d07JDaFu1N/VkmfxHJ4qFA9mr/h+dk686g3hIauz5PHaqswWOtg6OR87dNvhTR10jrt+3UvjVQdltkxsbU1uwCKePPW5M9aDfNVYzdZ9ajV3vpMASGcilnBtaEIyCAuP24jruA0W2yVKQxcd/3EBJkrJrG9XDcvWhkWO9g8T3pzQsaHWc2xid1cmdeXOZJrYLj2lYl4HO92DqFpEmpxrIZzJzOEI5oU+WnHO8wV7CXh47/l6ef+fx2r4iSilNvaFz+lZCwx06oHCpw4VQyCTJBk2+MzG1iZqwpDn2Rtr4xu2zuI46dhgX5x6RgIE3lNSrOMYhSd3LFATWHQI5H9Pn8wSFu1iC0w==
    MONGO_INITDB_ROOT_PASSWORD: AgBqcRiYQrkmwpQKQy43mkINcHBWcMKmULnbEhS6YmEX+UM0GMzM64dIhm+PdI/X4h/aNqq4l/TnM7xj5pw7C/aXSfjUJuaT7j0eIN53hTHcj8kiLIZAshrvtr7N1/RAXhvyPwQtfwnMcLiPd/EO6J4Md8sRK2dHfVFbjN5B4tlgd75brWyJg43z9ysIenh4kKCnMaxqLzSYSuH8+n4mE3btdCPtMfAfDwrVt09h9IAzHS2ddtmrybN4DzU+kDvoOFI6zcdLGEu74iN6tEG6KOG+XeyGGslt7pJVY/6b0ti+XPEV2VdNfDCk9Y75Xab8JvX1fYzx5v25h3YErJ57AdKXbcE3/b/47iaXOQYrmlRJW9+vvGkRvGWEsUsoiSI/DkdfrFSyUQ/w5RKKL4QiWc5zI9KwBrpa8DQGopjsZiYsuULzTMP6fLJdsI1Sk7ka+Rhsz0Yk/o0Bb1BE9g5Em95LOEwxA3lmt8ztyWkvgSdxksR84GWv+uOriuZYA9z7bWdCdM74jdGLmWCOGYkXFg4kiauzwynB521133MNvy3NTNjGhyjb/p34T9l+QRDLZkc7m/myfXPDe/oGHlrBBiuJLQg/tgmnAAejCXWet5GFnXosydsTf3SABmS3RvCVOHNc0R7rqcYu+9adJnrdcLPxzl8nLqW/5xImMlLKOfObM5Tu/JSqoNWf1Qes7vSO/Tfwt+xv/2Q5cZIcLuaEKzNlsxWJZWk/jfYYjQ==
    MONGO_INITDB_ROOT_USERNAME: AgCmZLfjs7afEAhDzy7JT3t4HAnXKQu1myO7FBpTHp6kyGvglUC5N5iXZZOgt5gcQFOVWBne0oqNzVQF4X9GVEvFj7avQq8VbUgK5MBGC7R4zTuLQ4XOsvzcToNAghmkUrfN8/16x3VPM7subiRiWVZ64mxRo2wEh9iTOQuKi1qRadp+ynjkWHmZVPx/2k0bKkMr34E7kNk6gt/7okgmYyaAhLfAjXNB2J7DPgAwDTH9E42ZjuHyg7Z+pZkPWJ0PluU+0Qiad8XcQllc0OL8ONW2Eri1z0ZPnAH5XhT+bcErvEbiiCEf5xHBrZ92yv/iH8Bdb1lBFgdKw5y8/QUctF9ZI/nXIVi+0RqVpGorAUUrnfotWLja3xcOm6y3e0XhvhoRKsrkpGxqCZEEoh7wOls5o6m3vNTOi3U15QSY94GD0c7DbA/zKLoTX5GgzYwVf49pdG3AKZlgenxZN30jAniy4JGG8hW21RXxpqKqtLUovhKGUG6N7dJ5Ag5vhixIwan4MZfGhKx5AFxbKa+Jjq4Rlpj4mrWYZ+VlyMXgKw4Yio9BlFIeVAJRjZMEixwIrfLnkV9WyKqeJ7bQEp84kXX17FhILvPeSY8oJd+ca9oGYWkpmX9WSiYfIvUN1StOLxMGXGP6QDh/n1l65fb4HyO4Caohh77KBBKxiW/DKvclMSYfkl6yJHuR6TYFWfFNh8QUAFqFIMDufixWDw==
    MONGODB_DATA_DIR: AgCH4X5HSHrmDsUe1ZfuSyPXAmKDnH4yUesdf4FPdMl7TfizmSlXr1CZeWsM5s0rmGrarW69YSQXjJRWT0EAJvcBgXJwlttKsQBT7gqhzi0vDJCeHB3GxbbRNhdKTPd/z9YiX422tmc6etV4dJrnxSGJh9TfOAJ/ouuDRpfhTd3TskAJpgndhqYEbFMid6geBnPzLnmzZpBaJ7p/EnYXSxMPNtXo0CKk6FSaSWkeoozTw3H6uBjgSj44mr2uEKiMo9cA1RekXg8JrzaOrrXDsJ+JKG/e95dayQoGY0LHewDcDSNxA+AEHvRPHGP1phpOsPb82bc0uHT917Tytl4TzlLr07yVUPgmP0WdhB/g/2FJx2l/Ak01u2Ty4WFAqeiX1qg2VDSHT8Qrm7GMWx1lTYtIjk9WN9x+777UKEGwYIm4rT1Gyl+ovlWHK/2hJTqNWTAtL/yQXR8gY6oPaWd05ju1Zk38s3piFkWKOH8iJdUmJLGl+QVZq0QcnnVBA3UfSXBz/TPnQLGUEOf8DMgk8VyTXR6j51I6xn/2pHMaFe1jx/FVGzBgtQwe2IdH5zlEJuaXMlxoeb37D3o7bAqv99OWjQL7QTXdqhXRZo7wYr0PlLoxmZooCV2BgviMSi8UduUo9d//gBGJoIMrCPOm7a6WeL+ft67xWC6kTn//nNbOC839OpfZ8n1Zvr/vvOXhbGuh2JUkSQy0GA==
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: aqra
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: atrenchevski@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: atrenchevski@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network
  namespace: aqra
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/network: 'true'
  podSelector:
    matchLabels:
      io.kompose.network/network: 'true'