apiVersion: v1
kind: Namespace
metadata:
  name: aqra
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-sa
  namespace: aqra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronjob-cert-delete
rules:
  - apiGroups:
      - ""
      - cert-manager.io
    resources:
      - certificates
      - secrets
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cronjob-crb
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: cronjob-cert-delete
subjects:
  - kind: ServiceAccount
    name: cronjob-sa
    namespace: aqra
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker/single/docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: flask
  name: flask
  namespace: aqra
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: flask
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker/single/docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: mongo
  name: mongo
  namespace: aqra
spec:
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: flaskdata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    name: flaskdata-pvc
    namespace: aqra
  hostPath:
    path: /mnt/aqra/api
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: mongodata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    name: mongodata-pvc
    namespace: aqra
  hostPath:
    path: /mnt/aqra/db
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: flaskdata-pvc
  name: flaskdata-pvc
  namespace: aqra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mongodata-pvc
  name: mongodata-pvc
  namespace: aqra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
  namespace: aqra
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - kubectl delete certificate aqra-tls -n aqra && kubectl delete secret aqra-tls -n aqra
              image: bitnami/kubectl:latest
              name: cronjob
          restartPolicy: OnFailure
          serviceAccountName: cronjob-sa
  schedule: 0 0 1 */2 *
  successfulJobsHistoryLimit: 1
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: flask-secret
  namespace: aqra
spec:
  encryptedData:
    APP_ENV: AgAnOc9NN+yVK4IZTU+l/7QtCr/1KftL71AO8NWbaTyXqKZn1fR+l0wWKApQxA8q5zPTNtCwvSYfnTgofMy2QnMHUJBpWBZO7EA6qEwinRg6XsZPxUzcpMycHGWbS0JlR5UqbHVUUQ9qQ5eLhU2RuuMLv2EpDEM782ULrLwZ+pK3y0QRKJMFXehjsB8kjybXd3PlFcKuCpNt20g1U80tSOromYI55tBrb5/058QEUKQ4BDpPpX6AN5apQHSU1oE+QxhrRq/jeRxSQtb1UHJ1Og2CG/YaDjy1LezEYPrBf/nrQjzjcTMhfCwjZmtTr3FmNETdbXygdjzNe7Hpklp8u3BRMS2lOOyHNFR4spi3pzoo+LxLOl5Er9smZYi8tkob1XT4OAsvLCg8S9ERMtZQ2EBLCunvJR2BtXm0CSXTPxdQoXTeWurxM/4m1yQ2CgS41IzyISatl1hgsPxUmHKw7EjSB/vItiUdUTUEp71LJ2i+BB4z5cvdKfCCOkbo7Nm/02+XZrYbEriyiPS4EMi+4pyP/IiTEjlUbtzH3Li44yAORblSAjMcHOFqDPDmPxAPMSRPqMYqvCXpidJ+EiBZIoKbpaczi1/FBHO5VJz8pLaNs0TtzGuGC1fvIjVTnmKvM57CUwPjg1IFC3OFwfyx3tad9NMx+8r4my9dCl0Qo7iFSEkyvrv8GHXxyl+ETJupTpwVBQMAhPX6QQjm
    DARK_SKY_TOKEN: AgBxaDlHLALF6r/iVUEZ0BmhvMlxnWTYpBcKQAf82cWoYFW0F60jNNZY7iSauJ1WAlhNLZtj3/8ltQxnRzPEL/xxG6pmQjnw4RVOwuNkrojdzKxN0GvuQOtVtjATMWnHehvYIwxJotVGusexCTWBdPVlIA+urvbyLTDTi16zxIbOulV1nWLRjL2ywXOJ1lRcxBhtgX4XnRTiHwUzrdgh3D2F3qhHOWdLuJrKaQfGql7HMIbtia6fy5waiOYOwbIbhCIJ+BkwEmZQ2chzE2TnbKdArgndeQnPMFzw1sysMcR00wOmSeMqDw/Uq9C1zr07LIVxy+o27P3ZIurEepMDvUQrdf3ujfh+IPcgBGJ8QbTv2mP2ci2e/XgJaZGBT+CBCsb66QdPLwN5YI6EdsE84Ii1BHDL1Arwew+7hdisgI37/1D3/RReHpbb/vOTt4KyG9uUO51PXqt/DhAY190ZB3ibshkExm8lJKHhjxw1TT9+edRBHcG3Y5PzGw/byjMIBcyarHPS7z0vc+AHiko66ogy5VyIU1vwb0YKJq/P1xfnZJ2msoD7XiIBrwXR4Lzji6uBIbqp47t42yeKO/oWBtBAsHN38YUNmyzVk1sWJVyZz+KaikO7XUIO/aP3l1SCe26dpsZaf9IZXYC6G5KxyNcBhmpT85oBpaVVHSCnXMOxc4oFNfOCxmJvh4IIiXGSH/ITSxlY95ruGynEC1jOnEJPUT9VugsRyrhp4eE7Ak4DCA==
    GITHUB_TOKEN: AgBYrImQeBCMFGKeFcZWpT5U2Y9nZISPpYjxT5SumRrhwOq74a1YTK4VO/PXGr5VCDAmsse/cqCx7dwr6sF+lFz/3gat+EyfkxcCxDkP8CUH6zYvE49ophv25MC+nKcSUMz37gyHyuYIBz/UwotOj9x/ZFR4SbjZSQZRkkZy+42bG5CdbyoJx0AWPIv8hk1nkAHj9oCJQFMoobzVRpfbqi9tZO+rcfOwlo0pKlu8IVFhDyWJeJfpFpiWgS+u8Qa6xWFSpkIrsMnzejvyGFUjgO73x0NGYKqihT143CH3BVYB15aEROPzobsZ2VCIzAWdmdjiTbYBC4YKE7D3kaG2dau9CFO8hP83X+ehuIIKEZ2BwmUgTCsQ56Mi+5J2Kr43OHG432UvQCrohM8dca2s0x7wN5/IrfzUyapEmJf0bTVopO1Wj9EsTcMa7GfTHegHjp3Ivp22Be/nWGY9ee6e/DDIZRPdAhsXQ2MLodGg/UldnLBNzMIdMOs+3g8V3eEkxGkHHSFJcbnnfuI8Zg4o34gZTdRU6AwGCHf2zie7GmQGZaQSJA8/gH592SlLFqd0ljnb3QeWLzC3c5/gFiC1ZEpe5LIBbCFa2zu9pVPupu4WDjruIbkpEyM1rxgpU2Wfo+zDDhhal5E0J8keiZte3W7Ic6r4CNRc/aSuhaiOqVm3T2AWVFwTrdmMFEUiK9fomwqG0uj9c6r3ElwBPbhNhoKpTyZpBIP3T65gh5jlRfy9bW3Bqn3VZenb
    MONGO_DATABASE: AgBXddYjgHVBLidurhPJMkDBujdpOfJFIdOaQlaTdQo4Kjl/88IQ+68IkZvC3nDkWIzCpvS3hrRnT3LLM3jWs9iPYYbrnneRcsC0LHp2uZZ0tjdByuPuMteodkYy/kZExTZVWcznG1//87FNypd7Pbhj5hsWtuw3y+Hrww2zMiXH9Af+XMW3F752RGUhoa4nwi12nHzZ7IPjyMuaMpt4iB1o5rUsBoZLu3+LEJNiEVp9WVbOL2Sifty/a00Czj9rNv1pdSl+ZfA9KmijryycGc4GK7Lo1y8rgmmymZz0dl2DMw4mq4RfCVyUPjPcXWt8FTQUY9Q0Z9qlS2sQm8MkjmhVkUFTpXzguDHF2qBec8hToW+BFYdohoVnHSVHfx35P7O298Ia92i8lzlSc3cXjQVENTXoIZD/ygT7adfVqsXuASnIkgb+t1FfQdKI3eqDe40QkpkdrXVGacLA91ljXb2NygRAygYzEqLuxwVVNULzqGQT+vlB2XdcRUJUHdd302VY2IQCioMm1LCeYWSLjLLLyk9Z42t8NdcLyVpGYktRLqyOFlyGt6ijK8sJelcaq/d93A8K/FJ89PJBSJWWfJsTSX4H+EdyuqoFm0m4FOSgGuUWwnMe/1AwVvQSTpAzHB0Qh5wV1uo02e7F2Omx2rl9sXow/i0oVRvenUnJjJ+rTTO+/db9AYVEhJHBBTQT9sdeqcF7A2A9YU+x/g==
    MONGO_PASSWORD: AgAXfEvmRjsb+xKFuuRML2dgwqa2zli6I2E6P3jCfrhLCp2WYU78U39M5YnEkOfbo6/g/CXxYsUNwZhNdkC+6xlQjcuwUplZ41oz+Zj6uvteEHZKWFfm5K07rRekfkbDGto8/X1WE5nL/qCvaRTDKgv7MnTDdS30NEM6uKTmuad9GFdStntJT1ZurAJ3F/mDHyJThqT1DBZWGRPA9kc+It9UCbKjOWwfA226QNPqNo47WMvKRFc/kye6NHP2AIBHQcHvlfDGNy+HAPnyV1lDSIdbHLntZiQfBlPi4R/RX72L82tDU+uOM02muVwPeyo9G8XKmq42aby3YWfRnpwr0Z7p+PYWOYmeMP4IA/KnoMzMqlTbFMhsRzTaoX6/FSE5ig4PHxKrqRGaPCDTTSA3HtuRB+iPWvesTUNfBE3ow/QcpGQD5xC01SwqR0WD477pGM68I/lIf9YefGqTtatsUGhrSROspd0FjzOlDDFgBRFUP0FHbx2kRz2i2PCaona1QTCpnjoI8tydDiZTKVDgOUfZrlTw75/WxbIwWmoY/0pObHR7HjPUPWNf0XUUYN0MdpDMVHD9hk4+SV+BFPvkFMolopZyySAyxgTSNsbSOnNziN8Id88IGX77zmjjFGUznhhwpUwpgBFEQ+Ec470c5o1GpoytL9MBGRiwd47EEjKinLI7/acsYmFxtoSRWqG2NU8GBAmdCOGfHW0YcRsl2Zw=
    MONGO_USERNAME: AgAJVN4yXZVg9BTISPXro17r+apmSXHKJNFcXu9500SrG0kKjmLEYsoUyjhFzg2iwkmUiliNlpCT9bzlnmczc6g/HToIu0MNgnpEXUwmUjLhSXs0ewocDpoRvIqzODNOn3vWU8P3BZbKg3x2KqLb8gImetZyO5W86TmGPXfz5gLD5JZqjHbh2do+UCSh51u5goRGtmL7yNtRX/pctuZ4bvDFtfyWR2BPTxvOOnpBS5/RfTOJhiRAgv9JuRmAFUOr0fELmooVkcveLn1RRRvcvlewT/FHeawNdZF9qUfCjvvJ0jjktqEyTjKAhtl1nMIBsoiWV4DQA2lV7NdDle45AKooe92eAGLEZacxvm57F4aeSoF+G3WvO5tkkf/02KDY1d0CI6VJIkbDCn9l4qxlm5gwWiQWvY+5El+afEqypjAtRjofKLY1nV6Fgm+VEpZA0xv7/Kt8naX6FrHJl87Uu2eN2wsVsQ+tRgx9RMcd1ihxuzLN7oOYTJBZvvPpysoAaeK5nfMrtKfVsw8zUqSsq5lwk0fFoKUCbI0OtePxpieauqc6dlX4InmOr7QJxDeci9wTen8mohlKhKipjbOG+3pnOU6j2OS2TDCvV7uTSyLX150HlWXDjbzO25hctXmUaWryoNy32YU2UpbTlJU+eFXXcB3/9gAPdgP8fHNwHpRhdsEiZeCbOVQ9hOXY1vN1CkewUovnJKFLdcP8zg==
    MONGODB_CONNECTION: AgBB1Rkh6Xkr/10P6hKc1Ijh3Y26RVQB0ahjfbBtBnyw4JdczV0a1Cdi9G6CR+Ivm/jNqu+I/RSgrLP2ulqQrkq8/qjMyDW0v1Z0aS0046lK6NJZ+ehxjTTWMaiyJxFmQqQjBH31Im0kKNrcEMa63qjsSWGnZhJ6yI/SGfq7Laz/imWK/Xt2zw38GkmGWAM3/BotR+FGYGPqmKM0EKSSrIoxbUxBoLpu5nTu9aK0ZnzWpYFHvTxaOPo2ZOtDuw4E6wA0Y0C3GKMiZ8drKznu6E+vx8uTHdnXZ4Ervbl1KZna09WAgNP6+zGhj0lQOMwMf1t2ZKtKZ2fZeL8SCKg0MlWdeg+gTX2jV2ivF1uvPwYSV2sBiSv2BWrY0HR221H+87NcWoZk4VQRShnPfurtlMC1lBP9Lt466A+995DUPg1+ofWJkUjdEhrlD7dPtyMrXjBJzE/f5LQK01c0iSf+OI2l82t44OOpylXW+OswyeFmeYFyiLr+MXO2tlghvmWYzpGVtGa6QuzRdFfjXU94GababSUS8ULSQ1MzPRBxyJYHTAMv3gzk0fY4ZP1zaWXYg+dIT1xfnJauy4zEBRmhiRDv8FeYul2dS1W6R+a5vZxjUZlo6PoFErOH/M4xmFMAUhHFJ+cOwxcyJ8Jc30bTXGw5Np95aeNhK3wu+RsMRdrgoScVeXK0qRT9dFPpWrsn0jCKV+HW1K3t
    MONGODB_HOSTNAME: AgAv5k51t8JGyHfdEKDIaNTbdYvhKxev/QgwKiq+615CnR6gXxHWtTZXTNu4jbdg0tSmdSW4mjneAM/V9P0xBm2Ahgpu6zsGjVRrEPGoZwJP8LPX9ych57vn+R3L38QTfqoxAM5XGp2/0YNasFtnaqOAIBjZ0SvTmgCTQP1v5B+e4HaKLQUBonQZxqw84g72XMwt4+K1u9XvYc8MnGt98KDCYtmJjVlMQYcxASfZQ19s1Hn8oxbWEZd+NE08d9Spzge0oc2RjPkXN5RapoOQ7JP6CaVYEnr+pMe15fq0/+o8yrmzPpmAmqf9fgZvOutVbIgtf+jt8wY8AnbrIGkixfC8Xdra8wBkDoSVGOQgEvTdOrXzQNWstDFjpBg1dVE9ILeKWE4vovepre36C6f4VBPbvupwmVB7lu1Fje0GHsXLpiTSwpbZM2Ly3EVOPiUtoBWmTX9/AOzOt9L/HOgn+ZDe3lHeybIBCa9fpUlDiE/+N4J3TSV+hwpUYQH67bIUIWk4G9VXhWNzJDs+5ZXuxsfjbLv2NdJ7vmyltnvGiB1eW2JvLVkD4J3aoP1nrn0g84FyrkVTzd2aZbxTtCSbphW1h3AHjYxxCVBgA1lCWaRloYe6aAVL5HuOTwYXCAUIHu+vZFL4HZPEYz7qYRkBeSlNhrqW3g4TXJsEkquz9mTDixVXeFeekU2H1smx1I4m44OakpHLxbF2ymRdnA==
    OPEN_WEATHER_TOKEN: AgBY9hZQwPuUc/gpwTwXZjCtv8Q+8WSflPcZZl2Hh1Fo8HUL/zmKBBPe/YLuc2pSbIMibFjXVQbRL2QNgvzKM2A8ZTAHIpztZLTSNCd5p1TOzqIrZDE7F1+BxFw6ZKd7DVTMCW6Zh6nnteTEhvdt14KxddQX8Bl2fWH3zG0n6QBDWcmRtStJjmRra3NbORXoBfhyHb+b5prRZ+QYWyeBekXWvptJOIUD7QMNXVxuM7nplXq9uh9nSiCgQ/+Yy3e2i2gtzH5DILbTVDpPaxSAScig/c+qaCbH62w74MVgF1180h00YgEzacvPBdM71Br2+9Hor9QZyqkw81I01MfoVbbPjRCs0A1Yg6qYJGS9ctScuBm7ctHA4rIr40N8di6jxChil4NWIp4p5Bnc+BST57lmLeTyn2GFOvhvy7fR1h8o+4i+1UP+6OERDTzB80oUQyLnXazit1+vKLGivqfyyk9DT97y4/E/pz4DtIpfovrZr2lyQpu4bkU/CjLqK+s0UB87T+x3dYD+sMBVbuGfBleq5V3JLhUxmlkkB8OGOgbbiLps53A0b/T9IfiaB61BNUNcIipFHlYxwCb5Fco2jFuET/cZJg0QgCd9vs1MTPtKE61Z+j+JJNB3CqN6RtNkt0qUO63yiawWjTSyl5i7SOW9N18fQpE3WnOS8+yHrtppqt0wibsqFkBFkKPJscVuyYUD0jznY/awR/7gy9bpeo5a6Pzsc6wMVal7oP1lj9ioRg==
    PYTHONPATH: AgA13eCkjrN303yBRiSmYaXOAXs6QnJnVqGDUT+zkOYkSHkpZxPXRB+6Vj3JFFjkAA1lqs8tnjT+nsormnhOitYwrf/NaXXq8Wic2b/RWnjGUvw5AF1I/T2eaEB2Tgbg/TPS7a/ZjMjaPHXWIyI+isUUj5YDhyM5oPWG73Af31kGGJEbmER17XBR62wWkKk3c+NHjFA8pFlhsIN3URJiPt6aklpi7itItSzVfjykCKV+tZ4jClcsoId+sX8zBZ9+WE1Fun5CQeWAkaEuuSEj6Zo3i2JKm8u1Z/0Df89NL9b6iZQ/NPcEfnuRwq8bSV5xzLAcUXUXlV8PbvppPExfaGGcq8Uh/1sfA6y3Zf9t4SLygpbCBZAqsvH+UxGnIIAPWLd4vRuh781GMG0UDM7bcTGPkcWD29aJevcgKuiWhehJuMmNbNTiU4F/dfrm8c01t7CncBic78BU3DyYyRskMcLyN/aizrLCZJpxWKs0fEOKtDrJ7MG0big+g0ki9ozOCxtopiJQdh63SlO9hnH7h0uV/3//aYBGeaGoNNNpRg119I50FRM0Pu1IbpVLSusxY9ToPL5VHV8kJGxBWxaJBC8cq7nkV6ex06VlAuWny6fGv1rjV0CempNIJxfSnVRfbYu+OHhvxD50F0S3WPJwpWQcBXwXxCTzd2Qty9lIw+aCs2KNG8RuMAoqzvjF0wsWiAhoVcV+zk415g==
    REPO_NAME: AgAPvRJ1P5hrhqz5Q18ViGQhogL5Qvil0MFkiXA8Q99tn9QufATmlrNrqGV78CC+NTdUHaGt2HBpAkUXDSs8LuvAvTMmcfEEAKayt1cZmqjwr+sgkbAFKMLJUIg8M6DRYADx4MVCcbtGgDlP+GSReJ/ct7j8T3zY4/KOvuxhnjdRkzvGbR1pApbWQ6G87zIgTnWN7ojhXikK5o7HvR/dSSXmxM2yOJE184yol3bqgiNUSLqW9isihLGfCEzwBDxTH/tyS83a6gyGuOl6sWhwHHx/isgt57wz+wamltyJf9w2rHRjTYep1doOIAwH8andxbytResVJCvC8JXL8IKTO5WC8G7GtTEJ9e8MOBrmqziRQebX02CnwNSa2+ErtbEYT+ftqF9AtFmTZcgVEj7rUi/QmhPXkPKS9aWyxaHdlSglFSFeJ23Fw8rSLEfwn3U4GQnChDtqtv1KrBhIfK2QZ4d70gEcTNssb4JYFA4ZwVxRKpS5W8fXv8i0DJQlcnQ08digCIAhkYTV7ZqBw5pGovsOKMWPjI9ktZrb1LDBgLHVlm/VAOpNggaF3RPnwEAfzKFe278rGSUMFw61Fg08hdTn5IVwYH7z6sEY6h0QiYxRMNFxSjUI92sdqwySNRUVzkHvbbjHBogQqMOcv8KOEXBe8s+6+2+MiRHarYc0FE53hCscy5FDrgnPg0tNQ08JW7Y0wEuHCg/szw/ymU/OJyPty7RqY3g=
    TZ: AgCfUnlU7mCvmty3obE/Z8edfWxHYuVOY99q2z30J3k3NJu8nIAkA3ZVB9PKIa80+R6/yIDTkR3i1wMnTFCYZQPgICvC8XcREhSZxhAvBE+ehg+2zk5PhGzB//PqUvgD15oR5x2jK6gOsFjrkBHtF9CchHxZg4GRxdxNWx+T/iSnq9uoWwFgY+BWIeOjpgf2cGU+RxDhNojTGalzCe3lX4aPFscHKyYnldRvgYL5izBnMFU0NFDb50Wz0KzQO71u5LWx0W8hzcB7ATQzssQJkse+AA6vYT3rEL28tajAy+hOHnT8ZCQgKdjs+huzD/bXKDarD1KTcSFYga5ikCiRXJhpQ89vZlDOrRSMwu53tqVV1LL18fJgxSFXtn23BNySlKaZxLNHfR57y2QivgbqXS02Kg+dhAj+vq8o9vCSevHb60rssReA7LSz7JoD6077jJqsuKo7+k5EhmOFi8IUIYerCtcivuoErCDVKO9jnYGQoyxFPYMyu7MWdgmq2eIO/bqcXUdKxqPKzn8u3mzg34s7pdZBQLWwFKqgKujTUqoSfpYWb5pBfkFWZdEhj7xHBS0SfiGhidF03NRVHS2o30pWy16FaON4EPnNaGWTZNsQ4BN/UnOrIwKNfOGGJgdSRwhDKptkEwiTX9QPltZErD1/9zlPCKufz5fjJE8XR0gB3/IutMOWzDu/Atp00qUXL/VaVp0IxDGRC7ETtn68
    VOLUME_PATH: AgBDf5kne5l2YrhfekAq9uptfOczvxiV/CsWCnGlCe0qpfCmqdK7+VOosPrNAwkxXEM4iC3tDu++sLRt7fwKJ0OB+l5bQPQR6m4lHoSFaPEgzi6QnU3gOaQmycVqqRgQDbXI8yPIu9Ok/4uBNKp6ZD3nn5cAdcw/DzrCGxu0AyLxlGgdO7GOPZs/M/JtXWD8fmtYTVNkhgKBPjWJhOAhXJyVTJar2OQziKiLtaHegjcx5OQ75iut+ccwu39QqnHwBGZT2YcPZnB0gK6SJCcvEbaFXZW9YmiGOQgUC9U/0p9P8+JHFYdzgK6J3Qc1m+mVwIwLbXlZ9cNlfCGUbbP8S9+ugKjyOo0wLObZ/3W6Ld2WzCqZ0ghG9+vyIlF9svfOZjCZezDx+4bi5SgD7SfLPG/U3rDNyr9QGVEqmkJgaTGTto3QFT/tR7aFqABNI0UAhd5cuDqbG4QWBGA75GZvTt3/vQv4j/j5qq01pPiOl5JzIjWlECvw6KUAPoxN6L71DqgGZ9/1k3B4cknkHZwIAKaFqRUrqAqX/ZgBgxlDlUZLVM3cYT58EP2PjYF7VD7cHxVPbIne8mmgkeq3BLcLfBc2no0oHKZ+heT05UEI2S89oPqHIcUIaW4NyQjuAwQBOioe0Qs1std9g76HxfMXGL4hvWPEfoYNQ/4v3UM6WjXOkogYkjYJn3jI40KhrTb7mmEOyxNR+HEQQA==
  template:
    metadata:
      creationTimestamp: null
      name: flask-secret
      namespace: aqra
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secret
  namespace: aqra
spec:
  encryptedData:
    MONDODB_LOG_DIR: AgCf0f9T68wFlaR76CSKuHJMet8T0NfQtr1BCpz9f9lnPeML5lNSKn1nGbODaZP1QIuAW2TIVMEj9MC8kPD/1OWhl2A0i4CbBqmOsoFPKQ/UrA7YDdVbgXAGjRpNJuQWuD3jCLWfTq3k7Y1I5GEZnq4ZDXkkXNoz97+GV5JB7N3IHRnFudgS851c5IcxWCcxG7CsEWyXJzPzJh9AyP7ZxEPnXiEpSBLOHFTWrz7Hs4W4v4OvUe1TYN6OE9ch8FQWw/+47wGEfjs4PPZ0NhEOxAHSLENgJ1S3LRr8LGZ+ML4kZoD+Nleri8Xi43PXPYuT/L1GpdDMG0VrLmOZpPFcNjaFAlkX4NLm1V9xWPK/Mhawb4k2NFBJ1yrp+QNQ+O+YSm7AfqeVGS6s7ha+637wSF6s3zf3blmev/Sp+AAx3w8kKUVKI3dAFqvAy18PTpqdpMVXu4a3/XNjwQu3Oe3Bs5LvY4RjHg1YgbUf13OG4oeuRVkKAiRCJedaPgnE2qZLQun08nZHHhUf0tNt4qoGMTo3lZvqzccuHoYK+b2WAALGbcN1n7bKFZpoA/AL9sWqE9Kz4pbexSx6btg7q5NDAcCOXSgtm0oo0wohLC4quUtIIAQdM/+wNs62xbpvOSJK5z9heLZLGERSeadi7TOgC3UfcpRhEwTaIiua9lJebl7SbHgZ5Q3G3QR5u6wbOT+ByB6OzNbueAApwiw=
    MONGO_INITDB_DATABASE: AgBAwkJioNxO4xFzh2Y8Y9L/2qkg9l5pymLfxDdnB+s6N5z53UJNudhLEGw9L5hw2tOpHa26V0PzylQ0mqw5zsM6/F8eiGOrtruMF5EevfTBd/JsLml08mUzQ1TIEB+Gva/RYe5bmLRjoNAw9NCeMzTudtsf2+4DZpib9XjUc0kgrhTNe4KRu//a/vJPd84yeC8dx0kSVFtoupFgkCxyvj0spgZ1+3fJMMBD6z7bhojljDgc19S/NwlOugERev5AEgXPudc6oJ0c60AWX0sAPJYv+pcGJToXtqRftalBT6szsdMIt+6ViatY9kCSRs74xK0z1JFcnW6fyqtmaM2nlVjpull8sp1tvp3ppzPLUHiL0f+icgqDtOt8VSH9j12wiQu3NO1o6AIjoTQbW7zzUt3DZBC8ohxb00U1uDlmpI2ZSllbdnydt4Jb0O2V0d7K675eFAAdyvsC6Dh7LqcE+DQ0h1sE4SzyVQBgSbGzzPT0BWM+y2jU3skh6ndyHOH053k3syyz9wjU+c0FegWJ4f8S+RdOf2wI+3sJTVL4U5sH72Mqe3LFd+zj6S5VSZD8/NI36WERmyc4T/zy7oSSXindp5zkm9Vg8r1P6A98lb5hEIhIqooVk+zFMZ7UXYkU5ldPpRSDsp0G46kyhqKiMFAJb7jK3YC79RihiOZWBrt1OqST2Bbfd3mUyT9WMcmM91HAXn1TVdlM/V/MQg==
    MONGO_INITDB_ROOT_PASSWORD: AgCR8P7eidUWn2iWM8Y/BggRbIN3KXARjcnepAP15aVZtZ5J4RISmSK6no9gf8x9/13P6PN/OnTSi3rqE6LU++9PyR5JJV6NHczNpvDjTOfSoQUWhWvGPSqOzMR1DLV32lMaO7st+xcx1JdslJ86C+U7HgIovA5zpE8kv6CNyq2jwV8SHO3S1r8mqxa4HXmrkg02s5+AR28teim4TrT97EENJBaM8XmZQYW3fb0le/w2VHqNuBHZ5b431bSlniQfAijRt3PfF6JV/Xso+n6DPjAAK0FuuEYfQ31d5jh7YVMNFLWt9En7fpsfHXuSx+wv08zQCYPb3FhibJVsCGstO5NdaHKtA/0qTR9j+6T5S21qrQj/y6FsJkHZaKCosCaPs0lu+SKMITEGnFN6W4FjS10lIJldMR1YKMeGBLJ1dU5pIeYFEcO+qtPcJn0q1oEn569btQlhuJX2tER8lncKv9osTivnod6bHr0+wiMXhgsp5v6z8OdjbEFQjlqWc8u1DdzU7gpiqWY63Zq3gtAJ1DYmmB3vuX7JKL7iv7PfyGDg+3/Ly84hvgy0RiprbA5UWswnybogosG5wDuq7pI1i7V3H+FYlecCXRCzxvi/ja1ERbZIjdF57T9rQVS8pzzshMgMMfO4MdOSAb6sCViB7D0HXEqHbAmmstaGP8JKmbpX6bMQra/mQ4HFZVK9JJtXzVOMT4sFlAVDejeRndw2Da8=
    MONGO_INITDB_ROOT_USERNAME: AgCkxTzmiVO7CDlq6mx2AN368FJ9o3Oka1PUr3XgU19vU+xbHIb1T9dbw1NDTOfjVrMEy70xTqQGWTNNBDDVIs3K2t7B1n030RBrfsl1sTo0mnXiU5hHnSh40pvIXrZH61BFcVj8fmHDil/vt+GMimnY3y8wIVO3tLqK5y0oBidvVHhRitl2j2AsJ9GDrFYAfnzJU+8nPbPz/g+8X8k4NaNcy57cNvUnM6DATw/PcM1otDFDhUbQUFTt3VA/JQoXdPFs3NEC8STU2hEavekAM7onMbycd7hu1W3HbPBxMf9uiOizLsJ+HsARDMtf7qNSNRKaHdgJ32tFntN5zw9kCHW4djUCf277j1IOKepaYmGhQvBDic6FCZaYVBsUrYOgbrhhLx2CaUTm0KJD1HLsXXZTPwII5k11X0MKSXjnXLPLwrD4qNfmIC01YVqOd5MkX6l9g+zzd+ohPZPQc84xhEV2PTNgO8mRtvMq9QGqKkmGM4MiC+k0GooWqnZwnuvwMmqghISV1I2jFo32Ll8Ppc3SnD8orX/mPMSegC+XOFGBBpT/NTRSM7tlMPWtjSjkl1AGGXEdVrJYaPZac378sbkntvubda+gBehV2Wpq+e+D9mFughy/gszDl7a36rsrksEtBKsSJ33aH4+DsTi/ThvhsG7rgvpznwQm3qfAJO+KyCX+pOUeNE/XPVQ+d0PrJ+n2GWDY2z/YUuWasA==
    MONGODB_DATA_DIR: AgAXtfSDa0y2wNB3gnhQbzyjV6uMrbZ//7g0dV9Rtbb65h0WfJTXrwoC9b7bVknmynCMwEiz2ayUZSfenj6UqpgQ19pLyiN0qlDC4rUuz7+c51XwPY+GFL9sMtjZN1wibMwPfA4lIOcSVL5uxGP1TTM2df9nidt1N366KrEPJE8Oo8YkMeZgGvcb6ANn/VYMti5ZXE3n0egtJRVD4GjHAuf31BpQn4YeuxMW3p+u8CraQSHiYY9/CeQUWeRL617XurW3JV27lEy5aBUi+nUA6hNRDKeC7oHCc9QZAzruQndQjNgLMwz+xqnYCxF2nyu7cGhEY0TbES2E/4KLkQioY6TKTAZgAdwCikTHHFwn48XWz837PUs8xGARO+jS0oJSsMjHpD2kHEmKxn0n+yGLcSAAVp258JWHC8iFDN7sMASaUdo+WuW3PdtG/uPEo9G5L5Ku/oEP+ltn2ol5blK5ac2UxK+B/CZCjx/3Wt21zSX12XFkaNd6oTfYfNG42x1J0HShzRGUqFePPVOmY63lZsq+yBIdtHmDocyFq5ZY7F/C7d1x9nd0d4U942fSw6YfJKMFOv1crI4lLvy+Jwr2pYaiDA9i0jQ9Sxrp6fHCytJvktm3SG/+D2YY+RB9iqmOv6CF5Hs3fAc6qqw6s5dUrLFpkm6A9L0aeDSzecqeIwM2Jk5VD8yPtjlNabbYdjX5r+c2qfrNgfqx5g==
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: aqra
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: atrenchevski@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: atrenchevski@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: flask-ingress
  namespace: aqra
spec:
  ingressClassName: nginx
  rules:
    - host: aqra.feit.ukim.edu.mk
      http:
        paths:
          - backend:
              service:
                name: flask
                port:
                  number: 80
            path: /api
            pathType: Prefix
  tls:
    - hosts:
        - aqra.feit.ukim.edu.mk
      secretName: aqra-tls
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: aqra-network
  namespace: aqra
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/aqra-network: "true"
  podSelector:
    matchLabels:
      io.kompose.network/aqra-network: "true"