apiVersion: v1
kind: Namespace
metadata:
  name: aqra
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-sa
  namespace: aqra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronjob-cert-delete
rules:
  - apiGroups:
      - ""
      - cert-manager.io
    resources:
      - certificates
      - secrets
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cronjob-crb
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: cronjob-cert-delete
subjects:
  - kind: ServiceAccount
    name: cronjob-sa
    namespace: aqra
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker/single/docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: flask
  name: flask
  namespace: aqra
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: flask
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker/single/docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: mongo
  name: mongo
  namespace: aqra
spec:
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: flaskdata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    name: flaskdata-pvc
    namespace: aqra
  hostPath:
    path: /mnt/aqra/api
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: mongodata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    name: mongodata-pvc
    namespace: aqra
  hostPath:
    path: /mnt/aqra/db
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: flaskdata-pvc
  name: flaskdata-pvc
  namespace: aqra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mongodata-pvc
  name: mongodata-pvc
  namespace: aqra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
  namespace: aqra
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - kubectl delete certificate aqra-tls -n aqra && kubectl delete secret aqra-tls -n aqra
              image: bitnami/kubectl:latest
              name: cronjob
          restartPolicy: OnFailure
          serviceAccountName: cronjob-sa
  schedule: 0 0 1 */2 *
  successfulJobsHistoryLimit: 1
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: flask-secret
  namespace: aqra
spec:
  encryptedData:
    APP_ENV: AgCl6eISGsgigmaVayFNkdnJ7ucc3A+W5FLN8Rc1vH3coZ/oHtHXTC2Yuc4Z8OhsfYg6GLxu09hZtiqXiK4YW4Zz5QmkyxvwaMR9P4DSCZHqN7Bz8/j9XKhGWhPdIP5BGIAg5F13gUJWX8QPnI+zl2TVD2BeiAHN+j8cxqJDWrlt6xDJsSgXE5Wxpy8Uv2IQbKvbuTOkkOom3Zy76JCynKj7LuqVy5PajAzsorkZ9wsXSwxJJh3Fwc4JiKe9SXiW7aL08kyNtCg4JUuHtdKWERaM8kfFNpo3XY7SHVkhhKVlc3tqrK8KI2MNq5RFBZjXVkuYKA8KM6vVIrZd2w0kwmUtb1z9yFuxYmGf8XmWpHief75OXOj9x5y+UI8J8nXObW6WVA3G91TgOqX+yY/RKf41ugXa8WLaQPj0Sksij6tn8Lm1obDVnEYCMxmKGdvIIGRwRJpUyXHhsHzn3hgv0U7ulxhGxjik9yo6NfVsdvrIhfLQOras/Cu9A32zbzhbGrYGeymNYFGar13zSHn+5GiNS8cEOe+XBdlw68mgrjhmyWO2re671E5h3d4uJKnhbUO/YoGxGqNe4rcoX1d6jlxvZ8Pu+ViVmg8sQ5HcqOvnbvW43nVXo09CIIdFsfpwZIZkhWelsOUQs2Cv/OqBbv85QIWP8Me+ZSWo3ylk2GFuQ5elt0kmKAmlIIz8I4iqxGpHoRM3g15jlkKE
    DARK_SKY_TOKEN: AgAFpUQaU0m9HQcAANhX8qQWW5sdB7FOSKgfxaGXDdwlJP5ldaVLa2B8vz4eZqAZnqp+xRGTSkOkeHAbW6ahNHupZlbfUz7Q6Euvb+DodvSZx4hGn5DBWRCa7A3aoWUD7OG6gWDz6IY0FOv5PpnLKmdSFguHl8Kaet+JxZtevP3hPOcDCxSHSRzc7j8HBZ2fSSl3o1kszBDnxp1aC9fblrc8McUR84rd+Z0rrxTOGqXYNSu5oGD9BtkGJ/WJA3xznWb79ih9/bJJk8Oem6ysOVjM3/4KpYMhYPr7Rb3iQuwgqZfrNTE+NJtTLTZcvvUQBnIzZPwhAzk1bGW8Vzzt9mgXv3E0XvfPGtCgI0O8aIgyDAoxCGOpTxreseB+foOVPqiV8Fvp7tilkuDUTnjr6vgPtGyXJoH0AQk5LCGy46xq1M3UMosdfRPVEgwrFbBx98yW7HqYZKdU/+dW7GOILLKVxXgsNymkEsHB8t7HNoLjHHUFy+H+Qmohf9cz/x4fpysHhqDe9i02HaaxWVDkjSjYQS+xE7cWaW2OHM1jS63PDiW+DbTks8x8NXpn7ozirM5YBpUa1ulthEIEOVhSAty0V3u/6pAb2/EZ+gmaGKVcyzojKgJDw/yNr7oILJw2ixs9oZq/GV/V5NZTzF+M66DndDcSaWMbuaVPXVhhMjSIFX7ir21pjXj8oeaRbS7y7bd4gM1PAAtQq6k3HhErkNfgrjZWefnPg1P62e51NNhcuw==
    GITHUB_TOKEN: AgCF8xuEGzQcWkUCmFXWQc/mLB9JmMpFuTRF6ezlOOAiYr4yZsYcXlZEXiyWBn90M+oKRMg0Pcw+sr4voQWx03YqO6XKUjpw9a4UsReb206t9YFYEG5IdhsD3VXWHQ0VPuS+yCJa9jiFM82X33pZ8EqcdbpiXr33JRdQMZbzjIeDNgJvQYlh1MPbK3G2vKJU9FZYDzhnppXcI7RWlbOvCoj1jE4GIzf9Q97+cAm5K+nBoqRHqEzCkKXMXY3TXDL9DYLEVB4Zi7fzb/gZqMfTYb4sl7d4wTFW0MZ86VKh0mFSV19UI4311puW1c/lYY0mgxLx9NAXw1btwJ0BcR2yJRypqpRxze2eF/kABmjrv7apu+IufgJD1qxGjVYpYpXCB57fH3hGorK3RC6JA+NVndiwYlCDbAYtX7MDD0gAmv2hn3FJUPvSoRlQOcpKzly/z+rR921C59ZBUqx/LE0OkCvKHPA+3mK3b2+pdC50OICIPtukpz90i/Tda3yx6Km5vErhKLbVG/fbgTbebIWdto0nasC3T4yadnqSGo7PhrZL1xnqCkYN44MUK8ijOjeoJqNCEAIHgwJJON8/a8cozuLA2BciVTsRm+ENV1/JqBxTMxJYIuVVP9D07IpWisjP03qnrMr0QNj5zdjJF0Mm2ZEqJf0xl55MIl/KU7Wt3txjtVSyKJAgvvHxUaau6wpWPrgcFetnNcjcwGcuvZYwrtFh1/92q0ocGRQRMhP8thvxrD1toi+VL27T
    MONGO_DATABASE: AgBX7tP1ijsrFvFy01puPHJFjQwerDIUrIZRUYJlkxhLUNzDjNUEm7ooD+4msOMUmXFFaxLZhJYGKEQ/96GJJZMoavV/X69g8VCpIBMJ4OXFi+UV1TEU92nZQ9K2+5umj1SwWX9vl/nBZIuUhEgC/CvyYpT35JqTsJTQXWEP+le1DRXb5hK7TcHiv6FEHum8DyEMJsBmhCChWFwJwK7UemMB1MmnIe3E3DKLx5aRqW3w3wufZU6B42WwWgB+BFN63uiqh2M+FF/GDgox0hZaceRu1K8ooWBfdN/CaVabhJUKON/qKpTFMCvngLzlzYuzrGtJbuug3JPf9BA8Rbxz5EjzjCH6UsPaE4UU9RhwT9/U1FhIDqcWvDvS0OyaOv0Ru4fUVuaenLzyuF0KieFXZXU6yPseOrXdINlJjGT72a0r9cR+k1dquZ+Xrcwe/iXZ8+HHWEFNROg7wF0aC2p42n2ZCpawbIM3IQycbw6FglsA1/blB51gVDCHalEHWtzpuiAmJs2KCUTg8P/MmexbaYfwTfvOqh5QIxiDwJ6g1UYA/Ae8F2zgzfmDvcWx0+QHFV8y0kBOgoULKyU3uOJ8hMQ3bqjHmShoboMC+jWDwHnU7nY04gRwPIC9Sr8rOFtSZ3YQDr89AwKgAIGHppdU7rBSx3Nw0rpyPSakl2oEhR+tfmrz4oD9mSbmFdr/QNlR7pUnUO9e7+wiCbEjkw==
    MONGO_PASSWORD: AgC0dfKT5VYRqnqWRehdDNCRr9ZGjGZQJ0sikTzNTL27MNO5ZvyyrblgYRdREFDAFvRHEJ32Q/YYbePmUnXRG/x8tYz6vvR1ksjik1MpwpFhw+HTnf2djsGNyng4Vu0e82xDpW39qfePpIJpGb5c6kpm1kLYjJa3S7DsIfTuiDSAa7aD7/OHcTDI3IxpprfxkJu1v9ffw6CdIlwjKXu1Sg5BC/6weCqIbSWllbxjgEjg/q6fJe8f53wl9sCyM2S2+H4/A+SJwvYXofafHEGZY8UN3x7rNdvsSc83LmdB9I51/294ed9Yd/H19IjsBPMx6dLKTzBNlVaaqcS5buzdc2BKonqbOpAENrddkQm4g+P0/9t3cSWEO7bH32VizP67CL7rv6+QijrpVK6vPckiuZOveX2FTbmA72cp28wnAURn4OTpEbaOJG1Itry20ohAY1YCaciV+goFPcSTUpZvwCxl2f3yCz5mC1iLO7xbzvCkrL/5Tz2+qJHEmP2kVbS0f9JA0/HCsXmoKouG9bcMKWsKDrak5IioD13IyWmbopyfF4mj+QNy4twI951ncrQyZ1kMX0AkjaZlUftYmm3tQ3vFnsXTpArrPtykPBF1gsnGBGv3X+jXejFh39lno31whbEEYgeY3hdhqGdW740Ua6YCbqH2U3ht9564dx3SqNG1+APiw6oYtvZWNc++rWb9fXgj4VBEY57nkb4dM546iP8=
    MONGO_USERNAME: AgA6MEae5ZFBD7tGdKe6nqOQ/BirexcNNjRjtdiKPVlOX5V1JOzKGX8VfhjmoerOVE1owNCtYe5bxZKPwlZEzuTWifB7ky9DzBHalOp0yRWpylKcr9QTnD650wAG4rFwpO3wt8n3jmwKp//cvSpzoRla9YBe/Sbm9JksJeYIZVZm3r45BYso+D+tuAchRCMuzc+Q2kh49/tZG4gxeMmKFv7mztnD/qw5lB3QbraLlMjgHJxMpNk5kFd7i++MYmWW8DCw/Dw7GvaLHqKHIHmuL1Yg8q6QCkSjY3NlGU9xN/PffN8aeD8/rvyU0LjyNygl3IqMxtwabElTevu+D6fWQuhFyyjXI3EVqJ15lKae+GxW6CBI0+5qfy18zkSdLu9BTfuUULke0j2o8mWJyPIEJEVkMQY0RYACk7ZQEDhk3vEGzeVrkIQytXpVrSVd/vwy/gqiDjQ9WoSSlWmBfhkFOGjZT5fZHAt+ZH6vVZojJVOuOr3pt28qldx6qlHql4/zeJh6uDW1cY5jeDzExsqTLygJPOZhnjNuy6jr3GtWyesB11JSPFjXCMve+4DnZJ9NIPwlZ1nE7CFXSTi97nl6UKUCA2Zv+cXonOhFnUuEkdXetoOs7f5QprKNfjeYUTQ7hud0losqACAlcsQZB4G1z2uNB4WR9XhpHXM/vPExfB6K4qubyaqI+u6P+4jGapT0S4O2a/QcqpgI/Z5eSQ==
    MONGODB_CONNECTION: AgBCz2FX39G5WU7ODfcjbu5gyWb8413M909jcQENptanhTB6XCI9X5xuTzaE60nUL7UoCLDSC3WiDTSClnQRY89Xs3UZ4ADDlDk9/tlZbgbwrGm/CkR75oIJHNZtIWq3nN9hKf0ZUsAs5VAwrfb0WCTks/AygNtfqgm5aMCqB1NvnQkyTJYuEeloxaWG+1bInzCnvHKbNZ+f+eea8ZI8eWRUj17W2LrAK5ypVgfkH7PsPsTbEO8bfI8J12Z1+6/1H1BMaHJIjYt8KtMiDosmyOxzMvhRA0Qchh/uabskQG6lrocDugfRpw/kYOTYGBPqtna8DVwpa3DBWohIb6OY4Iz44JuBzvzTBtvIJkLLaOb17PFVOD+z74Scm4HxC7tBsD2LoyYGdfWaiCyqGBEp0hQbrjUzRO3ZC7oNiXyTF4G4aSIL5nL9foGCmySnURHBo+7fDgb7ASJGdg8Gpu8tduL4L5vPO249zZZId8lw+AZr1Dq33vJsuQ+zVSOPilDrZk0aFpb/jmt9Qf22/1OwVKAHLhnaKmwmX328oSzpgnnnLzSDT3S43pYdvgrfScLRHbaSPKyh+X9WEgCzOU5NqiarjyTgZchDm/u26tC44hTDtHv9L/+uNvHNWKEl8521/mIytQk3Put4PcNfoWdVa/PFRsD5mYHCeN5I3zvLvJ2+KFvDLPt9kxPdbd8/qekyowN8Xxs7oppc
    MONGODB_HOSTNAME: AgAROF39CpqALo09XCSzRXa2aZPOLUJmX8CwiVuYYIVSs81qol/znyz3R7HPlLD9O5o/Nz2xN1MTX6VSqJWfwuHUqrhOSb/VGy/MoiYQtupbK8LSQOCeousdh1/m0T64rZYcPyLpFyCj0ivxx8YIMtLt+7aMtLx5Kbo30u+wX4k74oVcM2DgerXyO/qlu54E7J0mwCXiaoNmTza4/tuvl9ICiOcI6oNVwR9mnxi4ogNr0u5PTTucCmpZoh9wihc4CG7zuVlb20ICQV//ATvxhI15UxBWoCiIi1CLFmSoPPE+s+tIyOaVmdqkyH66rKB9ypaEmwES9m7AYRtPMfNvMTbbDMimqCqnUCuXr/Yb2vAxpMRszyzbplXpFSdUycDETT9tZpmsxsnkN6vNHFHKLW087Ov/6x2vk9z8Ds22dmWZyhI3Zd6zcymUcdl6C9H3/RhIHCZQbR/WKXw3ghTwDHk4g8aLBISb/jW1Td8dEey1mTV5TLGvVr4sHJDG+Ioc3tsVVRnOX8jkxzv/NOP0xK12CC9NdEqkcjspS/pw61qo0D5CgwQYLl+Zyvtk/Kqxc4QdKPSmL52u5r8i5/O3IWfkqbVPqgByDSU2Sh89hiyJusPsmU4Q4aQlX3Xhzl9Ely6rJJqLIoP4dhoQWmaW2V46olnzP3st7Xveu0YEOUbVszxXM/49eUIeHU6ICQnlT8VTGGqu2IZvf8Vimw==
    OPEN_WEATHER_TOKEN: AgC01EY5hGDznL97QR3BXaZkwdhjOKd45FXofU/QaJT1O5hy3OfVn8SoAdcJvsqdIz0R+TJyrMCGgwz9PZLwPA7p1yl379mbkzTTJ3kybSk0IslILrAU5tGLIa7AOFDeresiRAxdouJ2hXsYF0k1xjNk3Shdui8OUeeAzNeIBd/7AqpNaHHgESu7djkAFspIwXwofT647C7dJaWFP7594EWgZ/DIEsox1/+TQ4RiNG27QtnMv/DX7X2jlJGbQmEp1xvTy9P3LNqtD+l8B4TRq/MBqJF6ItI29yyhGBi5jN2xC7FHcg2jKzFcY8jFwdQL5IzoCd+Yl+d2xvTWy4NJKvKIAi4RVQOZtH/NOGBMgc6fSbG2FNA6nI6znfw/CnDOaSBcT1MZ7VyKIFzSBilYMgorms0owAWa95hfxYxwJVQojk8mK+HGnak61eo4/X8cu88qkU5cwfsXvJUKvazAkMVgBP8C9k2NtnwEvjM74qiC0Y9caVRyN+/UirQIVMh94cGNP/lhNRFeaWuWE1VFw5qvet+j0gObfEsM2R12uv0C7ugHy/S7SynOhImPkLbNe97znWL+2D8+cQC+lL0gQPXes8vRnMyAdYBJPj2hgnfX7QR0U5qoxCo/sXu9qct+BcABZGA44Nxisi9jcsldOIThFHY5bw+LcV4KDJ9VMi2KeUz8zqvZri5pmUu99K+jtv3wSsRQ32307Tcz6nl+BVJkI39Wan4Dmb5/y0KGRfLIQQ==
    PYTHONPATH: AgBqF4aFUceFfecZuYWeUF2KrX9KbK7aQiTNkXpq3MuROltj7Xq75ajbYYvW3RzdqVj22sIDSO+HJ1D5NzSYI7Fkp8lqA/wSKuZ5ez4B+w45qrHCMzVT91LMhKgVuuthYFoSqYrpsymNSSIQBt6LLh/3M2hsaPXXTUWWlXlNFXngIEJqHWCQMx/G2Z+m3bQsACjicDEHwQoIjI4amUacOZ2R6YHh1gAXfS5hYInetZetPqtfHTfgBmFFun3p3E7z92sMuNnXtaHx1n0RXXVYJhOYA8ryCHWrDcjxcykGRpR0gQVF1orLr9QMchwbtq6S0xB1TkXr+Fgo+sMb1T1+rhPA9G8QXCtalTJc7pw3FZvV5aEV2Gkpz6MJ+6I91LsSft4JIOq62F8sJkEHtQguURDzTbVAACHuD1K3pOznf52HELGocvZMWGN7fq3pOCMmR+6wwj8mpb03nDboooAV7KkPbP1Z3eo7cb+jIKXQLYampMW45uIIz7DuCC+Yt18AMQ5+D6AXJyqW/JopZllc3AGIquhOj6vqW4LCG7pMV6akLwJ3LO79hFcmrYYf4ltTaRAAp94QjOTDEvS1BBtfUnWoMwJuTNqD8NS2CvxpdauIKjH5B7t0yedAC/TxGEJdXmH91A2omcKYbefTui7iatGc3NS0epof1v6+VnebZeUJt58gnotVo1m+Z08WrPJ5S+vgwBY01kWzBg==
    REPO_NAME: AgABVBCymH/O0HBVkCM2990k7EbTh1mmJpKNN+iTcYeMJmG1hN9MP9heEysgX97kX7mjpMtrBhHZ5LqkTauhtrWJdiN3IrbtgVy26tjszg8XpPmF0GLSVK4c7nMYAewch+JiZR90qYWWVHnCiP/MNzQOfnfbpXag0H67VUPzKQj1n71JURr85EfAkzOzvlNeGEl/EmZADK/Ve+W115jcIfReDwKtR6KR4Na1Mbs71XQaVaz2Il/OuNfJ7tCT+bK6zEudCyAhxZXKUDaQywfE097SkRtHhDERlMV/whQWlct1g9oi5l2EBzA3guAbWdvhM2LtyOXD/Kiju9qhRbOHQKgn5wm9RJKIgQBVSr4aIogj74S73xhPcosBJ4a3xWkaL03sVgqTtHNoWE4j+US3BRSnzXQtAFppO1rRmCLHyr+NSzn2w01IMMHkdoNmHDoKsvQsmlhhLJ35sir+gyxi42I2E1+zfI2ex4uqtJnrJVt2llIVx8u38asnwMMQ0KjzCnt7U6e4LnoePm5+w3yp93+P+LxyHuvy4yMr14QXYSAcFjBULvN8NDrNoYtMWYtdaLWy7R00v9qkPEqcnrSdVmHsop2l3gWVFYuDNmyL4lr82h0uGZBE/bR90UFFh3FkvHbqYEOJegg62Mu8Hf0ZaEwGpM5H147MMiwEOUw33z0QwEP/mmfoyOShlJ1TeXgtbmMlAonyao4RJb/WyOrrYaVH3Hh7FO0=
    TZ: AgBsEGAQVsxjIKMoiAJ+gXusNOz4Wx90sMggJLEN0s7YV9SFAxmy8P00CqadwClq//zh6aRrgI37r1ZypgsKvJ8ixwsh/jua2ImGT8XZIq9ymoDbgulZ7LLuMCSp9g2k2aQoqsLjjSmCMERBFz+bZ63DmMQ4QIGb/81AsdufSMHlekjm4N2KUrSsCkjLWPj328LM3qklSmh9NFPS/ZayT+D4n+Lf99JKm1aTCI3F5dnctk+qQ0lvgblyJh5VvWLiVaHFunh0WAcawQB5aXG3KCUCFazzWY+sfdSdFrt3e4C/+QLI3aiq2qk7BVccvZHidPvp35NkzaLFp+KiENAaFCzmsO2MU7HBRlwnpcexTdIktHjcnyy/IgtRV0MAMTYSNVwVsXWcD71aV5qMkJPlpEbm0tzIrUo3WB9lcrWybIpcdCeBSEWSbM3FdVBMcSgos4vYKZBHBpxlbB/cJUJvNTTsHa+Gm4e7vvjm2eo5mO0b1gnEL2J9LP+oRAt3RCp1t45LM40APmAtnHtfVuAR1NiII1mYyDZzHp3QeQZxpPT4nWqSBtjUcQeyKyyvG0bt027BqVl7mkUfl4MoFuyFOWxkdypcSjuN2xC2ACTKpdE5OqGJZPzPTVGJwMFVP4EuqgwIlVQ0es90r0guxWSLf7TJX11Zc46bqIFKObzceue9tiCiFpK30VxEih32ik7UddktZlxiCqvUbx9aJYvc
    VOLUME_PATH: AgBU0R14RdS/R5Y6K+40qWfbYH3rgu+FrvjlGpjor8YudJsjqKtATqfskSAX9FgAUZJfqXaWyNIp74vzDwlD8Oj9m9uT4SEsSkuX4Ozcjouh2Jdm+jGiAf7PyWvhxeO0/z/vVASpYmjV4fYcCITcAZSkLMr7rk9baBBUca6yMSwoknY+liaiTP8kpB3QVFp7AWCuguQPijMZQcrZkTAovHBCMjTw73X7wSAJSnm0OsAxyhjFgpP/mkzspKZbzY8cGjI5VwZOL17aSRt/WjPUe0Bu7YxEm/CIpfCXjr416AOHSGqGWUZnK8b4akXjhAEWLUDWo0hk++uRT/0upNa5ZVLKhsUQb8fEk/lmdtI+BF5VpUazPDkJfEcofpa9aj0etQO7qP1PDA+iX06KfwWvYB0QNjv2BfkO7SKsYHlSMSYYy9n5ARJT9rgY2nZ/CmRfPBveVov/oF5iackxEXIUQssphgDIduHKN0h5b/YqTlokmpL/f2mnl+XkkWdgOW78jtPCMNZ3j0TjEJIUeBWTd/43+7yKbMNuDQ0dNcO6z44ZWwVRp8RNm2Fwu8rrdZX4k7Uk6mGjH5eUHfbfD34jTLBO+JorfJlDauSqqVp7tCNEuBDJLFLVWV58QLdZIA93MovVRzWvmTOtPO6Ltv92vFhG2+YJ9Ofzm5o1jTvRM8xpu0VSGZSKW306R8pepV29MjiS4QuBwVF4lQ==
  template:
    metadata:
      creationTimestamp: null
      name: flask-secret
      namespace: aqra
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secret
  namespace: aqra
spec:
  encryptedData:
    MONDODB_LOG_DIR: AgAyLMifITpos3t2MLGIF3NA0vQ4PXo+YG+7qOEjr7l+VCzpYgVxXN0jad9NQLe67G+3yXW9o4+YhDhe415lm0dkuF0CBCbD5k3wk59zjsD9R1FY7zIshz+Y1XBvz/e5YKjVcBry4XgGl2gUBpwQ/OjoKGNSEFzWk/y+dZZAodG05ZH7hFEEvfv+MXAdNalsbD8QwxE/62zmhHbHHkqiaQM5NJt1GXn43FjiugtEqEnAKWYmpu5ErJk78zKYmaTPqACPk1G4mRffKLlM91Wn0p5cPjaFgEr03xkeQnWtdhIj2Ruam1prfI7+zY58oo3O11f10NJVRHwTRTre7/RbxonIoyuLKcPtHmTQkiOi/Ha9NcEYDCEst8+Mw0EmHTS2qDzRuJX7m0vp+etdJjIZe0KdJZrw4H+z1QsiL574vw+eMiYILaUWi5PI3y3idi4D6kkR11uG1ddNix+0XcqH6fu1NP+QJiSx4tQUT4nhGPlx9qW/fdLhV5rz3Q6SwmGuDWcGYkLrmF8OrCpemdsc/brerni2pihhwAVXjBy5QEVp9drvFXDsltma/yHqg1WrFgfb2jE4xaTL8ya0hcYCO0aRsU+QqUHbkyKmTrG708dWZFiUkDPM7Bs7l28aYTbJiXdN1E5nf9Ex6WZDMTNAkQbyU9aJCaWRz3ECTyB3G6zRcWUGGHI2e5eS5JupGiePDxjA+eUrlVXB6mo=
    MONGO_INITDB_DATABASE: AgDBhqHZDq9AsnbLSejAuxcg3Y3fGw7sZCZI2Nvczh6QPrVygtEvo+pdDpWCY8dYimwBnnPQgV2jYywB4zIVLhJVD8UqEijqUbgLTUXWHhpUyy/5ZNeF0bKJ4iLTllt53TZsTuxThX6yNLUku7eL7BqXwK0XTlbz1ihIYb50F055PrjFtob7dCy3m8SWy2GR+ffxhDt1+Bx3vN0sORcUNPGG04Es0OONF7g0CqWzyjRFTMLhs67BiXb0XniU1E2FxT0SwjGFwJUtWZtNQmN0TuXNIuOsw/4y9uhnWXUsHw4B5iVNxpmExuGBYc8y5LJwZZfptbaEetYZg6BZRg/d5d3Q5/oqACW8Xm5z7suHVOF+PVtichNOiRCrxv/NubkHJoOjFys6Sen54/2oosgKiFo/QucYGwnwJ5H0C3OxYh9+SqmlxW1zfhpbIfn3SkM17bUIaTi25x9QVCAn0mefKhcsApHcZTw3p3pNJ9k8BpJwZsM4xr7tijw8liLQL/pfFaEqhZg/KBz25KB7lRpbuHlDFebKxvOe6Zc6ajX8Vw3JV6Z8aBTmDiWKQ6zn2kA5kvzBKxiJbcI48d2Oyez9ePBWhx9BRFXzCet8vbw8TFWeEz03hx4G6tIluEqe1Dk5UK7lD+yJgtg3Sph1qHa57cPcnxQoAiBjII/lADogf3341OPLXQyxgICLfewXzlpG4c7mjoW1NUduYMfo0g==
    MONGO_INITDB_ROOT_PASSWORD: AgBRbUwZPzxwCuMCjPOvT7PgTjsHDNirmF4pkF9+3ptWcegZI2INKXTv+4ol/IdbcuHUSTegI8LPM/gjm57m5WJts2gPh9oy4R2CRHA5h3nJkaiPYgClhU5d2YmcKG2S+TH86dz6SazTpzKr0zU6Tg7L8QZ8ZzLzj3duB9zbFd/fvWb20oknAjbNeDjhgI8SARZp5keuExZ2XzXzXR0Jmte/dxX8Mdpm85DpsztzNu16UPITLDDyTWnApniLRQ808nB1cghx6NkHMTljGcF2pV2Ufrez3gHLv+o91gF3w6CdwYnz19McLMMFU+WR4f5JM00/VxFJj6wVo43U6pbXKi29mqLGzRBF3perHzwSe3dBjyexNB06335avS+nudCJ+KcqILbXDOWZH45A7lKqMdJxjx6Q/s85CF31xHJAYJPxx15huyeJAUrvrKgt3toZFUSfqQnZFT8RF+hht00PU8Sb5Hqrf10x1M6G/lc/WPLq/3IJT4CVzaoMOXiiEwm7A8uVQw2NLkC1qDjmCKHjJen/2J+G5dEF3R3m0Mmh1YK9u2XbDAMP1SyXc3+iAYXqgFOycpZMdrT6dhsX9AM3T3ObGzwV1aYajsuvkT36fZUF+KXhhuSBb6lb8t39IA0XT5xJULv66uMIrzMjCUSAujV2wc8hEoLxX9T4cRyzw5kWm7RMwom7fKYGF/V/wzVfduoAzToBziiQb8u84CAaD2U=
    MONGO_INITDB_ROOT_USERNAME: AgApczMsWTRVXlGVn8MEQEQmyCJHmR20bcctAGVLPZPLUQ0Abky66g1DX7joESG2OUR58DI4t+WYD4CkMCK509Vyz7SZYpfgB38a8CraEJFX8LUuuI2/T0qzQrW4gtd0Z1MY2BhSDWLjUdrIZtuzfgO1sBp9E0w82P78j0XUxTmdvkXPaW7wYp55u6k3UCifl5V6zsTWOrOm8y4OJZN1ms1fPDyDkSvv/9eL8GpZGD3HeXpg/qWYKwQm+gFo7CEkD5pMVEWsc15n7gIio2u2DipTHTsI5R+KILWkeOHxYok9PFIwvqbqNcFsV4RDl2fEGQ3YyBygIQ9nyoopZe2624+RqchOyo9qabUrp9rK1Kc6v9RidXXTSDghC7KAoOO2xY9DkLMUsAftsNSCfZBeBY4jpZzvpG87kLdYayCP6hkEyrwVOV1bg2SYE9Ztm1TrcZyM/UM1uAGczPr4umVvy+987TVvjOlg8P+7kXAKhUVm26f58vhoTdF026fp9hnqNmrUoRnLeJZrTvQWyC3ehw5G5xOGnvwFYgLk7qWQJHbM/J2OOqkg3/9hNGFABjbVXDDBT2ymkNADkVOrOOG4FUuJ5yIz8/yb5Nb9xKKhalsK3Ud2FCmoftQPUDFdBxQvfy1ExGJTmEpzkFpmeIkHzn1Ek4RyziCZ9TcROWruzUZi5TwpQEubb+vj8FsTJPZ7b/WOzQMCydC+/lEsbw==
    MONGODB_DATA_DIR: AgAa9xA7grnMomiyYZG1wxQFcrsUqvV+LoPUSsp6v2TZvcLfzIQnsDGBkhyACKL7vetNtRexUiq6eup7QBH1b+AnTRegfI9ZZumTSeVERnSQIVbRcjDGd08MzRqF6G4qYvEnurX8wAihUNIeFvaC+G+EEwvl/vojSytRSeNU6QORWo6IMVKZyUtahRw5qacw0ntPpk3ANr9kDMBKqVugNMCaEcFz0r14WQ4/oUa1B5BS7N4QBun8624xoG4wmuSTWj7cwK0LH0rwSnVj2vG1jnNhT3oHC/f4IIZJsV5hIR94KnlUbJSl93Gmh7x8XJSKt80qhQGwqUWvJw9wrK7H+UbMipTe2UHR3KlXN51QCtf8H/DYrwCN6bEvOQ1UaqS+Xe98mRSvoE5bzLcE5X+3ZEPPEtxcJpX7afK33PI3NKpZugvkZ4SL0ecTMrSmiVEyEtUZkZ0FGCt+qj1H8UD1YVTEVvftKNgNHLYimq1anbpHNOEkNWarZkoRjm6/IGdTQ/Zm07xWB7BXdAyxDrYVS718RyBJKEcv93yc/4l2SxiQ3gOcu9Dp1Py7akVZNHsyfySdeYokfM6KFm36gwdDIMSJEBNk2E1o4DmTRuqdfGL9MBsPRVg9uXoh0tD/0Y/istSguUQdVMnJrMphFbB7TiI6Ss5RwmTndGdR4h8qZ9TOHTqcnZKiOFFvMrcUzhDjLnJG+TeCizczfg==
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: aqra
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: atrenchevski@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: atrenchevski@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: flask-ingress
  namespace: aqra
spec:
  ingressClassName: nginx
  rules:
    - host: aqra.feit.ukim.edu.mk
      http:
        paths:
          - backend:
              service:
                name: flask
                port:
                  number: 80
            path: /api
            pathType: Prefix
  tls:
    - hosts:
        - aqra.feit.ukim.edu.mk
      secretName: aqra-tls
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: aqra-network
  namespace: aqra
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/aqra-network: "true"
  podSelector:
    matchLabels:
      io.kompose.network/aqra-network: "true"