apiVersion: v1
kind: Namespace
metadata:
  name: aqra
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-sa
  namespace: aqra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronjob-cert-delete
rules:
  - apiGroups:
      - ''
      - cert-manager.io
    resources:
      - certificates
      - secrets
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cronjob-crb
roleRef:
  apiGroup: ''
  kind: ClusterRole
  name: cronjob-cert-delete
subjects:
  - kind: ServiceAccount
    name: cronjob-sa
    namespace: aqra
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mongo
  name: mongo
  namespace: aqra
spec:
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: flaskdata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: mongodata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: flaskdata-pvc
  name: flaskdata-pvc
  namespace: aqra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mongodata-pvc
  name: mongodata-pvc
  namespace: aqra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mongo
  name: mongo
  namespace: aqra
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/network: 'true'
        io.kompose.service: mongo
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: mongo-secret
          image: aqra_mongo
          imagePullPolicy: Never
          livenessProbe:
            failureThreshold: 1
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - db.adminCommand('ping')
            initialDelaySeconds: 60
            periodSeconds: 300
            timeoutSeconds: 60
          name: mongo
          ports:
            - containerPort: 27017
          resources: { }
          volumeMounts:
            - mountPath: /data/db
              name: mongodata
      serviceAccountName: ''
      volumes:
        - name: mongodata
          persistentVolumeClaim:
            claimName: mongodata-pvc
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
  namespace: aqra
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - kubectl delete certificate aqra-tls -n aqra && kubectl delete secret aqra-tls -n aqra
              image: bitnami/kubectl:latest
              name: cronjob
          restartPolicy: OnFailure
          serviceAccountName: cronjob-sa
  schedule: 0 0 1 */2 *
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: flask-secret
  namespace: aqra
spec:
  encryptedData:
    APP_ENV: AgBC55aCST85MgMrPig7WWKxjoodQlzvN4dtkA1xcoYj5bDS0d4HW9BwAtxniefLMMpN2NbOR7UiIkxuoi44bQiXk9vOroRt14dHm5Hhpo6XcYuLgVnhmWgag7sIfftLgr8ozLCstnUxW1v8O1UmLjAcAYZcvONVu6dmJvb4+2njlYI1A7xKRNjvt0G6dz49plqvnRn700wuaz3h1iD7LAUWlz/9mpen0JYsMQr90aWLOE3pyudxrAtIVHQZsbuZ4Lmzl5qfljqcMfb0Fn4R4xcQLrPPALdGzGTqayTDiXIOqny1a8JOOJfQ3YM0W6hwGhAXJ4nlfzMQhrAIxVYXJPWRVVxuZh1VESHaMgwKHijBnlXMlwnIIoJykeulL1pxBTLEoRNRo7Y81rUH25BhnfcdynLb3c+JPMuzKSrBhDh+4NnJ9NrnGD4wFlX4lgafhXdldiGJAHMQxyhVMNrTUnKrUWwqxP10SkjRibKjynFBLhmrUSksJIU7KKVQWcnGqfFc804kzdAHASi32VbZsACK700c7PogIEmCSPUGUtChWqAb6z3eq+4vQGANRcl4jSTJ5Ga+VzeNhWbxJaE7gb/IYcmHdYVUvumXLzbXp67e0fD6jojXBYbNtO+cnMYW8qqSLF35JbA7+W5Qpcw9PuptZ3XlJkuN7B3IANi0k8FeaFiLE8HnEhbElGWnd8TEqVZuiTyqEkMwJG+v
    GITHUB_TOKEN: AgA0onWnXGknvDmOgRAb3Ag8TZd6rUyRUw3KGVUn8s2YBSpl+08vlgWr0tadyo0NAnERw8YsH5S0zM6t5kl1AxzZIrKrVPn/rkYAoXBxnxt4iiEfqHmNMZ/k0QBrOPzoqPlbNPl1CqHAxFOvINIWpUcQfo5zUo5aTTkhxyzMtktOiVH8mOmFEOD2g1dUKLFHCcfOfeqgP/QpNw5a2V0WapT6rJS1g/aLLlD5WZglqdH/B/xdafJTMtJDDW0w6rzn9LkcD9QAPQJ+pkII7RzYW49EH0kKTIJoQecmhH2PKRxCsKCMGI0dCy1s1oBRjsytjO5G9abA5VzpnMVJDJoRfkpYS6hcA61g00eQTViseO6TQ6Y5aq7MxI4GnxZOtXoUGd53zqXFy4WwGR507Qp6EAUEjdwl3tHJs0Zr3ce/tGbFyDHFi4M5j5WLfQDemO/Qw8IGHqfMOjYYp2cvOUF3Dde0KeewKcFW4661uRFjBEf9tW47cc0/GdZGz8xabLnlYet0WoYzNXAnt8Gx4ROkcHTjuwIDoEjUyAnfrk/z56181gNJ/p/Z74ukHz7+5Sx34k3D89VDrRMP9VjWdIdoq7zC8ic6pbpkFbKuRFzvgI/YUYX2m5ip0CdWGUDtb39esL9pB6wxrXuZ9q9a9G5ybj2fYKWZRQD35+j4cunhbfCfIsBIEYx4rx3I1Cx9GoiDCq03ALibSzkfnAXks+kU0llRjddVXClSjiEkqS2hKwe2qRsqUjB4kK9G
    MONGO_DATABASE: AgDoIidKZAyi7DcVP5ND8aJKb+uHaVDylDToyJ0xL+L5agQdyENDae+E3QLwv+hN4xnucfyF4mc5Iqg8RSrkLDSLVx0GoHtXodYLmtz/jM/EAfyplFGi+cbCKrPIjFO4WmzK5nrepguS27RSJjn9lZg8zR+wgyNIeHIsMNbn9n9cpBbhExCGkg+W40BWtRuSI6Fs6kJpSSTRQAdotxClDlPosIH5o174v9uXGBIyiwiUx1L9TE5uLwscTebxjcY283iQ1vLDj0t1QW+2x2AMMNw/WsUEvwL2okcZrA7PuVBE+js2wGl06SwRBkWfhZVCF29tOh14K+kpBBcVjC4/3AIyNRpaUxNerE7PS6eMXb7NsEItPZW+2GvN8UIkgduzBY7MqMEL/wOEAd0c6H4BhYdJwM12YIivE5YsZpH52jSWinpO7gFoCO4O4+wb5icDgsgSQy+JkY0C6sUW9kEovxtqd6eFYgJtyME+n39jdx3kJl1kY1tbjVNTYOwg4ktFnZ1y341ZZrkqhuAHxAs1vp+CR8QyDRswMHqLNQGIUX/h9JdXKFFkFmzioWfeQfPqiSBoqmZwesMb8QBIcQOPmH6pTQWF5p9To4XJGUQW91saRnWLn0GDsJmEKSlCeLcrve5mCZ2MU0Kxf6mQcd8J7eretw3Q+2ySitCYBlnKY7zYGB/EbYH9rF6WokHNpPyXt13pSVkjGT1W5dyTjQ==
    MONGO_PASSWORD: AgDmWcRdL2e9xde5dEYWTCJv8dqEFqIykPeM8td1VkHjUY6iukHKZgK17SoJr+kKoBBFGzUaGCLSRO+m9EoZtSiTR6wMP2NC2MFWvuoDoBLbwzDBYZUIOFcXd8PK+9t6GBSdW78wto4kvN3lIU+POmiXAkzKsY82wXzrhit65zwwP1Tf8scpGyzgL5/pOMn8SlcdoL7okKvbklczVwP7xkW3/wgLTFTh1AxytQAdUkd5gkq6zL9HeKO3j4Ou9Pq1WgzGwa8oyka1FP6zdna5JF6fbcDQwUxNmG/lOr2XBR2WVfY5dXg4AV5LKSBlFQanPhDpYmAynkMLRrKBGbt+Qemx/+3s0fmheRoE6pZbsw3hW6pA77+sllCzLBEGk4U4cWiGVdpeFrgFR+KuDHWH3JKh66tOGJ48MASPd1sRkPBTuQCR9la1nPyvQv4tjNCofz3xPAfyEDVf0m/BHmrXfWimU2DW5ffflXGtUxz0DNEsHhxGcYt8fH3lpoRcI5LNduC7si4e54U5jAyNaeY3W5s0yWNTASDTRJ7KQaG9xaqncIiYFM/EnDvDPgpJpGWZR/U9WR6aW07HFjTrVU42iZk6NL4/amtPz8LfdI3GcZrgJNTO+LCFCJDCbZl2NROh05aAUt8Cqvyg+VozdQd4gkHsmFLSkAMuXizlNy8O0jCFM327A06xgqy6syjYduDZgeJ8GLvignx++fzbSh/4r/w5no/z+yoiRJrDSw==
    MONGO_USERNAME: AgCrgqxl2jQOygjwq1CyOZOXpjiPrD5XB6KFOh4UaKLejH0AAij35GkFUCMTIIN+Vu9tyoFOgbljbGCGmkhDd7E2N0pVYyuVoiZUBEdpfkTchV+36zUsJ4spqgd3IjDztDhYXszmtHYG6LaC7sIFPzhEazH2rDGAkFyiVHP6mwUDm0orTfIMFiCw2beTXLBI56i+kgmXXIZNp/LTy+DJ8AyewLNY2kSd17fLxiC80VaZnFk7P+FZFgtSDqPRf1jlDZIjOrrG5kK7GntiYT05jkHpWQRENXGLNvtV/0/2cAD3ehSSLwi2XQnl42eJypxNRWwrWIfq34l61JW3XihV6sTqfM5F04FJblJhULjOLVtBm8w9OYIZDuqwftl6diJxzoWOiHBTRgld/zsRFAryyQoeVheiiiUrSvfBaQTjgFDx4Jwueo3JDSaHFzj/nv0SJDjqsZFrixxCKpi9Ha8vOQ31/1g2Hp+NLbnPo7Gn4YliPXE60TTFzgk/q/QapYNEwpXZ8/8X657rrBzzhklkJqCJbN4npPuc5Zh7J+luTxs+n6W6dnZPK/TEqz/Qu+gigNAFHry3IesEL8W9WrcwHoWV0W5b7vYuMjfRgR+Lhe7XekNovUZdgfY6MC5nsCIlrxeDTmQHkgEc/6g+ak7iidkd5AMm/4XV3wjs4zYid62H12yB5g3luV8/evHUbwDs7TwSsT/4pcYU4Yz++g==
    MONGODB_CONNECTION: AgAJlf6wFeezafY9IUN1TR2ouTazTn6aurDJxLcvRsW1t1nH44QA/ZV8BxxeueCyhZyKPZfUKFbmlhoohQj1LLpZRwUQx+UsgWjNjowJ5toAGn1FsyqeKOjoUJRHnLRUz0vSVijkNOKY3w+u2KoWv5iWYdv60hn9dEWja+/1mJSmKk2sG12awYvLF4GO6aXFKiv4+ZCt+QOiT2ZnKN2C5d27j2ca779iN8coEL+Ma+AfuHWtru/gYW5m6dTlYs8ihjCBRjS9snyNbRab0XDDgt4d1eKz6P/yawDRPAQl6jqc7q1TpxApDolK63PlJLcMv+Xs4UGleg8TU2UKaKfkt3FDSXjIzqey5QYOT4i5MedvmyUnA4s0H+/nE8bEqVV0NsCK6ZWD5BXx4uucpWitB/scCR3N5daOpOrpbLWtfvqOydTrNKpnvUxzGaFjs41BQUWY8WYW0z1cazVwMi4pOmoGy+ajQHj4VjHEFkPgs+xKp22OjgGgd+UDDq0NGaN95cmnYf46nwbB6VnqTMDECKX0NUmoz+F3T525SoSyz4LPTzZqTU7D8M+VvdWwa9eajBW7Jc7W4WtKPS0KAvHqHh4SxOJtI5BWuCUfvx++z77R70Q7zJrSSzhiqL1aBJj71ZJZ1wNGdh6Jzx71BJN/FGZ0o8IhV0F59YfmgYMpSqevlvZ6MvoKTx74PKfld2YpHVjRqqprNBw4
    MONGODB_HOSTNAME: AgA7DOBVkXmeTc/Hn/k6XIWEfwDgT0rSfiVftMVTm43t0ChS5xltbqqzVtLUht237uVas+qJiUFuRchI0UuIUbY2RL0d9VinxxNGaqN9LERn3EyNVASOSMSb4FqeOlXkywuoyB02OPoVHl3K9Vm0udMV4AH5qXTiYlcAla8jvPSrhhK6xI5CjqLmW1UFM/pelGySYZTbNYnwYZ/OoWIcKLoMOf7eAUNHKvcxwtREpTNOaaNEDgwRqEaPKinM9hsHAYfAOWRZ+UpCXBX7WQ9ZCsqz5+ytg9TCG2TXsmNyns1IlDgBUTrd4NnIf+hMycmnSue4xuCH36gx3XKoNTTzrXNBzkUQ1v2wmAJjYbK+qCwR8dhjt8UAPGzCl805scfZe6fPw8glEFFcqxy8/p7//WFB+py8UFCzNztZhZ+0STRQOAKCIonQ3vE6B/y/PdK+gAM9W1rw5YjJ1soDeceJynEdUH2IPlwcYzGMFX56ap+ryBJ0e8lLqW9f/f+Ko0kSXNGiZXhdUZMQ6YXNWuqCiWc7DN2CtLmbDhKFbcoUFvLPwnNz3SSkPgmkFWjpV1Ooxn9eCRWQ9IeozYhHu/b9ta4bKSYAK6SAlQIeHwHB30GsyogpDHOVC5ZE4s13/frx3kbT9MTDExoz8oVUvafJS20WUqJ81Ydo6oKunmDy20b7i0zi95hE2a9ZdlvqVeJOf9gjZYJ/zgNRjn/U7A==
    OPEN_WEATHER_TOKEN: AgA5WV565s9GhdbglDt+yKWpFHnc6lA+wFIdjqQ1nWEfAsn4iwTzqBVQ+YooDyNo+3m5zagudb3PlvgXPqQgfEETyuGIK6L+VOPxPXoAQJ5Wct3hA9dySw6JyP5GAVV4NuiGzteJl8VhcWocuEpxJeknGUacprqZSaYxqAdY+M3M8j9ciIQVi29bpe8Ut2E//9JS0aBAPKUlE0EGTWyvxKShkdXGT3V3IQ4Nz55uKq7Q8odaKyR27uWbfhHKobf3Bp4eMSrvhcQ25Sc5XPS/PRXd5u4PiPMesmMXNzL973qG0LwNKSs8WJAtXBG1G0kQPHcukgRkaqV0AdEjsbyiNIEawe7NgX7K02usmO47P/cpZBhFm72WOkY8osziK4vBhpVMteTAJyNP38/KyI51KmIssBPP0qnXHgMHSRToazWBExzWC8nmzemU1MXI9ffofj3mFjUr0BsQhi59P1srMJ88fdb94FK6EBApxTPuKzzoHaBDT/8yRcp0XtDg7oEZ2avncZHESYk2QjAq72teE7R8gC7fDQp+Cdp2/6iAPxrkUhUYSoq5eTnBsyGTChK7p+7htfPONRyb8befwVax16Voep5tSgpdMIf7odDAKDrrWlYpfYYaWb0JM1HGr0HYL88pbz5bH0+381CWNVvAg3JGUGqOHKo601+byBAmCS6AihLN580jLEF8WaZ78V82k590ICiBc2FUwLXn4wkU8ysBPbjNZkdAz6+UTRhNTJp27g==
    PYTHONPATH: AgCCz+/WyBMFLP29HJdnNBc2JTlcs0zQ+6MYLXYehjCKyGOqCFS4jV80KFCcceSYREPkTsuFaDfMDR9BuIlkorvnd43AC7vQC4Z87zCmieHJYwlaV5bmYtvFjQEy7mhyQ/sylwN/ysqAB84b+N3KpCvGm9mCVDgudpsYqp0leJ0CMHoTwc6oEVWZf+mOkGZPxqMupgxZ/rCwOgxzpZ5wGrUZgLoM4Y4NXHKzqpI/dz2pRCRBAPoKqC8z4FLNhJNemT/0L/cgIpFprqIYmP/LRcfmBPWlvG8Zp52mSzK4hqy4tq9brXIgX1cG1bF+46IeSUrtMUNQQFj08QukGp22jss7LqcA2UDN7rormHeWGyikbU8trYeNZwyQW/Wsz4Ilw51kceJNCFNJsWM7ezcsFO1jj17rfyvVzopEavSqDk/q4LgGp2Mw+7B66AUxVZSK8ee/LNbKhDJAEq3Y8u9QJuyT2sScKN7dPcrAC5v0bL0vhXGnfOAHOqKmKD2Wq1PGSdq+nOV3m35hosJfDcQpBE9wU/VAHkASZEqYWOAVB2Ca6F9kuX3LbkmasdzGqaFl+trIlh772SVTyXTVbh1ihomM3Mocfi/wVweeA+aljbOOzzdeCvfIfMCywjK7UHlUs6t37bD5A5hbsGNXObm/KomLeh2mw+rYsJY9XUpKudsK/7SAusp1NEdSEWdmOShKDNoohlhA
    REPO_NAME: AgDdh2zwrlchg1VdrZwDl7TaRlx563MkVO/eY1eN0ZXSEUjhlnzxm+wGqSyZQzZyR0CpxUZgk83F2YCKEhQzEMPVDyTfMVBxMPkXyWo/VyJXrzqdgqTFhNAxv5Kd2FYFLs1UMIDgprhrk47nNPWxepO2Hr30Ea1UOUPhbKJfIIcJxu8/6iaic7pZItbfPyJwg+iNzfF2Q/+QZz6MG3rUy88jUyYnRHQZkrB99Vmilta6o63Jr1/Th94Rc0+frsYylmbyWW8PMyI/FRaCPem6N9j51UYLJnK88CKIngWO0KKJtV7Xj09JVM0YyBRDAN2Jzm7/JKa55bKqd0zyJzCvgsUSVpZMCUiGrgnSfPmph1nF4llosgtMW4OfxJY2InmV4DTzrPOOrN2YvFTR2TIrITCbl6H6Gw6Fye/h6XfjuETjC6Q7/+RkzNIfmuqTjzn47hT4mLYFi7RBKMtYs063YCz1ZDCEproCSTuVuP+UIpSSZlRs9s20ca6Kg7brfsAoNq5zxmIuDLtEp+8n/x/vsTYrALp0kyy3qaOZagHzsOmssLllZSJLzD408fk4PNdiCAfc3P0rgUcGD2+yWDfjZOmK1DKoHZ394wo75vyFT9GOcBhbPTjMF579ZOqK1jzfYCISb0ajGTRvhJJ4HykvWEJbWteoctfVVFHq4GOcJluFOkCsIg/71H1YO6sL6xbpfzT6sHeQGwfMcWA+SWsOYUtDSOghCZU=
    VOLUME_PATH: AgAI1n6ByYA3V3/ypaURnvHXz1N8tQBs2bCErYgKj319SF3R9upr2R5KyXIwq1PPCGvSP8m9UW9pV0JSZJFGMFkurPgemiUNIJn7PoqcNdTx1DC68ql7gLctYRZlI7KhQo1ZaCcngaRTLnKeSPCeDy1SfS2K2zGcuLy/5ApAsiuR9PYtQsVeThYnPNBeHHBOEsDld//4rvH+icOisKQ0KFCPtAFMFbbL+MotpmyWjzfqK6UAUyUvw6kN7+qgsDqqWExibl3siBOAE5LQjLCQ/YndaWX2RKFCafGdW2ppyNL4Lh4F86DqvyulV3PuH63rXElQc9XezS77qrNd05jIoaCIhEEMMBRXl8+VDMWGib4tuMID0XEG79XOIqtY4eItyMaYvqa/fosCbiUYpwspkjxzEgb5wDoHE8qQB5MEs4Kn+3A3KAJh/AJqPaUWI/IDf/O12QrBFTASI+veQB79c86Nn8BGUfJp1TMyUGEBrfumVD3JnzLi0QOhAmUGfVB38Hxlhx8TGp2SmbNFnjbfYqFzWl02Lnccrsh6v8Pme9otR9ugxo7VbzWBWPSWaHlWfBKweSrc4uM4cFNOyOSzqovK+o4SN41i2dOlG+crYMjbNJiJLJZN/RKUc0Nbw5yRnlMRIF75pWs7Sky9qe7xoYRsN/5yb04cj9s4bjBsDuyEM+kzbcefvXzdw30lIJvBZ/QdwVeepwn6OQ==
  template:
    metadata:
      creationTimestamp: null
      name: flask-secret
      namespace: aqra
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secret
  namespace: aqra
spec:
  encryptedData:
    MONDODB_LOG_DIR: AgBdonU9vCOdmBjypfIMBj849IXzab+xQYZoSdHMOVqEyH5bvDGnpO16a4JHIommSVoLf5snP6NCO2Fg4+LrqkAokiAhLMlGHCtardaDF1FLUItfWAJS8Wvyn0d+kV1n8lzta/9+e05A62y8PgLfxySFjwxkN1RKBoWYpo4y0q6FY4RMQ2o4v3RSUYtcxK6bDHrGSEUy+yOwNNR9kNnFoS70+La4lCUTbH0Hjps9qRxe/f9qtNNWaGOV+U86GnZmkKNS4fRUsXo+xyL3PsGTjci4dTTEc/jsUtd7uUzbPP5aIijEWBsPt/HiFPEZkntIBb5TzqClkhLpwkg6y5VGY3aWSCm7eGhCE3bpPU68e32vQmP5IYRVic2w5EAxWNyrMWC5rtF/vKLpxt4KPHolDJwSAeKi+x/kIilfFgHqNSvxGJ46pxQ9GEf1FY/Btidx/721wGwyH/L4T7Xu7PLfAEGFWAl3+qcoG093/c4ZKgSwYvG2VCU1w4qtlfF06aEmd7GC8bmskIjmILA36KB1VRMc4AnJ82KHW7EqxNVsw4cA53NcjfHMNph1UkmYKySA0x9Q4csWBGgjP75dGwPV9puuR48ODT9SdTy7CWxQEH8Njp1/pfp+jtDWqECKteqhhbG2RWA6EPGis2IXt8DuLMrJEJgRGU4WXbEBhbS3X/DhS4QSjHe6LSktmuxb5gEB/Un7H90yIRIFhgE=
    MONGO_INITDB_DATABASE: AgA+eSlzsDFdxm4+iDSr5KXSfq21zJ5AODdAw/3uH3UY4k+FJcjw1GzgzD16CMC9HP5HLL39RAspe4mWVevbMwbG7A/CTGOVtMWRYF/R5kXDpYcsaXDJamfodV5WiVEDtL6e5z3w/kBDi33UGo/Y1TneirCGUGmdyL8hrTcwCpSGzLnVZpeP+3ZxVt/uSica8uxgdfkGjA48UH8JeNAPhIboLQ5m43xxrY0jwQJ1gyFKu7tBJU6LyL1Fy60MLnR19YnnEFVsYuoSeCBPSTsWpT4NL9bCiFx41G1VINDVUGmLWwer6YRtdkpQuJUblWBueC6Cpy7/YTYg5e6+L9Qq0iqQ4sTvHcXqeySCitwgYmYiczst56/d07JDaFu1N/VkmfxHJ4qFA9mr/h+dk686g3hIauz5PHaqswWOtg6OR87dNvhTR10jrt+3UvjVQdltkxsbU1uwCKePPW5M9aDfNVYzdZ9ajV3vpMASGcilnBtaEIyCAuP24jruA0W2yVKQxcd/3EBJkrJrG9XDcvWhkWO9g8T3pzQsaHWc2xid1cmdeXOZJrYLj2lYl4HO92DqFpEmpxrIZzJzOEI5oU+WnHO8wV7CXh47/l6ef+fx2r4iSilNvaFz+lZCwx06oHCpw4VQyCTJBk2+MzG1iZqwpDn2Rtr4xu2zuI46dhgX5x6RgIE3lNSrOMYhSd3LFATWHQI5H9Pn8wSFu1iC0w==
    MONGO_INITDB_ROOT_PASSWORD: AgBqcRiYQrkmwpQKQy43mkINcHBWcMKmULnbEhS6YmEX+UM0GMzM64dIhm+PdI/X4h/aNqq4l/TnM7xj5pw7C/aXSfjUJuaT7j0eIN53hTHcj8kiLIZAshrvtr7N1/RAXhvyPwQtfwnMcLiPd/EO6J4Md8sRK2dHfVFbjN5B4tlgd75brWyJg43z9ysIenh4kKCnMaxqLzSYSuH8+n4mE3btdCPtMfAfDwrVt09h9IAzHS2ddtmrybN4DzU+kDvoOFI6zcdLGEu74iN6tEG6KOG+XeyGGslt7pJVY/6b0ti+XPEV2VdNfDCk9Y75Xab8JvX1fYzx5v25h3YErJ57AdKXbcE3/b/47iaXOQYrmlRJW9+vvGkRvGWEsUsoiSI/DkdfrFSyUQ/w5RKKL4QiWc5zI9KwBrpa8DQGopjsZiYsuULzTMP6fLJdsI1Sk7ka+Rhsz0Yk/o0Bb1BE9g5Em95LOEwxA3lmt8ztyWkvgSdxksR84GWv+uOriuZYA9z7bWdCdM74jdGLmWCOGYkXFg4kiauzwynB521133MNvy3NTNjGhyjb/p34T9l+QRDLZkc7m/myfXPDe/oGHlrBBiuJLQg/tgmnAAejCXWet5GFnXosydsTf3SABmS3RvCVOHNc0R7rqcYu+9adJnrdcLPxzl8nLqW/5xImMlLKOfObM5Tu/JSqoNWf1Qes7vSO/Tfwt+xv/2Q5cZIcLuaEKzNlsxWJZWk/jfYYjQ==
    MONGO_INITDB_ROOT_USERNAME: AgCmZLfjs7afEAhDzy7JT3t4HAnXKQu1myO7FBpTHp6kyGvglUC5N5iXZZOgt5gcQFOVWBne0oqNzVQF4X9GVEvFj7avQq8VbUgK5MBGC7R4zTuLQ4XOsvzcToNAghmkUrfN8/16x3VPM7subiRiWVZ64mxRo2wEh9iTOQuKi1qRadp+ynjkWHmZVPx/2k0bKkMr34E7kNk6gt/7okgmYyaAhLfAjXNB2J7DPgAwDTH9E42ZjuHyg7Z+pZkPWJ0PluU+0Qiad8XcQllc0OL8ONW2Eri1z0ZPnAH5XhT+bcErvEbiiCEf5xHBrZ92yv/iH8Bdb1lBFgdKw5y8/QUctF9ZI/nXIVi+0RqVpGorAUUrnfotWLja3xcOm6y3e0XhvhoRKsrkpGxqCZEEoh7wOls5o6m3vNTOi3U15QSY94GD0c7DbA/zKLoTX5GgzYwVf49pdG3AKZlgenxZN30jAniy4JGG8hW21RXxpqKqtLUovhKGUG6N7dJ5Ag5vhixIwan4MZfGhKx5AFxbKa+Jjq4Rlpj4mrWYZ+VlyMXgKw4Yio9BlFIeVAJRjZMEixwIrfLnkV9WyKqeJ7bQEp84kXX17FhILvPeSY8oJd+ca9oGYWkpmX9WSiYfIvUN1StOLxMGXGP6QDh/n1l65fb4HyO4Caohh77KBBKxiW/DKvclMSYfkl6yJHuR6TYFWfFNh8QUAFqFIMDufixWDw==
    MONGODB_DATA_DIR: AgCH4X5HSHrmDsUe1ZfuSyPXAmKDnH4yUesdf4FPdMl7TfizmSlXr1CZeWsM5s0rmGrarW69YSQXjJRWT0EAJvcBgXJwlttKsQBT7gqhzi0vDJCeHB3GxbbRNhdKTPd/z9YiX422tmc6etV4dJrnxSGJh9TfOAJ/ouuDRpfhTd3TskAJpgndhqYEbFMid6geBnPzLnmzZpBaJ7p/EnYXSxMPNtXo0CKk6FSaSWkeoozTw3H6uBjgSj44mr2uEKiMo9cA1RekXg8JrzaOrrXDsJ+JKG/e95dayQoGY0LHewDcDSNxA+AEHvRPHGP1phpOsPb82bc0uHT917Tytl4TzlLr07yVUPgmP0WdhB/g/2FJx2l/Ak01u2Ty4WFAqeiX1qg2VDSHT8Qrm7GMWx1lTYtIjk9WN9x+777UKEGwYIm4rT1Gyl+ovlWHK/2hJTqNWTAtL/yQXR8gY6oPaWd05ju1Zk38s3piFkWKOH8iJdUmJLGl+QVZq0QcnnVBA3UfSXBz/TPnQLGUEOf8DMgk8VyTXR6j51I6xn/2pHMaFe1jx/FVGzBgtQwe2IdH5zlEJuaXMlxoeb37D3o7bAqv99OWjQL7QTXdqhXRZo7wYr0PlLoxmZooCV2BgviMSi8UduUo9d//gBGJoIMrCPOm7a6WeL+ft67xWC6kTn//nNbOC839OpfZ8n1Zvr/vvOXhbGuh2JUkSQy0GA==
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: aqra
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: atrenchevski@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: atrenchevski@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network
  namespace: aqra
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/network: 'true'
  podSelector:
    matchLabels:
      io.kompose.network/network: 'true'