apiVersion: v1
kind: Namespace
metadata:
  name: aqra
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-sa
  namespace: aqra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronjob-cert-delete
rules:
  - apiGroups:
      - ""
      - cert-manager.io
    resources:
      - certificates
      - secrets
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cronjob-crb
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: cronjob-cert-delete
subjects:
  - kind: ServiceAccount
    name: cronjob-sa
    namespace: aqra
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker/single/docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: flask
  name: flask
  namespace: aqra
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: flask
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker/single/docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: mongo
  name: mongo
  namespace: aqra
spec:
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: flaskdata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    name: flaskdata-pvc
    namespace: aqra
  hostPath:
    path: /mnt/aqra/api
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: mongodata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    name: mongodata-pvc
    namespace: aqra
  hostPath:
    path: /mnt/aqra/db
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: flaskdata-pvc
  name: flaskdata-pvc
  namespace: aqra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mongodata-pvc
  name: mongodata-pvc
  namespace: aqra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
  namespace: aqra
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - kubectl delete certificate aqra-tls -n aqra && kubectl delete secret aqra-tls -n aqra
              image: bitnami/kubectl:latest
              name: cronjob
          restartPolicy: OnFailure
          serviceAccountName: cronjob-sa
  schedule: 0 0 1 */2 *
  successfulJobsHistoryLimit: 1
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: flask-secret
  namespace: aqra
spec:
  encryptedData:
    APP_ENV: AgAqzEQJnMoDvS/YdziKgSu3aS3OsyQ4FVCIf5DKDyZnv4NPFbPcSUVzC0zUDltGHux/V3BXyCWxpy+ZlqvvtY6qPfCezJK14N65VN99EMYcwF+HV4u+Hc0j4ugnRlNvdixPk2G7otbDw0gNx57Za2d0/fw3hwUyG/BQuAdte4VWjhmHhD/Ip8Ic1ilVcJ3MSPywnV/IOfcps0FpF3YfJS6cRuiR0b2gw7CeXUY9CTpEKDjeMtl6NyeryNNBKfYV/H+AtEHuxUfEqjFrYwt0h9gD9FvK+eRqtBjriZn8A/Z4adUb6v74Axw0e3aI5SJapaJwj2VUEyo53ZeZnBTnpdaRiM3vRSw5f6zAxnZ5UH5sFqzHgg6LhicyrvG/81Y4j4WyjL55EDcr7kjHP+f+EDa16u8ydHh6DSqFPCxvxsCOoDH43atk1+acVRLyxuhunLqQe7r6ffAiYajM99SWBYp60UjXQDzlHj0FCxswpCajQk/o2m2yiALjdaZw0dfjr2goK5XY8f/O3DrQkMYA+554z6HfzSdGet8IkU5BeU4ZZy30phageJCyC3Z+nmnpn6eJ5/FhJjwD8LJS7KCIEJ2tYs7fMssDjnuwqSW87kXIZHzLX1gI0a9dMVZ/Rjuy56JFhW9oaLMVJzStbZHObhUuMWwIiXeetYcYKQmMeq45e6iC/9YmlVRGv5bbnoD0DNFYOWwrQeTtvWWI
    DARK_SKY_TOKEN: AgBf+BwdC1p8UCA53l9Vc5IGRsgRpWMugh4wLctZjDTUK0KjcWbiwIvEYDgdVkIOpFc7rjC5r9u+38E3D9Zhv6qnYgrHV8M6gdbnYta9twX+nmD2RzYwghVpatf5cBmUuidVQkbZtSy+2FdPHTzrZ2tW2AlhHVYi2Yqy7wlDmJLTNERwqNRW5diBz8vPhudkjvrWImjJDqrnDIuocS3XWg/XSoqlYsZXWFMH0nufzjF8JrvuQIm394c6HLrmou6BAZko8ONGYuP8QK8dgUkJDoSKzdmqGt5uu/tqobU/d60jR1k4sy6ClRTdsuQKZcBbDs01mTjy2AHtreiDmIP1oyx/uQxaGM8kSrldYwiqO9VTciT8ZoZOPmVU/6Kcw0Q6K6IztXKC5S/oOllECyk2CdaNINlYLvEanwXwaucMehFyJPDNJmhDzFWGRQrx2gj7CVh+1L6EN+5qV7Xt9wkEYpPp+jtgjeIePVg+Gab+Nyqh/Na/azs+WnI9hl6h5aMtw1zRcoJHfPIXIIWmx7/SKr31llo/ETmBfrq9RfJxj0RA9k7XsKetRRbYy6Nf6OEUC1CHkpbV4C3Y4firEMObv+MlgGET1v+uXAwQ9FpNEgzAj08Ao2nZ33C5XQSpltxMa4YsBwHu04POA8Qwn42gQLAzIdcKHpjztN01r+PKMRcVnlRQigT7iowIioXgkAUtpZo7uU9VVtvbWU5/fQnHV3CM1KJhEwGzRwqz1GWUCnaOgw==
    GITHUB_TOKEN: AgAotL0O5ZcJvSpXYPb//3LutTppPXSyqA5ITLz9ZZPXHebAoXmSKj9oXW9e82D/On9z5T1318RbaQwGvhqXVsGT+ov55dbdX6+z/uc4ZuszXhbN/MZvLNe41lQie1tANa31v/YcPcpvU9vKvowiRFkPJWqiIGDDwBZcEbKv2+Qogqht2EhedODOAedlVNHA2JkJsxnTCf8y0B/XaMkjmeXN2pc1/KVBJfxtCHLgy5EzqKAgeCQ/vo1tPpZWBs7w80Sy9qFwm7B3ig/9Zgv2OgjXjBbBPQ58t+EgcHHOUZGWzopCfGKJKYe/hSIN35boykH0aUx/bMwzXu9PrKBjPmezt15Mim+fRGYiLZ9cJr34fBKx+NdZZfFvch7I1zeJ9wzfgJCpf5aQuacHA6GBTjBCx6q+a71rd0GBI97VcI2SQuF98wthHjZBctekgC9fCtALkn94Jdy4BACKnuKepu7vqONl1YsHygMKCg6xkLy/dGApnc6a+rAt1bOPTqW8gPXUi3NbtbMzlBWUzD07to+aIGjIgInRh7LGpT3oDOtSrBwGdjJ/NWME9EAxwLAfQWuTEjYpHHPgml0UeAzk1gueG9y659mAWlseuQU+Jh77fWk1KgghvZTj+uNeZh90FkTn7/da/iBGW72hSIRTC/L/0RVgpSJhpuD4qEh8uX78gz3n7anX6HnlS6Tdq7ddyi898JG+33er7o32jU9vST4DcQtX3mfzIx/XmvAjuwWpAB1Ud9yDuRva
    MONGO_DATABASE: AgB7fKcBtY0VJw4Mvf36KvbBbL9bXljXfHeNmaKgLm8Cg7rih+AU+kwVz4xEqvXFjH8dVv2J+ZGGFLdN2N+xTGlVo1ijc7eulrErDxQPMGdJ2FVvyA7dJ2fbd44xsqFld+FzSZP/qHYImRA1hwYTTilhh5ATLLa+tlyUY2lIi0nFnqRRcKE1mjxdn9b6SOgbPqNofHBc2koDpGh4BP3EO/AYdHUuuIqLTaa1NNAttbjN8xtzjS0Im2Xtl0N4lAK5IYXKSKOQVGUsZAvP/GqCGAAfYh7/yomklKQxmwIkPhWfuPnRLkQhUqae9BFaGOk3GUDQ428qTTFlQnqBdnlVkO1RaPsx93zKIJYtc8+gm6Zw0i4zm60BP7aoKU9ZZ64D+oM5R6mf7wwauIQw5tIPo+lzd8UYIPp4gARuWrN+K/ohBq7LwAS6RF5GAzxWBv64cCHvO/xFgayyGo0/JcHnM7MeB0fjYdIOQP9Ghuuy1Igjbflh7Gfcq+gMjGwZgWQ8xHfgMngls8P5dKQTK0vFvOlf4pL8T8Jpad21uhbtNLeWiIC82rvUUcLtLy8LuwOpANFw1/Ef4071Rqga0iCR/KZpSJ0STxImgKOm5Tyy0roSZkQmYJfA8k/h2usRIMFwlWEZkYLYqEhe6xXRJv4dBYvt3Axa30wo6F7impKypZuah2ZD7VJzdswd9y734PKBP/hi4seBTlkaXNqmdw==
    MONGO_PASSWORD: AgBUI/CJZPdwP9aKnZskjR3Srz3MHbgNro5nRkfDfxBysjqeAPEAc5h0gFz6HVpaHINQfuV73iNRXo7TKpQU9xt5LIemdenL9WrUZeQzoHVXcD/k2uU10Ygz0oF1FXBADKd3DOdKgtbzBX3bCmBcwx8o1B3O3mmAEWv3sPcEce0gG9qE77IBN29OPmS9mdpmRUlfH2B1zSd8mL5vR/tPOxAw01cNBIju45pGEjqcAzA+MoD+ngbbjgEKbW52DLZvpjPkpI2nq9qOVTbp+K1nfStHI9cE/FLiyMW8toVX4ueNtD5YRXv7RQTO/2Yp9xcl4yLZx5mw6RTDZBJUCGCkdTZxHT1zeZEMwV+nvOVB03BjUmm/J0oxGn39fMLcaGNVXxZlO2f/r+1VxPXgjOClVYUlkMA8M8+Mrz7uIA/sR6dY8FQoRVErCwbc952bOJ3ph586Y7S4PiHGKXdsuSt0buiy2yTudyPm9la7w9Z4N6GlQ57WNFepIl+guIssynoh6BU+kRJmezBO4OuUmfJhtXhW/xoFFs0xzfMIcsE5kiM5GDeP4d3oziqS827u9m8LfErjUc/byb1eJ8cMJWSumhfknoggxVVSSkA0tQF/1L5JWgH2SqQ/VV/FPAnVnrjReDfE07ZnWhspKnw/NnXzb4/YH28piGrclqKU4WHUq8tBu653fWAGzqIZjDq4TCs7tANnuxJaJvhDj7eW0f18VFc=
    MONGO_USERNAME: AgBMvmbvuS8lj0zXOYrB2Ox+gsgKWl2T43InoaezSw6qjCdjI7SeBWyJXS27ilfSY4LIUbdvMHtnjlG6SmHVJZNHyUEr+rWLgICBpgb/BZDi5JFALuiPPWAkIyo4uKyMXkUyizjErrbF1LZ6xesWAn1AZEgRD7On9YjOGQdWyKyKg63HwhH9HoNUSK75dt6YBSDmmajF0f3jsRkr3ohnLa/mN6pyZcJXw8jHVT3x2uweXBjjgSADZtKxRxs8x7RKdwjPfaHGFoNAVrgPP5r79Dc4JynSNzHLShOrthzc4czZmvRjoNmGwgQXG6yfr19xcYdnynL1GFRo8lVWA7Iq5Iaf85YKVQEEjQBVKc49hxIx7cnBbcgUusdm5nVVcqFlZq/k4tAgWu27+Ekr0kgfF2Ue2Qj+k1YdEVPFSMqIDD85ixyBwaEczcF+JUAk/tgsfchAXV4Un60eZLQCuFmSLBfkDiRlbwEjSEmZatmJIl2TvVoYq0JrEy9M/RHG2Doo09PAOzKa9Ka7284s6bFEBpoq87yuc9aLhckMk4yLvDsz6XgQadq4JWdU9tPKhmKE/vVwO1T7b8hUuf4LDVWBCJASWjSCQ7+4V/ULrdBXsKaWn48Yu1tgFX68yVGXKtUR01uEgjs788/BS/VqtQMcUmnCwcu0LfgBf59VQBSmwTjO7tbGnFBRi0Pv/XK/aguIbzuFi5Hiv0lkazsCFQ==
    MONGODB_CONNECTION: AgBqHXRu3xdZ0ar0y1xV++Sdac+XafBAx7Km4a1L81CgdzInQJxMm/F1Ebc5xTHiWwWMdpAaufvTSVGS7ZAL4+jfLGQa0arfqIDZltlXL5CkSMh0X0COrAVj5X07i/51Lk0t5xVViCWMPUzmFJ5xoZg3HIQuOi0SOud7NpfknnRNhdpEmzRDYkVEGRJZN9jnsLVa2TZtL+ufECuiIMxGie/Nw0YFlN35DKv8Unwu3ZaLIBMT2ujqkhGXvDWQ9alGEk8n1i06ROtDBegYlYAShaITUg9Am2+mvH8UuVQanSgOIWNAzH+rACX4g/PvtXdTUtaVrPYovyarl3pjOg9Q96jnLoqtB1x9XMJRr2kR/U04ieBs4VhGTlOr/43Q8P/TYr1bqG3H7b/TOCCrCsvTkYDGlr9sJhWhWZVNinHB5sOtnlVmpx8PM91UP4OWadjoNJF2y8laABea8FQdpIQQfXuEBs9oMC4ZjU1jzP+nytDv6AFJqgXhJWqL1MGv6zNj6QIgEutPdVnkpdV9pqTkeQv6BGsuGGHcjp/OYq+4/YvXQooq9lIfRj1+MY4oHN5B7TNDpLTXW6gk2GTaF2OhwqfWh7E7DtN/E8AjDUorXGVJyv6FtUT+O2vIUkAIKpZU5/MKZ0Fiwan2vzsdYj7dDTEMmf76IIqNRzrc56h04q1CIpt6n5ZNuWrxc0aJIMzWFxvd2HqVjLyI
    MONGODB_HOSTNAME: AgCaeThyeyQnFIQBxEZeVY6APzfs1xNcQ/jFLWcT+svFLU2pchXpmvYNfC/WUpdp0eUsB1L0DQipBX/8Y83ysoFBOFQMoBXtoAv78dMB9DWayTSKh1AyLIDPYx/tvnb4/2HQcVtKr8bmHfPe02+/LRpHKErhj+NZfYeCWrvc1vAoovnA8UQZZcRyfONmh32fVT0mMqmjerxOZwyvnNQDbNuWgoTOfeuN91r5JHEz+3MWsTHs/Zl0ZnZKRKK4AvUImc9/zFfPAF/UbyNK4kbRazLK2t/JeDsDGAoYlLrK/vwPhF9hkurorZOdkuI7UabVuaMPYG+FqtDMRwnj6E9fabLqzU1XRM4b3zDM+TO8Sq8Gmk1A2jgk//pLiN7Mr85aVQTND9unHDduLxw+efWZVQdETC3rugwaf4N8LoEFfXwgweREwK6XBe+WbvEevW/hGwOgWMVmzBvxUAMtkqT0zyHPfR7KK/IdhAfFh87cOQOrv9btF3siOviFjs0lz6jjNO9a0u/Uthv9+4oY82rPsL0rgjI9h1YDQuK8Oubkv+3leiXPjR1cOJcvzIPSf+z9gJnlvDs5q4nXk17EAREBRmQQFR97Manxc2eFP2WqZdyPQN6p/i5usZOwC8GqLNB+b6fZBecm1wRiJXxrcyMW0qsFCSp/RuTSLI1N1wPhqfEXSdbsrt0YLbVXQ7Gdn8FBw2MH/cKq5R2MfPDtnQ==
    OPEN_WEATHER_TOKEN: AgCHpcKJ5Ox3rdEBNv/0W23/hZK67NOEKhng1uMGwOH/8QVmcCH321Upj8+Z2v9+byXswbzGfRbYVshE2PL6/UWXn21nC791JDC4rUTNa5XdkS6Zd49MKQTi3NSosLfrnm8Rcih278Ew1xHVE33RYgUY4iQlsSYAU5SYwEw0mWgLiKK3NY6sj9taH8VEl4KR3/9JpIXXdN8qefkaW1Vc+CHs+QOBnGOjZwqqaC/d5ZxGEd7qgkl5QZNQuhZnYcpWeby6jGDFdfcFHCUoHdpvFd9wRyqtMKWYEnrHZwMF7NbWzrMZfpSHNwNUXURvnUXcf/G9JTpYVpN1EaykKQJW95yX4NY/drkeGhzF1kMGbkCK90SYxfTp+i8Cndd/Ma/L4iUfL07k4MnjPTPt2/zk2pUUF3wMhwe+LCzVbhJcnpdBZrcjavl8P1Yv3jf7kH1Wp8FEndG1gDX265VALnBciUu9c8UJHNFO1zRViu9JMpyNoSjApRGvr/gCVtLf4gs2kGeMD1WHBPgapxS9pc9Yq14waZWSgMu9ZPGWtPIQR4sgsHIPPAAHgwKoYhRLCwDRblDrT3TZrhQl6wV7IBYRthR2mKD0CrmQzN7DZQjcTyWXuiIoYbzA9x8Db5jF52/xe/5CdfY6J9w1z4zxV4yg1Hm64HTDO9rKyHi8bZ21OonlW1QIbjsmDj6Jhv1RH3WFZIUa/WzfojwF05w0CDnDRAGAizUlQLE6vIBmfsPNnSGjdw==
    PYTHONPATH: AgAosi8MCtbRAv6Y9GjVEWZ44cLrqaxC86wMx8kF5TyA2KnowNXdtSDY4Vhoqb5thEw/iMznHgtaQ7ADt8x/WEu3XJq+mp3RMi0TYRLDoSdr2Gn9OSBArBbr8KUzjfP4tLB1r5yuDyyTBMmyLoMzxzV/mWyaLdJwfLPwTuvFM9HM/R7hR7aHJTJJVhNnYwZrlqR62AVl5vZkV0iWD+UpQP3jvwz/cAUofoepO6UTU3RU21a8CW3O0a2oRX6X4MbjIp/D0mQlagNSmOuQwxiB3FiK7SSf7MMyqu2onqjT6BbC3LziBKUg3HZZmTTvF+9UVf9S5QDF1goDy5BvlSl85RFmiW6oMkkP5LskpcX0OYqwasCx14MErg+5rK9c7N0epDWU8jeqNbCt5Lsuk6vtxpmPfxc3Ew/tFn8Fqvwj/AipUoGFWU7bWhpwPhbIeA7Qsex9bVsljmP+Ff/qqRN8GNh6MYtRykakAltefAhzekpGtPGc6/yI9BN9ifQKQOIEhwaTI7gkoka17ctuaID5lTDp+gXeNm9vnooO3c0I+k6j1QHlzg+Sbc+H1e4yFv+7dWhdKOakUdqcksFtYhJsP64KDR0wjNbs1cPNgHZ+ollyxszMuaJavUGLw2v4ZsJJmTEV1xNTqQbjSEWdQ6fjrvdkoPt9AdXrK445M+gq1DQv9AYD/zM1KdLQ3Of32bXoXXdTt1FPVGqdSg==
    REPO_NAME: AgAUc46ezU+95kQadniMZi9eXsMKZQ6+YYjzbsw9LgDyN11FT4OwDS4qTJiAU/2YFA2vAXnAIBEKN2yud0hdV25J/+yyDvghHxQRjHoS4Y+RzvcH8Vq66Sk0J8PH1nixhv1qURaS0z/wksDe5L4N3TZ69YHiCUXXT/3i/MFVTbyK5oBzTwtoOsHP+YUzvP37NfXEjh/wauLFYW6xEES8XUmbkyNoYPEG5y9hCcgwu78fj6jRoCqayy/I7IjIpuGIX5Nfcr/Kl8iwubmiR3XX2oIE9A3fRKMAku/00pq3m1vZG3aLCikCZe0JW0wwh5qEg75czcRSnPQtvJpbPJbuMpOEKGJFeDl1NmV3lUh6AGKlYMyxArgA9ERSSYlQ/AaWlfrhHAv5V6j7YmjOZaByUyFAul8QWX4U4KxeU3uuMjvIQ3ClbScwblhPECy3t2shtmEs9yutacuhaFUCwEcBK/MeIZFb3engfuf+XacWHlhJkuZnKPlTlYpEpg/pQJc/Ptne3nhd3AlKWDykkMgpkc0VYJLH4LIGXJSZoMDBWwg28XVoitCrtKJKUwCVBkV8Nt2Fp1RGkzAzicx0kgKl2TksAWaoMnD4oFulhNOTb9t2yeKsfuEO0X6fVNrHaQ98epUD7KWkbqMzfglUgJ+26QkNBPqQd+ZKQE1tOkbme+SrxQ0QiaY+8fRmDaPMswVx4Fw1gAGZ7vifJypUorrSvxg3gqWAO80=
    TZ: AgAQ0A6rjR+R6aKdHB8Ju8x+vbVsnBWna0tiDU/9efuyR5I4RUex4rdsmOV3GOe89btQgGnyVbTp3K/3s/JH17b725n10EBhJarf/itsVkj7bJ8k+pZCk3RzZxzpHA+gMDYFACG6JmIvnYDRv5Bj29mwFH5Swfo1M83Z5BEDuombZjCeXqYY2uaF0A9MPhkTgxz2qAZ8T3HnVCdvXUVIZVmbhVrflZo1eo9ZEy+3io8IzekmVKt1kV3yHp/snpYS8ABuNAmAneamsYTS3/Eq4T4FP2idb8dRTD//NVvgVfq7D2Oe/4IhP/em0mKHOkKpf9mFzQZ/koVWljzQqmPpzmf20n4Ucg0RN80c/KS/VXxmCMGOqWEh44Dp3eV4nkV9hkOrjbZvA5wiXjKfOkND2o1hOoc92NilKGOXVJpI7Ls7z/U1gavgDm7xjPhK8bP+3WAvYfwiWTPgBtayOG1il8oQCbib7Tg9PHmuhqBZ+Ku1R4tJCwBDyHVrma2oL38bO+WlKHeYiQV36LWcP2FZEFysB4M7vVRevdtIwdZtB8I0WTOiTj9lAqZMcjukTnLz1uCzDdK7bHuhXgmJlU2sNCS7Bj8TRgA4FljHpHwCqGiNfD6h6gwZmxHYwVgTUAJ2Wu15LvglEY/k2EsydnPc2auNkUfmoQ+WtnbGV+osmm7TiuTMaPHDXbu+ziOWnuYMC749C5KbkX2GxSFwMZ2x
    VOLUME_PATH: AgCDS+WG9t+6ksBJzKtJ1C3hQ2PDlVE++Db+1rP+4wHMKH0Mez4aOqgyLaDpeoYNn54OY0B1hO5fhWT/VKqvoPwtMi1po4PsZgmQn7hnN4GZpLBqkTeV3wg/Mn1p6hc7LCc4CAuG9256koFXbjcFJePQlU/VKPttV0n707HLdCG4oBV0TeQ4vTZ2ZG4tAgrq26DXa2kFz4VSOo3iL5PckLgyId7q/Iv6cdksz1Hk4HrgoOUzRvaJ81kPzX1Znq68v4j92ldI96Ls72fsExUzdc6hhJqAK93DAq4LGQBa9uowPzARzWcpvk7eLhx12t++3Ar5vG/mSHBIevQ4A71FPVXJUkx+dAz0mU8HhdEh+I1Z6AmfHWTihKvwoAOwJ5LFpVKXXszDD8Sg7X77AMVIITQMZlM7MiBTTp7sVdHtf/9llmK5en+mqwhXQdpjT5aQQPNzxmNEJktSoUY/Xug4lUWTZOVM78o8t5fv6C4pnBeFFZHy6+OGDAo/fufp3q90cq1CRpqSU/C4QD+/onTZ7yH9H5zPqMxVu8o2+jE6P/T3fESjsKUAtgCyjo8PxpCCXeg6ABYITlG42L41i8ny3wYCdS0vCNof4j37DQ4COws5b4AvII+pOnQDPmHDt83tygwZLgW7NAHXi5Zdph7Tn8qiX38nO+9aWIGySucOp2OI5KXvAzyhD478FrG2Hqz7k+VcFzZEPr4c7g==
  template:
    metadata:
      creationTimestamp: null
      name: flask-secret
      namespace: aqra
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secret
  namespace: aqra
spec:
  encryptedData:
    MONDODB_LOG_DIR: AgApYnt9XP9/q3CUnEa/05zeUy5gOys8qeiF+vrPdaVw6nyFiJRw+BJzU+h7zfje706KZ0uESFxl17Bh+M12v5cv2WNz3swjeg87MKparfIZ+cxkfBwR1dWxe2hrWkgX+Doy9kCex7MJ2rjh5jZfOQKKxO+mZkinUhmkzc/1PxGJ7Ya0noJ628+fgL+we/OqLwOowuTqTVE+rPUhLZvIhM+GUgillfKaxKFe8EHtzm9ULnfOCqRqFSQ4mi8j6g1ZugM5WOPnb42TlWjcztKvozoGQp8sXAk6KJP8L03BVtQmct8R1kO6xknelsdFX4yz54OrsomvY4Nth405/0a4mUr03CvwgANKsqYw2yCg/IBchSJUiDzR40c+sqi4iPs1MDazCpnNwYqhDRulJxrlrvCRvvadTaXTPQCGZuDP2q3mx1Os/icayOeq5c2bqH+ju0pk425MmPWENihS8mCPff/85WwGifPVGgRPgaa/F8U297q1I3j0CZxRF11iqoHo3Ck3+R/m8i7JMB+qd3Du01LaEorBb6trUth61Y6/5Qh7MVhNFOmQe4DeE/8ROZtusDcx2wakSpPkwDFhpvppGqvMuxnVTk0OhBAfOHJ173XtQRe7SBZVMECj7qJT7aLT0ZC9aRCJPm4jarfQgjuTqIsRceeLu/YP8igvmwm8I4F4NUwOgASWMnV7eDE/eUKxouyjsEqAAt1+uk4=
    MONGO_INITDB_DATABASE: AgBkPYXsNUtBpuymjuBd2XuNp90eSWQhf4y99yi3G3OxinwHfoQWXpItZ2+9ikl9/7XsLZ81wb3A1RuP611R1P3evOWoHfo2OeC9Ob6C0mwxgmImwfgtk36I5KTdKu6vP8HNP6e8olBAfCLjZ3gmXPLW6Gcu26u+m2s3T+tZZLxHLpuYhiPEz+6gJB4i9xDPov+1MI3aZ3BSw3SdP2bx4VrtVsDDo3Ope2TjcK0WZ24TPQJc6+HI0OdNi4dpGrchl7K3cHNwUwPfubqoT1uAuxQY5pGeGMLtuUNQ5XCjqHn4FoTDQ9yDjBEJkcP+/9nZD8Zx/dUCyxWjYVZomzOLjK9jczkiTiSbYEWKbQ3288vidH8QXg8F8nu+Ed6VOKroca4tap0B0kN3pU9qBbPW1mu41yJzqfq93Muez+N78La0ie0okMZbg+TC/Y01Vqdo+gwQSc/lLEovJAAC3YDay1wUlMKv4K8q+aWiSv35t3Thk92m+exlleVgnihMaQXg68Nw+30BtgnQCFGE+OByQIGurBHgBzracK7pDnl7eZE2sFSai8lxCMCmsyammXZcsMO2QO9qrRniyajTNh6RPfHTma1Ci+u0PCNlEdMN0qFFhaggyEifqbX1oB+UcQDqmc8d9O0nILbcVrP6dsYOnpPFZUfrPBLRnB0IvEndXHYTttfj48zEthzKz2iNFGbpbo1L80ZH4SuoR6N7eQ==
    MONGO_INITDB_ROOT_PASSWORD: AgCdlaZtVycjCk2IuUP/xT/ORGTzXeE/zF0pMFQ9inf5MNK6HpiSw/h0IX7LspToUWQjod/Rc5Uwna6ayMc5rO3FLfsNkeoggWabfcIcFMuF2M8KhiesXLDYJz48s7lHcIDFF/3m7gdpydeouU3+jn2EeAj4N3KPGtl+7Qk8WDHTenhUqYV+4ULB/Ymse0lhj1LrmJlwYqq1RLb8rWHb0YQXjD5BGd0Mtcuivcp7vx1hksr8tHGHG46trfJr/8nAZ6pkj7T2bRL6W9SHtOc4xp4rkj3j/j3ix/AVRqZu9eIYdykAFrF7ovmRAmAdhVTiK/oUvile583LmasNT3eZ+A1sD+cvKH35WtiO5+ohYrJl2636GZEBhnI1GR0ONw//IeXGnjWAF61qiaJySR5S/RcOwvXaI+6S0gWfZYdqv7G1Qs3dP9A7jCsmBms0gPSyznW1RBL616RU8stfcgiMT4/2W5LuPQ5ENVyA45PG+45SGPyc1kRJ4VpvA/9WLyJZU2FrvHZ6zwTPxydP6NIjh0YG70FNTRuNHz/A2LvkPCPqSN1iyWj3pBTYfZYdhZLSgHbKrfGJIrSQHw2qoJQNxGuW0N8fuVFzk6ZrRD1q6SichzIuGrQyiY7qg4c/ZmEw4RF5+xY0KOQYbCa13wbFI4tZiYD+9VbCzyJUuzrD/QOJtV3sLKJ71ri0MKvBpu7IKq9DZWq0LjLgxMLdM4QTJdo=
    MONGO_INITDB_ROOT_USERNAME: AgA8ANa3eLk/Vf/gdkVckBpxpNclHwTfqZDfyLrOB0IjzWuUD/KFrwhBtb6n/6ueBkH79APVkFNGRrZuQnnqM17KWvL/i429ZNoGt99IgihALnttwiiNpyRSJugCtcbXRECxetxTl0kpQwrevFcbTJaqUA20rTi2pAlJXkNbs24HHG7cbgJZW40Z1bfZifngIk3DO0CMamckzspcMGqQAJ2FNlaSR4QqOHi4njwYHAQX53ts+SeWyvyjDQXEXzB1Y6hThj2+Ze3Rm+M4X8e2zGM5+M0yyLXTvZq65klkGYl+0gTPFRmhZVp5pMNmYJUwdNY5YK+xAtEFRvj0C0Bv1hutTveYRYZM2alfSw0vqoeQ/sxnLYdUAmiE2MNJJPYjm6ViAGZs7c6E6RCgCTR/MqofZOoGJ1W5ag0mY6Muwj+zNOzBCV3K4tSoQkpd+xhjmv5e9AUT0rZ7n80r9MFrqxQJEHG4NOFRnu3EVK+v91v9kFKkb4fjiR9ePHKYWORqU5c+e+fkHLNX0XxL03Q8IhvaQSeiCtd0fpJlBWPYmTyXuPc/inh2yuVdZHGoZM0IA5pQVF9PD0O9+7a6HzDlJ1O8gM5PZFgvEG7PBzjDnXUOcfckMTWG2ncsklTNkgQyANPYRMHk43a8zWvklG35YQB0MCBkWdzbUoy3NVMKXnHN0IKjbp75Uj5F2DMQjZI2SZJcNE3Jv3itBhoz7w==
    MONGODB_DATA_DIR: AgAFBAqxPJj2ANrFRak/2dhEWSq9C1cH5+Xs4u+kYc4ndfQX53/xy4SfETOzFNllArJBV1MlguM5mUPIWzQTtJHz+gWve0EMvGcJchYcN8WP3DhV4FH7uHiZAoImToTCuXFpiAAukK4ytXllGX5SmM64E/ckE3pYdEqEyd+JlBBksxSvzkYxbj8trSqEoZWLmmsWgGVyZAL91dibq6rK04kUxeRKuQh8huCh/j5n2oFZdHHS//S0wWrGbLq03nIhtZ7TJ/FEBpAbv7zABS+Fnw64zPTtvP6vZ/v5uPwdaPI4iJsJLwaBcKuyjTkWjavp+bkt3+Nx/1y05GNywGoDML8lxX9QYTmEAjtmnFTj61G4HiIIetisMoDT2vA6VBcougRpUFnQzm/rH2NzOhvZgegH+v/44ED87w2VXi4v+Yw26gt6Gtge/xzLZlPNC07C0YhEns5Hi/arjHrFX9ISVTg8kK8iWzz0CQCZ7YqHSigiK72RAxGbKbQd1C+7YwdO8KW+aZYBAMhHowQVriPr5VSjW12WhO83VN9a/PpO/PruM77LgV/WSUg/BMjXXbR230QSl9LURytGLE4kbV7iApHDg/5ExZH9b3okhhytLQJ3pv2C3W6l/IJsvZ/H+hfUIv5Uv1j1yIQmNP1sgVKDiJlMhwj5H+v42X3abfpAjvbUyTGnghMQ0zmr2svcMcLp/T7pcktBNEFXkw==
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: aqra
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: atrenchevski@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: atrenchevski@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: flask-ingress
  namespace: aqra
spec:
  ingressClassName: nginx
  rules:
    - host: aqra.feit.ukim.edu.mk
      http:
        paths:
          - backend:
              service:
                name: flask
                port:
                  number: 80
            path: /api
            pathType: Prefix
  tls:
    - hosts:
        - aqra.feit.ukim.edu.mk
      secretName: aqra-tls
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: aqra-network
  namespace: aqra
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/aqra-network: "true"
  podSelector:
    matchLabels:
      io.kompose.network/aqra-network: "true"