apiVersion: v1
kind: Namespace
metadata:
  name: aqra
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-sa
  namespace: aqra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronjob-cert-delete
rules:
  - apiGroups:
      - ""
      - cert-manager.io
    resources:
      - certificates
      - secrets
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cronjob-crb
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: cronjob-cert-delete
subjects:
  - kind: ServiceAccount
    name: cronjob-sa
    namespace: aqra
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker/single/docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: flask
  name: flask
  namespace: aqra
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: flask
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker/single/docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: mongo
  name: mongo
  namespace: aqra
spec:
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: flaskdata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    name: flaskdata-pvc
    namespace: aqra
  hostPath:
    path: /mnt/aqra/api
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: mongodata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    name: mongodata-pvc
    namespace: aqra
  hostPath:
    path: /mnt/aqra/db
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: flaskdata-pvc
  name: flaskdata-pvc
  namespace: aqra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mongodata-pvc
  name: mongodata-pvc
  namespace: aqra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
  namespace: aqra
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - kubectl delete certificate aqra-tls -n aqra && kubectl delete secret aqra-tls -n aqra
              image: bitnami/kubectl:latest
              name: cronjob
          restartPolicy: OnFailure
          serviceAccountName: cronjob-sa
  schedule: 0 0 1 */2 *
  successfulJobsHistoryLimit: 1
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: flask-secret
  namespace: aqra
spec:
  encryptedData:
    APP_ENV: AgBxvrBtuvxksY5RdBVXgN8NpEclozav04J8q6R4pLfMqbEUxyy7H9gBVNle0YmsPzRVGQMAdH/7rVVgv6iuRZkmZgh6kI/GUPT99iRycbSlv20UOr0LyqqkqDiT+SKMyNbTamR4jhKruTqYsaSU/0gnRX/pTOLBCyHtyQ2+SQhOEFtTYgsFJs/qg2RS7S7MHQ9goM56MQi3gA0xAAn4hmnNBYx7wvtMgNOSySLhIm+vVXID7RQ1zVTD2cRDo8E8uAC7y5VbRuOFYcz8BmpJ6MyNMU3wxteHXH7KjOGFbbNgJRFo4gUfKfP4rwqkZg8KIsjQ7TsC1DMOSK1bAgM/npx3TrWk261fHfkUNItlTORVGSnN++dLjYwlnoMv2l0FwUlYKcRuIyRu223Pzh/YyDQbG46V8iLW7r1uqOYrTEdzD+R+kJwLRg2trlGswMeagOvCpzRrrIq7oze1bHyO4CV+ENVHhbf9J6RbIVKNuTC4B+hJZGzTMW5H7JWrZ5tZtgWUBImXx1d6qSxpgKSUbf3K/YJ+OOSJioo4cQ0mmikzaGVMmFnui7WmPyXMOPxdEnzPw3yVBVMJG9kOtKkfnNgCg32ibxh1irhiJyKWTvKWmbsfwVJ3drsZmGjLBgnrXFvUsjjElWS87tqOrjBq7e8gxEX0scWXonzvYY+EV+ulbdQOkZgllUsJa6MSU+KrV7t3z4+LAkuuTt2N
    DARK_SKY_TOKEN: AgBqF9m9/C6wVCEKadmY8+KYlllBww0JxyaiqlE2uy8xgvar83IIuq0yxgqVQ+Ljk93lQsF/Z61dM6dSytg+QDtok1MJgmrtZk3JhtkS8k7+YYcAsG90O+LvAZfeKKVD7YhMBboeJSHtXbFC7SvQRktkTFhfmHYmiW9s4ahTm0navxfwyQknkni6mwtQ0b0g6r0KCmHbQCZ3vBymx2SwFVP6jCbpQlzBTlcizC+VIXNnTwjm6UvFvnew3Vm0YJXulUvZc+yoTdrPYRW+82f35giTiu+xcRKU+S3UFGQP/tXTo8IpGYKlzrUjxspg7Jgf9vMriNSAAMgvrMErX+bHPfHF+DqFXkiorntGPzfZe3ilSQ5rU7AWH8fuFfgWb5L0sdHmtJChCt1qXlJzhVdmKdURX6bGFh0oLiqqQ3Z5xST8iL9hhFCBLVMKA3nYacEOwMPi6xVTkkzvgq6VB4iBdEKfSsCxisSBb7z5MRkCrDbHTrA1cacXOMoIspRbvdQ9gjwuCcX5ErA+1SWAcC+Vq5NNO2ZEy+JBqQYZ/YrKrg40Q3xy5FwzrBIBS2pIlApvngEHezrTZXfmuvxW1UA0IhOrrDFNpnvldxuNjD10GAizDD7AlBBiSeF+cfb8kuTgtG9TrsE8WxvanuUa3lPPzH3OUeBoESuSWatG/taUp/u7FBi1aSYkixBZ3+kogE8z2rV/TZ09Lvvpcigc6roObRPfd/Xz2gQOjguHX9FVaCO1dw==
    GITHUB_TOKEN: AgCmGIPMfEmlbK/7IARrXws2/YFgfNEc3cvZ3FFGx+5urviEkHT4Y/mwt2C0R5m8J8k2133xwKKhStWDvo29lJJDQHWSaVlYCJgb7EtaxMPKJm9SCzz34RdiUcD6+Gx47YY4FrwJ6/qgraO3w8xENJ9E4gT1hNqJaATCIgmT8vx+cJoK+KKqj2Rp3u2WvDxdEj1+Of/iTwut9h1RPcCDgNw424E3XeveTMR92oZb16G9bKGc9PW3l69EIhIWVqr5YaOccxmfhT0ViXUn3xHELE1qt2qD+PDXqLp5WAKrzsftbNP2wXTE9jFxQMQ1CyjWr0Jm6XDx/z0GAaPJEkMgFd2iqTL4JWZaHijmg3bAegisHkhG/sxmwsLxaIrOgkKFARgcjpZQCjd8XiIkJd3fnMPxFj1XY9XOAQ4X0Hqf90iDBOlbLXudB+osFVXdcV/PEjeC7pr2JsOUpvA6hMZp1pnCoHUgAgrUWkyfA2ENodQ2ZUkPMejtg284Boj94s+GmEkEiebIArdyfkUtxCtjcuOKQK3EvNhrxHO/4ZFzSI7/codMjK8KmGM1aiTP7o3terBo70k0KVHP6VBVSleYgSZRmYQ6ujZoBD0bCv+yvTRlr8IKz881m/zXbeuu2fvODl/9epkIZRjLZznp/hOGdJsiA/dX6DjzDKflSMGMWFEKkp6A0rU5vP1UutHIr824lxs9WxGUKU6t6UFKno7dN+z+KXyU7xrNRfRbhwA9XYW6U6YRKpkexS/d
    MONGO_DATABASE: AgAIKj5TJ//5TY38c8Y69KPv998q3JScDrMRQ2wF4FKUR+zBPZDahpstLxIXpg4Y9/5jXlwiHsUFhcJfuugFrH5kN/00vFGAaF+EIG3z0sx1gYZr8PFGodVLOBXLwiQek7OtqzRHWd/tmC09TX+VNWZEJjgEuFuOB4rv1jHvMZY7koyhnWbjGEX6Edq3J7b9VJ7s53DSkKmrKbAKgTspefNmcHPUUJ6TO3mh9roQdx0Odqej14xj+aSG5pt5Lii7aW5eY1xjuUhEquWu9NzBWYFvB4X9UFw1e/4iNSZOxbxkxyTww7L7VfBJhmogK1kXSwcGdNQjUheV5mYxGVvXgQNbVz8kW6XD0tkvRvcxlYeavApE9a1ZDqjMfVQ3qAYNNpLaEsqpWQyADJ4likEdRFfAeB+Yalx4300DAumR9ioUVeIfy+Q4RAbVs2KFl5ea9v9GgAsBLr0aLPPDXeVuE2NJ2A/MwSJikpIZtz4S2lHlYjWnlgP8NVuM7/cQ95dUKew+l1QGEZOWWOBjJ4VXJU7FYKXnkL7/0pl3leqZyz+ZxN/Vj8bWsiea+SvV23FpQIz0rCx/FTHvu2vq1MTnlJxkQsK7dCZKyx4PoDHqYdI2cf7M2P+ceRODieCbk6S5GUYWdi69WHnqBKwWLKXWeOtJUAidM5AdjhqXd3bk4ZesWldgK82QPY8eamzHvaYidckgz/DGUXJ8N667Jg==
    MONGO_PASSWORD: AgCBgb+IruUnj3MspL7XYeAkgCjRVIHs9m52+bHvcBpwRly+HKO1Ct3ZBmwgU1PfbvsNucQNL+IVCnn4dJhjxYZske2ziPFFSYQ0LIAgNHSTulvvwcqm+GNoDLVN9XKqSlqd4rrBauJtiHKhztadrS6tMUUqdLV1EOt6zMjRMufvTL1U6qO0MoorpZ6x1pP3+ZmATOxe1A8/6FTrABW2iyYzIIgjvAPlhyRZH72K5g8IpIxiwE4UtashPMnmEUnv0mfYCBkTrfEHGwrjjTEiTNjygXKbpV38yikgTUhqE5XWXJ/07nL9/F/A35n6F2tnh4Gl1CFhVTjx8sY25pTLWDyFIbIAvvOjDJd3ZXQFpnpU2QfZGDKqRDdC6hAR0P6lGEa55gmBkcUNWODI2CWPljTeGkX8R2/FzQb5pxTQBan5nSxW7XaQbDikbJB/ov5lBRLymfrP99hLuk3HNDDnR6MJpwhjjGUPCAA/3F26PGNhi59cRc/aSQlaVvekVGjbfxHxgqFmScWb0WoI4ISsqCeoMsUaavDpx/MXWYA02PARfHkp/ND3MvBqsrL6AsNOKZ1K3omf7kotnpwuMc4Nf34dgu0dFwB0wWcBR/xP3pLw/wLc0LUs63LMm+sPj0P4v9cn60pFqgp01lnxsnw6Cki0ysWSVEelED2JX8D1unXWck+1e+6yj2jw18SiI9ZWuU582HzPCHz0QEgxY/sM0WQ=
    MONGO_USERNAME: AgAIY0QAq0Np16Suzw3zJRc755c04EpbiUBJyPDrtJCWPJT99V1BdCKDPr0tXtzsBRm9xhOanbspSTaQzXfyIwFS6oY3UiXS4rgKynp7VV1wptciu0JdBZAOy1vxpdzaeTz1kRad8UTWJBu/HWtNc43/w2FxETguW7IKUtlUV6nNNoxRWP2MdDGGKLRiI29GK/e0v338kw/eb4DdTLfb0DPGKr4yhdGCxO6T7B1vLQAJtAEZolgNAH6lNR5pUTuTcYxTxDEfrc0squ5uGczTXY4JP3LV39OhdAFBEe5zk3v495n71pM3L6EwTVFe4gXYtRPw83kiNpHCftaavy8NdDbt3ZM3ET3+qLPsvpaBHHAFdyLQY4KyNKLQhsc81KH55MimHT3LbWqcyvHaHxnQw3n2Pt3XI4bw+xMwTL22fGQBYQdeVxLICa9+9sYxPtjph440cFL9NVYQv13VxU1DAPpgRDN/Xk7rCFgypsx7QggXp//o8EH0JE+wXShsrn1yp9K+LMXpBOpm0U0tQKOInEs7BfQxd+19mzUIeViCw1Oaj8zzU/PTn8X7k+yLO6F+hZCni75NDQuKU/fS16yvZCzz8/71q1vXG0dxdcAFeE0zdxDtsmjfOV80zr9hnpsSdJh7/bycPT9jz+fw+h/rNnITNrDc7lgKlBJ0NZwSrnN6ASeHu425PSlWC1tEhNyBQkDEao7qMyZKtEbS2A==
    MONGODB_CONNECTION: AgANcHr/cyjz8SRjBJajMtGj92leBL44vCG9hGwzoiSRwFGXaFTPGOkVCEn1eiNU6vhu/ASjsDqMRiP3ixYFQDCK76KZQT/hzSGST39Hu7jHKJB1yJE6etD/qi6OpKuZ6/KDyKxdNUikxkY/2LPYVvi2fJE23TkLStI9vBRydGw71IpNUUqEb5/dq6zmb4z05diHM2wq+4sCUh8gH7oznx0iGH65tFJDwmp4JJJ43xiga2qzQudEZho4+a7CyE7XbkY6WSzAjX+hz00dAhRRKOCjf/CJtv7MLQCmgtnYtIm3sEqVfcORLV5QEQHnmXQ5r/Z84AZlOMebg3QnYEj8kSYgj+SsOOl/NNfM5dMF2wIKCgcC/QcqAZ7J08UKNnx5W3QUXSmjxFwYZ8grkWnI9mSyfOwXk9fL0xFohUBmoJeDYtb7lwd9JpzP03F6RO9IrPf+iftL+Mf4vFa81ur1Fjn6uM/LPaYICIaHAvN0dWO9htc1W5/BuhIacJa5ONwLezxSezZqD2xDK0bqRh4I4LfOZef+wnk3YOiLitv1M/uGiD/HOhwehzz/aKtodhg/cX2aUixlq6nQmtEtM0PA4SKh1FOSeyLhEN+wtoBpdEmskiwQR/WMNTLbiDOdDnY9DlthZvvjqzzrs27VMmSNMulmK2QTb2PdDHJR/R6EhlVnvZ2vYf2iKjSIN9NDp/z+pRW3w/WfFGza
    MONGODB_HOSTNAME: AgCN0BZaIotb5idE++PTXamFDRJfpj8GW3Xha3ajz6zEQWr/qdHKJeFvKEpsWsHzH/1VHSgFfoliKGO8IEHiAg4FPWGsbMvDBN+TjNb9myQF2sJWUsfAneStG3CM/PF44f9B8aSZB0p9QjbxsHH+tyQSS0snrf97QVjrY21ATDt1CChyJYlKiNorZUf3IXtsl0DUCMuU8KR8rTvdRJy6qn38XhvDO4U7IBBfkHsODV/yonE2NFKbnJSmO2hlKViznbjqVFZv1GNODbzg2NJDhvmoOX+Ga3eYVC0h1k4XcDNOV54VyVgPu5nI+l/L/nQDtOBTjRy1bL2AQ2NTNRDlTmo8Nr2SMvryVy+dUYWoMPuRSP926yuB73XFrpMK99E/gDIfmI/U3uTG8nsp+Tuhdw2LPsv/NAqt8jlzpUZUHju/SVnzxviisshwfFaZiU24GBU2zZLka4gwgY4dpsM7KCbzivjhLOyyCDKxqPgwry19Hy3BtFxvD4+RqzDy4M4JTm7IhT15+IwxNHrvJNl6hCFz7whkwNKaAax19txkf8npFSsDK/rIMkD7QXu3/6gdTaiyL7FY/NtaBl0YZrsIsS867u9yJqqDfldYAwDGItrwZiSyLArLmflGNE+H5YY1XzrN04klCBcmbPaBSDelluDFKJqzVAQuvMyhIqAkuBQJI3gNE3J3ME5zA/pTg7llpmAS8mUXvNzLKNjGug==
    OPEN_WEATHER_TOKEN: AgAQ8MJcBml5cEVabEgmZxzCvJkerZbPJ156LyDGCjOqkr5rgivgXwhoT9eYwOr65lh1u5YddNZX0x4bvLTpiTJ3NetPd0A6fPm555OEL0zniYFyHxLQ3shtkXUPVldatfzfEIJdhuyNH3LzCbwn6rlVkbN+EJ7sKT4EDzG5lwq1ekeyIYbzc8M3VYivYEmTlQzJRkguJNx6XrFR5F0COS/FL0aQxwBThYieneKZkcZh7yHFEB3pCjSt+zQ15CWO2q76q3oS6SAmtyhDiILTlKp21gCHNcwrPhsXzlt1MpRvZs4LMSy7R+9Z432prj1H2NGzxN2DiOMyRboZVh8TjUCbY+vculnjBHbG9YiGIBuTc8qlt5VYjgL/vB18wVDd3vzBxNR0SRPDQl0Euoyfi+D4zFCVBmrqIXTvVPMO2wE7DoBhravrEwwWb+5mp9YAxhXhiBZD5CYpJhJhvDIHV2lVMPayF9lz3DSkN/csJQKfjO7rEgQd2GPZJNvni/AqsVQlN/JXtHy2oiiwVwKH2838VaRYojJk0SeSFM+7NlnbuFXqCXnuKK3sYOTm71EA74Ncraxkne8UzXigq07bdewZMtKyEjOMh5omQvHZE50IjKcfA+chuBFV0jaIa7Lzf/xkG4boRbrYEf7QBYkJ0iMo5LYD24tkrOqcxjvapgji4hZhzHxfml6QWjG25QIdNsbCbdRlBk8sLM2xo24UKE1z0pTgF8v9RoauNFahvWcmXA==
    PYTHONPATH: AgAjCWY9gj/WM9BKqwe5/SZDIQwjei17R84QW+MVXpoJYU9VZbK4sf/xIoDGTuyeZJkc2NCB1XB7pxpcJB5ZzgwHR+d1tFqwipa20L/FjVFiJgbQJiPBoP7UQOz67NUzCJnUsu7gYDlky1nMjx16NwpH3MLsNV4ZAl01r1VlRhC0qh+XC5zp6Uh9Z4yaMaGchvp39Vj0nPfQAfQ5BfVGHiXz2oXMkf/rC9LPhoM26fO+xIP5MOsESWT1AVaJqjj4pLkyQhdKRcrAnp18sQ4AOSBfoMcEGR9tv2mKjw3a3zaq8IZ49M8wozNDVA1cJ3wQkVF7fjykE+xFqJvtKvRt5BYtrl2l4QYJVSz77OXOSGs/4eso8+5I2koTW9XUD0plxP5Gj2W62nIAfcCe9cpDd9UvvzECfNKiupaEsQFPTVT3RXwvaYojp42zlewAaCJjSCuIAMQWyiNwAcqJr6QscCYSF1jUsCHLPdF8OqJeZ6Gf7nPDP/vdHXRq9AOTXCqO1fKCNbIm9adDRiclGmEd4gbjbCwGtiZopQeFuX6NKAf0ADIcBbP6F0xHcX5jH+0JZaS/HDfcAYd5hAKtW0+VALnlfU7xF7dLAOQ5qkKare2ILOvrLWFoUY2D2PeI047vzoAr5c1u6tvKsy/uVAR5Pn0hMhjFNXWCKepw91LQ2PtYdfrl4DEz12YWHJjfS76fWxfb6eCAqBSklA==
    REPO_NAME: AgBxWV++y5JEcPjj/ns06w7YI3Pdq60G4QCLJzi9BFU4pMZbq2JgrxyeUU9qp76CsRbSLqnm2ggcorZtqWVn0QYzLM7vhAyF8LAlMvLK+Emnhq01UtH/6QNGO2bCbXm/U3A10N2xq5pCjKPYUzO5M5MSl0OhwMqBytsUmevIdA1BSAdYltNuI3ZZCtlpQHZjsGh1K8W+hoooDljE27HaicNqpGWHdi5Njkk/K9z4gU806ystJJzeVD/t/W84DjgI9ikFtbZzEULKdZPrmzccZDlbp/WEc2SGqCGyAeVWa4yJ9I++7VNB7ZQPjXc3xaJ2OFlBRhCubW4xoy8i5vBhV5nKYJVRdiYIxis6cnPoNV6c7B29rwQQGg7684P1nQX/c8bxQVTywL+YkGVzy/LruWHX5YQgLmd/NmD8Xu8wqbiW7DLuI69SJO0UZWz/miPPib4ej5IRpMBhpTus1LURZJZaD6aj6zQ+XmVc0Gm+Ag/1P7nGE/yRCSnRZNIy/abfBSiRLAGSkQLneKP9BoELl+NpHhO808hxtJd0tfSF6UMJZzagQPfAnno07krmaoqdO6VQGgU6847IXPyl3JU7VpgNYhwVMNpNUzvEA02mMl2Lcw2lcDfLdruI6xZHeNZVYkK7W5fYWJogkslcqu8ifl8MOQm76geUA/jYqvUBgLxCqEk8u2n1ic4Ru4Q1+k3NSI4Ba43JYKfzod6IUxhdCDuzQ+oRh3o=
    TZ: AgBVAWh4cEK2QigGWVQpI/1EhLf4E+7j1JAVDnKSjz5f6GwAE7j3Sd/3eQGE6HamM3bWBBX+Q/W4PuYVIfaS0zxmRX2jkNIaW6V6wFfMPaf1SnSwh0iHsCRTczhnDwoKUy8BEEJnaYo7yXnxARbNsA04oVFqqCip/rkXhcR8vNmtWsgFeZbDBHseJDSQWWvRys8K3mJ0rt0ep6rn/p8qwt9Wes9WT9qWx1wVGghQhCJInv5FCjikDwJU3bKQKRolBqYYrxBqJ+IUX3vbZb8M7K4NVDuvwGmF8NrYc39eNzXs17oZeJL2m6c3k0Cj0Av1ZjpYMlVGcc23xFqm0XM8SFTr4H9Dg9qGhKTPzigWXDaMAZm/p4qtI5dTEvichPDVko2E+Fcc3CV5VZnGGdFlkdzTU25brsEWO42wKmXfmE6JmZZFytdzDBTPCpV25+zmRqQXfDPcpiYUnK8JTV6qHrlkmzh5lh+eKtOSdRtMagJdrtRN9dHbxdR7n5+f7MLyUqc6miKEU/t1aIJ+GHuz3I8D8a+edDC9HqxKu+RniEgWeS+qM4052g9+EeJ+4VtRqk6PfzgSULCX7UsFQUs9CU46jYC5wI9DhWgvIPR6JSWM8zSCLmNp3r7+xpYpN5wb2O74QgFZksRH/MM32ULTIDaQY0SatVEBhCpt+hkD9LGYIGlbJaMXwebQQl1sUQr1W881ugnyRSM7wjdow7mG
    VOLUME_PATH: AgCZjignrXDWCYPj351zIroxzOWs5wiHpTdiUBJIjuZdbWGCLJZJZYOxXbcoDDWdDzbPOUT5ApNryEP/Z0qrL7Tyv5w8/RNs5fQUYh2bfT773aahYq+Ic3c/J1I48gxnN4PehnZe8yT6zpjtMMRgxRDRqzsyKcps0aC8zTEBdXpW+lqXY/tnW3eEA4hphe3clX5rmVbGZLiuM89SR3EMYUothCksmtJumeQKapGL+5GSZYUMHGDY1Cm6WUsS9pM+5MVo3joBc8tVn0GYX+fJAXBdXESy3M9QpKZghno+QOeplZAQ857m8nh7Xc2CdYRsu6kTqnLkCj92yZcTIeEofmd99mlvsr/ryA92j6cWvReZtALi3KLHYGBw2gZgi8IPGAxxJevipNpnb40+H+f/3WCCRzAUSYKc5LhzqlyacDBdOmorut8usVEJjeg9493BvhgwNbSvTHo0xt/1OfnhXfzZ9HiXmFoQd4PYbUD7FhHHieKJ4Lfbikz4HZgzVX9yolpMctCzccVdxlxmi4iIqPzL5Vb1tu9rr+5gNEF7fDkQj9TlC4WtGYW49V89TxKLpHm3LSik1xySxX1RGunH+nwhIkJbL6kvKenMMPJ8KlpnfI5zne9Cem6pXLrIDeXZgYphyRJ51K/TD7KVWkam+ycjPtGoAD0nUE31aXMa4GHjFuJNrZRlxw2ZuAH5slLmEdcUOLYDIudr9A==
  template:
    metadata:
      creationTimestamp: null
      name: flask-secret
      namespace: aqra
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secret
  namespace: aqra
spec:
  encryptedData:
    MONDODB_LOG_DIR: AgAX+2ZaCpjBD1VY5vZ4tFg1RgkZ+4Te6EQkLcfgEXP+drhRNK+SsFLarrw/wk2X1QoFWeGE6iRdXb2pNwnXFP1DNUKHwRka9tbARNm35kVFc4WjnQupvFrNJoKyTKA6ZE+/KwVGh2NEWk/WVaRKdkmTDXmz4ETwqkJE3U1XBJOWAYh8TB8Th0D3eKNIdxFFhdNte4hY29PMB1Cov9LoWVNhHicoHyZyYNupkYLsVFLErgOMEPKALVeUoWXMzh3hnXObi94Nddvs9yYcwzKl5M9n8zFz3ivrWYS5ocd+galKfBmg0LXNKcAaD+DyKEBZUyTK8dAq/mvi9YamHHIlGWrfbsCedbC8R+Ql5adSEISs9HmhjOTAtDsV3mNPMGeNbYTKyuBHis42eO6YIchxGVj9NYPmswbCZbppeFzwjY1DLq/K5A+mkJunfG9wGI4Xp8LiUPwZdLeijU90/1JD4C0yC18BMMCvb1HexqIRGsxuxOE3m0MV4PLxxPi/3PGtht2ffZ5B38/CIoOI0EJTgwWHPD/W/NywsNC948+/lfvzTrxJyxImrWvJH7O8uFbTmF0d/ooYFt5XQ7RUgJuJcaiNveePG2XmbpscdR1zbK7HGZJmXJ3BaW/TweQ+RIvdsO/CV+34z7CzHoxAcIvGMpefHxAe6hQhASF/rojOdja0nriAN2n9SAE9Hg1u0tyTdAUJ5fJH8T4v1F8=
    MONGO_INITDB_DATABASE: AgCEhPFaQZTB3DkwG2+R4oW0CaOLWeY6unsw1cy/gNsCSRFwHjWuElwsvwfBd30MqCgpYi31kU9vY9WS9FZ7SYR/+TS7QIYe7pQADgbsYpUpdozd8Q1Gk59gHK9hdVBp1gE5L4ZeMaYHlzLbKVZEuQgewq/mLHFbigBV/T9AAaW5Qpx7qRsCxYZIEMVRZw05y2pkw3BQk8eD2qpuxpWqSGgaqUd1BhJAkojNtW07WvdfCin3gprqb/Gp1U1ohgtdyQGk32yEVLCoTasyw6DKoHE8uUrewELChA3IC9CoXGLo4+0dU4pw0D5RPpGP4mIxJ25sctQVFACYIBcOPIzY8tbwuudYJKM59zYV6i0O3ZtCsXEYkKuzAoUK6vjlMinVWmV5S/prV54GvW+aMez19RUWR0Ada4XKDXhUStfJmlo4XP7dAttc/ryg/h89Eg9lZCWQsViGpDjVMUk0jhw4jBrfSdiQPOXphfBVbmYataCLjtT+xACD4qsTegrmLNTXfpdZPQAFuUez599Y/iWOdhM+0TJVoooSv/MY65blH8CWRKtbo1VHbEfplLdRvRVVUrS3A2dSZa1VdN4niqV98+1t9ogSmjq2cmSebaESB/vrtO1paSF+32zTgu4KAvblJYGFS2xmCo3dMwI0Y5Gj5aCyCfLMHRYtqMAqQ+GiDBng/W9Gev0lYys60VENEjIWnTNuHVFfxvvWEoAunQ==
    MONGO_INITDB_ROOT_PASSWORD: AgCZz1xqTKKkNoTm//69g1WDz4ux8fq4YUPAGOklkLgb9d1bcYDGPIeAZePHvbX8uRqQxReJbgBt049+PKDQpzp85h6jIsnDx26Ie+zC2qa65NIpMwrHhqTEC7wFfWQFLMuRADIpXMfSNMAl2GH/PupxjeNmxBSdI3QPMCK1vIHt9TJcR2EdshK33Tz6clchyY/nTOA0sTBdaDxfxhlvjB4aTZP6UeB1Qw7plWPDmHz4WNYw3AbA9mbe7+71B0LTXpMOjsyr3W8WI3JdYmKgFxbNyEvK5jxUCN9IkBpHK4x1mUENjhQMBKse9ELXTiiG5rrZs35nIy2x5pZyNH5M28yGjucqqv+HeGcTt24xckdYY6xEbGhcDWD4Ar/GNGrRYmI/z7B7giTFRvKm16DcRx/5KmWAb0A9ZRlp2YVWUoVxE8tmC81H9aRJ30XiaksR6MgzbqrvOv/zilf6SkR8DzIWJ+fCYt7wbJTh9JKDDdUYFCurldTwBJaAoP2Jc4rAmtzzVs6agjcl1FSA1hHEfKgg4enBFzLJG5m37+b6hruGT2I+H11QWo+nA9JYqVo+0nUie3CLisxOMlrM2Tq4UFmFkWJ/AEO1J8d5ILHmUwHv5+gvwM1WJwteHjoOagQkvDfeByReNAUpp0BQZ4ZdcW6wKVLQ9aW0wXdviw1jKbkE6ckIX85idR+ar5VUl/nw+95TlRyciXJojn5rL1T3glA=
    MONGO_INITDB_ROOT_USERNAME: AgAS87LMsEDVvz0KAuo2eJ9DsSS7AB4/DYoDtxBPIKHDTSyWGc+nREw78Gc/z3x0mJhiZdTyYD654JkSyfkGXu4VzfH+/W5ZzLpWd4Qm1zvXW31YWmpyywZ9AK6phU2iKOMzyi6EmD97AHZHISn/THHiLeXXLqaccWCS/VD/wBVbfs7XR2U+ZA+4vg9858YvIcfQKVcNJDep7LEQkxd6XxBSpdLW+VXca6UapwwFf/lVCIl58Wel2nsMDin/kG21Wp2UY5lfyGr19TQdfuOJlrypdaX8HWP9p/3EGZ9sjVjAvIyyXVADL3mbCbFr4nFK0JJ7weoaJlneLncHE+JGr9/v/UNn8/lMQnlE3DJZz2jEsZeScn48Fxx4MrAaTwq3g8lUVo++rq3nWJj2sfQmCru+9LnAL7QzgcHIqiESEvOokk+mcsn/kEnf8LwIvZfQ1swUoSdtjDVsQNy22/aUgDdyzGMhDhfhEmLfi7BShOSZLCrCmbBy4TQ5ZaeBaVESuxI5enpYcZw8ilAq2sI6koT2Vysnn+X/f/crBrzJybRaIByEaRy2qknmgUZw9/MKmDLHj/XYjbIL4cppkF8ve7QzPA7Cm1XxmRRJM1Wj7DoLQWYUtzIMVfCYA8oJB1Pmsc1sqKREEkFgKeKgPidHg3bcF2IBMWvCtjpryFizEc2zRD97Hitm4RxV4515455jfrM3z5CUZ9iXvNbeJA==
    MONGODB_DATA_DIR: AgCV7RX4f65C7xoluZvdXGmisa1koQuuSzjdUlFDZ1Q+AvSXoyeMru0H6aG6DzP18qjTcthRF01/VzM08wHRmFd4mfE0fUsUZEA4hSju8kCdJWE2Cj/C4mmvTHHObBQqrFaGYanN79xlci3YIW5gvaDy8r15AO2yJ+iW8yTGtcnO2dd8DdQWy3ifhL72TSMJKuVWyNA+UQvnZdLSqgIvRyUwcCsA2rZdRYPvvNZeSSmtTAxMNf2pOriDVV+Q/9s9LOpLs44IxIwh+UQso3G/yGV4MJzk3pf7gzRHbabc35lvewPwT1mxeV3KxOX9+zdG9JGE9JciNJM8+/FkDrkhLXcVLcseanahdhOISudiWil1TnCpF/o0QIjmUPA5GJjuTp75wmEyHGmeEaXUD0ga1qJPWrsO5ShL0axqGz3D4XYt16rreB0RSXV3oWKnQJXl2RvnfQjtqNClUm402dtXGJGoBcQfm5+Gjj3WmH5WCCBDALhhcVp9e3JiNMdx9KP86u8G7UJvioXTA3iL7K07mnw0wPgiWoFGbs+D5BBuCY8mfdlrD7WGIbz1ajVw4XCm4ea33BPTCJw3QXkGRmPt/gRynS4Xio+UFy4MScXQR5ieLKny3fmIvN7xK9PBL+uT68NJrfn+vFw06uH4hU9MmKNVoiAR2OCRpt2pHEmHEYWarW7KWe0m/SKl7TIQIOVfskrJ/LzwPgduQQ==
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: aqra
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: atrenchevski@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: atrenchevski@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: flask-ingress
  namespace: aqra
spec:
  ingressClassName: nginx
  rules:
    - host: aqra.feit.ukim.edu.mk
      http:
        paths:
          - backend:
              service:
                name: flask
                port:
                  number: 80
            path: /api
            pathType: Prefix
  tls:
    - hosts:
        - aqra.feit.ukim.edu.mk
      secretName: aqra-tls
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: aqra-network
  namespace: aqra
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/aqra-network: "true"
  podSelector:
    matchLabels:
      io.kompose.network/aqra-network: "true"