apiVersion: v1
kind: Namespace
metadata:
  name: aqra
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-sa
  namespace: aqra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronjob-cert-delete
rules:
  - apiGroups:
      - ""
      - cert-manager.io
    resources:
      - certificates
      - secrets
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cronjob-crb
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: cronjob-cert-delete
subjects:
  - kind: ServiceAccount
    name: cronjob-sa
    namespace: aqra
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker/single/docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: flask
  name: flask
  namespace: aqra
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: flask
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker/single/docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: mongo
  name: mongo
  namespace: aqra
spec:
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: flaskdata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    name: flaskdata-pvc
    namespace: aqra
  hostPath:
    path: /mnt/aqra/api
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: mongodata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    name: mongodata-pvc
    namespace: aqra
  hostPath:
    path: /mnt/aqra/db
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: flaskdata-pvc
  name: flaskdata-pvc
  namespace: aqra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mongodata-pvc
  name: mongodata-pvc
  namespace: aqra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
  namespace: aqra
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - kubectl delete certificate aqra-tls -n aqra && kubectl delete secret aqra-tls -n aqra
              image: bitnami/kubectl:latest
              name: cronjob
          restartPolicy: OnFailure
          serviceAccountName: cronjob-sa
  schedule: 0 0 1 */2 *
  successfulJobsHistoryLimit: 1
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: flask-secret
  namespace: aqra
spec:
  encryptedData:
    APP_ENV: AgCqw/CMElOPHfzC1sYqBh8brKih5N5KB6kYSrqZQCTslVeZ3fykZ5hMHc65BT9BVGYAA1KceyttlGNYLpND63wQQbkjb1I94NuuVN2kIl1aEJaoH+4d6iCoCsSUR4HNLa4Upl4cqWJv5E17y060tiG1yphEKKMzYVjmFfJx8Mz/uKFF28LdEZtJZiNBhF/NMTF7D0P6am0RCIy0x0fgINlk/i8ht2VLtO7F78oTjtMGxaxNpo5ARJks83WIiILj7GtXcq+AOXrTxAL5FVB6taYGCC8m+lLbHjG/6MDFaWVUTYFvZNpIQNCKmYq1N4j37ES9GJBKa99Ifwo2Fsl+JN8TYtQU4zXNlkfaot+w/eF6dnXuPEIhTqJ62bRjyX37VX8uot83ktVgMK9D3e0YmkoJq6vysFYdfr8gZzKHntp3xhx0rpYra3rcdPmugqqjQhUpq2Mx3JVnlPTE1sVFw6VTMUst6AGMTvpUyjLPDwYupbTf8/XMt/Qt2lvb52kXghdI+8yOtb9tV8eDPvvGnazd0kX1dQTCw0ygQcN+Ufsg/VncyhrJQD7NP+rCzqk6b0OMIM/UBxFwvhr0tDbJbSR6bEQctxQBGyqi2qrVhr2X5QBR20ne/JMHNKHCmvRaSATpVSzDiyl0fXgeWpvr1DprgtLKq4hm5HoDsnj2xFG/hQNR2xxwd+5n4c7rmcTlYPzNmRnFL903y1Gw
    DARK_SKY_TOKEN: AgAOQdpf1Kjoz3VPfr05IMTIGJtnZ+xa9GLdo5/423zVORGHM9LpT3diTRS6BYpL2zYGUQW7y5Ni5mjyiefnVD1fDsTHfkRsSvV0jDS27y0/E2nLU/N3XGcvKQ8t4nvDx5HegLj7V13ETs3+y/+LtLVWCPgnKXABOXoDiSeVkpQ5GePEe0gE6Ma/gokhbd3UoWgRG5qn8shCF3Rlatx1xFS0CRvrL0pHSox4qgONav8eAEeGAO+QGUh4sGKz58ZYby3tCbR8GILHoJpqKgX3C8DCUDFLQikdjlZl+Qrou01jMwuiCIv5wX+/SE3N+P/VE4JCwlq5g4slZ7EUKeAEW/Dnk0LdwE5JS2tHijlBKfWqeyCuLoku+dL/AJTN7FjRmc3zHvOjRhMQjWA3mvleb1CFhINxEaddpjQmWKWGh95PSkLNGK2YPGNSIVFFfywblH2vq6pd8Ro5oiAVAt++mRa350XnjNd3ruxWRuAwIWXAbJtkBcAKgZtQ+R7oyaAII5i9opVVH4zEC+XBfM7vfBa67ZKzStGIFIyFcH6K+XQEMCn0MMvC6cccUzQuZGyDeuSlkj24YL1UJ/yxmgRpLj3Nh5FtNYuOg5P4Hm+84qia+3ZCWe4Rr9FOoZj3zY5Jj7Gmi1c0NCzAApNHOrx0IsSdHhMOvNLUXps0pTC11rierqN84e2lh0isaT6axGj3dJkEPtta49vDXoJwuDCvkT144Mc9KsI4PHgYydaenrru5w==
    GITHUB_TOKEN: AgB1xrfL5dzB2iWEfGlkXwag4R0nmpBhcr79rrV4bfiCUlVPQg4V1howR6xyANlJKkhiow2q/DHmOc3nwfVHU0Kz/4U6rDoHVIrlrCwHgNFxFQ5vla9DrL4bbPHRJa5qTOwCPKAV+0JQs/sZ2Hi5sL5dPbT6cXXcbjz7pNjcNWO6jpuNkVOQ8t04GQ0vVBvaZ0ySABYTFh9TYVf2VGH674sFdY5L/NHjkxRlIu1eFr0yHzsY81w6+y3RAnfcCqC6sCac8aeMlkXrR+6F3OAq3YyemvqHaNAhoiRcODgxYu5ByZsyHexeJTZapFAfkDHGtbsxD8HGwqrjoDl9PFilqhbzxFyfNiMMzgnnuM6HNx4yDntkibvGIDgE+BnKNJ1o8g8gNYQnESV+MRVRHSfzppkKURjjB42xUUJ2LuubTaLguaXr7HFhIgqAH/ucajk0mABz+Lpu59L5Z51WXdetJ3s2GREK3XJI74CWVn3zdAzCMwGNIOozmA9+QBzMs+01xfdG6GhiybERUIvnkXDUJKOrlo3FQGszZKX9rZaQXvMaXlYbC4yHCeUz8TNIun+fRR+RSUxOKOxTR8pq0fdKd3QlCaMBwyzFqpcThU7NdYnnkRdkcMdK+YHzrREZ9lK7pOiw2p4v/AWO0WgyO04WBqvZqAjTRetzk8Mdx+yDyLR3XdmjyGvpi3G35Pqw+ZGtqfFmtml/xVIpxk3OcWTFNgOxJztqpy8TQgcsiRic2pNQ99VTAMrWWmSR
    MONGO_DATABASE: AgBAiITOLRfXecoTZsVpm/HMP7XscfHYJsJIUB/d2Z+CB7q1WwgAfmJKHpzxrF/5UbkAOlmSU7hvtzPBwhxfshF5gLR9WnGUd4rQWM91ajju7/WaYCfbh1rix23qIijCsdj7k7LxsxlbyzOqeB7AzA9ej3HaF6NaLEHhBUI8X3rhqmGnwZZn8G1G/WdpZjjwwgDLjyLFU4yaD7nwUcc1DOB9Abd5ro0+r+0Ido/45+dip+YuZS5olYgYdacfYyn44Hmzup3pHpFxsR2SEM1tLD7xqRgMmVasb/thB39KIvCt/mmOGPmRY8Jua+jhbHjOBUjZb3x0gdwpdrhnJ5nfYcntgNHRBlt84FeYM2WZbPqrhr6byN8SJE7fq6pzwppx9Zx8UlctB4Ze4CN3gLcNOkVN4QzpF+lKpC7yF5yGNdAudoahe7TciERCmFVgAMrGt8AYO4TezB6UnfHBf7Nw9wf8rbOihD8oapyJ7VcJpJ3Bfx38HLyf6NmanvaqTaWB8+bQ7h/1EB6lOyi77nyTRTUJTJ+WQSEfLQdxiIy+rYWt4TiqDWhSe1/ZLzjC/IJ4c0u2fi5F6uipq4YTXeD0m/1H33DLJl7XxIJ1cIvzJftV7s/os9qzn4ZqYd22Xd6e7ND6TpnLDhmBXw53pocLENiD37yxAZvE8mpNxBADViU3zzfjdA5rjY0Wpdh2t4t3xeYGVqMtyyWh8gRVrA==
    MONGO_PASSWORD: AgC8RdW5gml9Ed5XPgN9fXlzDhRjqBgXLq1gwJ3ITrJkFDevNaO3gYrJJqbP9HY0RvBkZuOxQKZVq/aHAi/ypolwKDJTd8IMKYLq84ggw6PrWsrLYvstc9dEtNwzW94yIo0mral4RDBnaHbPx7OTTVwBnaPAHQ70hIwu1+2NVuvigSWlDREDj/iTRe34ywBvMs0KYSYnn1oz56AwnhJd0lQT1lPNXTpGtNcse9dDyM747b6f1fI7S6MlgysWwtad9iCYQlZPs+rnWncob4sM3MDeD/WTbxuBF58pDKi/LllMZZ0QK3s9qSq82BVt9L8Q319fL/k+O+i/uwKvEMZtpQ5xM27HtEGXj3sJ3BhoRKbW1C2grqac4cenxCevBgvn7+2V3VfCSBANYPwdoz2z3YDAcbD4ftJYPM+Nq58pnVFabZCaP4CweEzSVFvSqq/nWlOf/bCxP0jW6HiX4fFp4AKgPLbFe59RvAGfdIiVTALDPU3DrtPmQXCDXN3TTB4U8uPy8Cj5WvTyORyLCvKn2HW83hl9JlyOfj6cG3D90pDQw8UPL1+ApDQ0oNyV9j5Enod9fx6A1/PhW6RnFkRbOFuqAdgu8HkBaaHnbrgmGbs9duOdt49wHvEfcDwJFmzP/6n9eq6J/P4wRt3g0/yHPLrdnmC1HxbIMbsPqCuAIdJhVrVdEQnWkU6pwKdPpaurc9pVMUMkAz+hdZz4xOlbh3o=
    MONGO_USERNAME: AgAo2cnHtFqx4V9L6IsZ3DjczLmrgF8yGQAY2IL7JCAvVoC08ICa46bhIlnvchOPzgLNVO3Gx1zRPDhJgZoruLx/BOdEcOTjskRVl3v3bt52DQYk3CMBdIpHdh3tewIQK48+f8t83dtCUJEN6UykvGz2vCU6qo0WEihRWflq25wOXy3zLbJvAZlBxLpm4c9xWnvyWnDRd/OJKf3vLaTQ8xAqz45D+G3UC6DalcSvyqKWZ3k5jNvaMzEk/mU1pZyvpxGFHshvqe8r1vV/b8P5UoNX7AUDJWB8cpxkYqQvS8cYJlnkKUHwNq11zx7Eoa3WXBfMX0GIMhFKLk5bWF9X1Lh7/Bz5NoALrwBKxolVVMF6r1nQ4bXnPOe2fyBxYKtLQmclyfE+vhBmQ4C7C0iYpu4xBWd/ozpRPHa6lL96DUzL/rmI/puzL2vTLGmK8EJDtI5apwaFJlxT10FmYVo+eCpcM6xU6BohlFd4F8WBca5G5t/VwZhWIsdl0jh5HTizLxneBtMIYWDmBAWjtMi2KN9yDF0egn41aZvaX2GwOrobqpDx48qeDZbQn+c07WrR4gAP9DOvmTRF/7AqrMxZxSCDbWVUoyEHMhVH0y6CyE7eorv4ATcoJYFxIZQfnZIYyqsSV8kpAJTshpbBoo5Gvi2EU9q4Oyrv4qwN/vMq0KcGSIm+PXX52VSlIaG2XpP4a1SHm1COrMaEIhZ2+Q==
    MONGODB_CONNECTION: AgAR4SeBP/QbyxNh7hoYpgo0yOjRRcbrOmFQLO/D0eAvrxY58kxYeO9t4fl3WeQQgoI43EupQP4NP0zyw6+Qr0n9I4w9O3YBVoHwrlLoqIPBJt6cNyZZL7HP9NmjeQ5esS+AyjOr6aojkGWBgM18ilavOpY3/JQIFeDiVRm/oK1KERAne8FyLs2IpNxvBCYclPfyG5rgAhkVND/iYne8teb5uTfM5fIPuHoxKAE+XLTqEBm2DlOwopx8bWGYEcgqTcHsP3dSfSOoi2uuGLfYp6mGMMhu69xjxOop1OxK8Bu2AGMUKcu4o6s/ogQ4zK3g0+C7tsuNKJVub8xrAs26dtfFWcLZoHqHtXtaJb6t+oIFnaJrK96QzwzZCdaPYeEJtSvKIRptkV2Rd0svCKrso7jYKHaCOwcBHOLy9SVOxWW+CqrS/LY+iaaaS8A6uP8vllqlXZCmmk48/d7/vh7HC3eGe0jBsLAdOuPW386JlUqQDSAitMqlZQginzOug8YcfS5LANx5M1ENw7RQWJKkqOWQVjSfbPsv1t+bVHIwRTtqCw0hWxJ5qyvM/KhYtLLJzXXF2YXaQfGeMCw56BO+ONkFCwx+qXIUD/4SJAFEzkLJDnN1e7q0QCw8df3iMsKE9V2aQGjMvIaOMq7qP7SNCCrB4YysozQGvbBk7DOQNsSB58ofine1ZwIu4vDNF2ta0grL/tcd4EKA
    MONGODB_HOSTNAME: AgAccVcPUdei5nNLCMtvHp2sONGr1CDRmroj1d94B9JNoCaCXnt3OGG3v/pI65v+kSQjcJswmtrWLG5X+B3jqtstSTvn045kdwax0bCZBk4oej7iBfV50LQGIP9L1lwBTOhpG6IkuxuJqIcrDiRK/HxYV/vodXzFO5b9gENa+WWW13HQuKeNhbpuv2FH3ORE+27CYZDNY5Vrk0YlNzJyYPZalrWgUGzEMOgzf9byT7/qQo4h2sqTsIOfMMu4O4a4HWuStGU8k3jvrCvyKS09ZzeCr3IObJPlIxKpcvcIZvOpOAsTw04F57yi4He3WwRqZiMMRfyXA0ZXcfo1/DO2TBy9vJsslvoa1upKIkKrJQEhXp2uPnMsS4auKsYgiCuChWrDFYSghvGJnSm20lpGQZ/ZblRV6K3qnSg7f0Qnp48aPP9IBSOw7y0MHBLhSFTw50zhdsCsYhx9TRkfgnZfrs7OUyECNWdasvs+3AB5qpnfDdugAXnU+JQc0UAiYs9EPQgLGqaTuUS+GwFqBDO08MOE+rj1Wyf2cvWmAQbjHu3ro2FP40KiX+bJNkUpYWoyJrf5qZ2ASWYwjzxvVOA8TWnqH5OQvMk7fpf+VS9rZ5p3XCYV0WaaOA9o5L2FT2AKKhn8a6XlubSCGGmdVjoydZYbAwKUmHU89wna6xqQ526b0lD1gndo07qGoR5QpX/LsmelVavjkv97A1hfNQ==
    OPEN_WEATHER_TOKEN: AgAhu3ikU5Kdl78dy3aYgfFVIJkwcvWuMMg83deV+DyjvmH6Okzq/5J0xIvkXpE1ZBl+RYzcNaU9rYd5HL0GNsVaZHBkz62IGWA5jhlAnoWNe+10eszOD66U2bC/dbas/FH2fAAxdH9kOIyWy65LUeEgxBC75DLd/2CxaQTPOb0fF4P4wc3GSRAyFF8TypFaqIh2p1OF0HsHczm5hRHNSZWIslaV/+ijrosEqbL4Ot3aSzcRezAD0vkRL4DBwByZM9Zx5OeFO9dSpClNqOoFZRk1R9ZetBVO4CvKZhePoq3YhIZDO6Pe4s+abGPpJISeQc+8PhJQMvX/8Szv1yTaArfc1tO+vVt2iNKBFL/zk5Mrqs47pNZit/L51f+ZcohQF1+JJSPMiGG0mxjqZMeFrWElLhRTvpAQg9s14JtKujq6rE3kLBollP2QRF6LKTAwZ3Nx2LuggJmFHsdv0aGZC7vyqkFJPywyp9rm0fx/9kVCZ2lHlY5c3jLAymxGsx4mNCeKFKD6yrabF3CTI7iZTYC7gEim7vsEYajbhi/PHXssvOjeMpWlbUSc5BNNPPetcfmXlAM5Zs6Gl4fwIiC7in6Nn+lPmUAwXkv5TGU82Jp4Fe9o3YlvuiU39xn5gbe+I2NTOo38UAsIGYraj/cYsmLJBsQTgsa5ugpj/OP04fNTXQgIVudvt5mCGh/mZB0Yivpa1SUh86yk0u/tbaytiJqeO+g2KaroOEyZ0fe02j0thA==
    PYTHONPATH: AgAdrTX81m6rzo1EK/5QGd2iicVNOJJnnEZoFLxu8NSqrsTpxaocorGAY3a6o/t6reoBdKNqn17uG7VpFopB5DtOSnikFw8g9U0tb4mjoYJQOXbaUJgsRGAcMxcaxkmI5JlQsSwAHJ4iRV5bIb3BPCkbqCM8tKcXRmQdEUj66Hnye9FwNzSODDk+6rPdZ+u98mvymZU3X/KvAd4szzKty7M91qXI5VCI11giMBbJwpP1f1oZm8TKEo1k8PkSl6rl9AUJ/s+K+tiVOUzvDzIRXjTDn327MwHwLOYKEGrLFMRqXC8pjKjPAzKp2CSi7+5P8SEca2BhTENAMGub3+pYlzTOhJDHyvoy/KQxzkazoihjnbpRsfjNBtL3oqY2/D4Da2ziIYB9/Mlg7eOiONN0kM0QSR7vZMrgT4QehXiS9+6Se4OexH3SDi/fbyW1pOE8/nLUSlJy4NMLxo8B+k+zxo1eS9+nZ7b5gzoYnOBPgkc98XqmjVjbNZD9Y3u5iRmYBU2U0VwLEaZKGmBlh4VcY/v07kPfqKePACUTj0MN+l5M4mhgrNiscI1VPVFECyCcFItu9kZscIVl2WqSzbeSlG7WcLDxKBKzvOKNDlKochsCnEprBk+R1P1Dc3BywVLgGHsjzyTQSbEF0ykMu4XzL1P9vmK1D1hx2dolJEymsMUt41Hh65qlEZSO6W5CAZMkrf6jktFK
    REPO_NAME: AgB0aQ5I7Uqn65J4/heoRnSIltxWjy1udkursDhiy/WLQSG21kQqsZbcVvB0rSpG8ERlkJQQc9aKpFsr4gmZ66k0CDpWqkjxjRmz03faCNThHfdyxOHbI43pEPl/zXHcy6R0IuqeLapacgApQQzF7wY9tEDBRGcLLlzVoXOhtB1Q2SQe9ulLC4QcxPHiTRVmEkARDTpdIoMDT9Q2/FvzNZQPZlOgrkoMWqBfuUcL0JY4jFPonbp5ix0mQNdg8tiI0QJ9jveutgfROHkm5G62OHSCzRabl8yD5NjObRmrUs7FRupTn8ezzDoRCDNXS7WVgEsP9vFcoL7L28sA8KBMK+W7IyStFats7zT0vJkZ/p1f/FGru1C+Vhb+dxyOPIHFn79EBEayL4NKs2tGEH7IVELwSv+XT44DhaYQ8jgBLLLV69M1fJi3A5pT2t0yqT84AngMHRE+6AmIpyoJfXM3EDL3koFi2lwL5lmyrFn7U7kZrMMyIJFMFcYeUgv9Prr6wNrz0VffYpqBOVnImm9l1Q8WmM2hxSH//SVCFPIDZe1VWigi7YChRKjvTjdYnPupB/bJWGJFnBBdMr7jW5Ye6aoFgMFlXryi4TrMvxLGh/O4AqwMdt7iuYM70T/yncodJdBIn0z2j/CPkWSeoi6QcJ2l/qBN/8C2mgXKPDko4LRhGeoUYY3y+E5+A5PpAWsGgxGhUskqZ8HkT9TzALTuW2pTNSJlSxc=
    TZ: AgBWRgvZm0EW5b8bXINIHUG2n4rGd1vAcSEcr9L9Wpc9c8L0q+yL6hVHv2jZ46r24lFScDGYLNdrXeHfOT0tMd19xr5ZBoRe1eNFnjX9erlVtZo5zDBLbqc6WouSCYIES1Bffj1VzHTijeXu3C51e3shTxoDS1o8dLOPSpS3VZKW/U0pPhDcTmE8T1Oa+UuN/hqeUa4QU2XaIyxlobL2br3rr63fLSqhVPwnFocejEITKuA8YNxbJes6zqFoBaBH2KdV87phbx5V7UdE0ieJHB8xJSGcxLSkauT/2x71/VccPd8l8BhqQCNWRJZwLuUX037bgk3J1pawjsuGtCtc9GzZYkJ9J2Ess//3zk4OeSC25pGKk2W0X917sn3baAsonoCMR+HZqvCSwwIO3zz+h0F/9doa36gyBP7oSUnmXqz3Wx+IyNz6nDftT7m5kQ3pz4BCptqV6YKa1mpwydxhQtd+u1LCpcNYnNtgByZ+aqwi1sEq2p7RjVEhv93pdFUVYzBUVo0Taids3c1eGrBGWFBFXEWNwhyd3OvuIi2H2SzAsq7vyZXSQ/nUuLnGSou2Ah5UQcGbetgekX9JbRlrJ0En7kHp6UipxCv4K7GyW4Z/zV73FNHIYOcY4F4K2jFcxROKTwKoFim8bCGoPDdrpm90oior47kRO1Uspxx65WFjt6aYt8uXcnwGkGT8HoY1fokAHPSlyNum7oObRieE
    VOLUME_PATH: AgA02qcwOF8w5Zx6L5N2saOpYH2sYhvY38Zw6AR5ETV1cUFM2zEtxCWOeFzxsHbkSMvFdmLiqa/QfVfhEx9L0VOb5WfzjlY8mKDqVnrueqiUIZ+E+S9sqoBCvIdL0zSflruVjY5YLAR8+KdwtzyTt9JbQfMzfcEe5tQEgxvWTNTc6o2aKTeU9pDHlZz0m+4YEIiyq0xM6RkZKQU0ZQDj4q15JykFjpi+k6b/Q16l2ymnCKBRXCIx5oJpdTlyyVqrfU64TdnjmCOhT17puh6FvbwHptr5ndr6Bruef6MH/TSBnjukOtarUBxAhnUfgTUYeCMnqx5vJn1nyGqRz6k2D4lsx9R6XEGuAO+1oNJdg4pAI9lptxQgRb/1md2+riHqmG32yM99SgIxf8KhjHM33b2VT2Wl/iTbQ/valVGDLseuEQs9toYxNj5nqPMyA60JxsOMa67dmR8y6PZu+ckOz91Cg1rGSTpcyBNA9vklPYMYfB+hhyZ0mANiv6SisrHJyls3x3WDi6I0NymZcS3m4X5KFa9069UFGzgVNp3JZzwAvNGwBFOSVS9SUTZTC9I/MlsBtalmuuxhyNH3htbgHstlukVCaxYgTmv9Lf9BMIoxJ09VttA7E18RWCNeYduidHSAPp5zPOKcjnHyuX9WV0n8tZmoA4RclscvJn+cE/HXKTr2GrfVycuai67A39dSwWD+tX1gFgaAgA==
  template:
    metadata:
      creationTimestamp: null
      name: flask-secret
      namespace: aqra
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secret
  namespace: aqra
spec:
  encryptedData:
    MONDODB_LOG_DIR: AgAyLMifITpos3t2MLGIF3NA0vQ4PXo+YG+7qOEjr7l+VCzpYgVxXN0jad9NQLe67G+3yXW9o4+YhDhe415lm0dkuF0CBCbD5k3wk59zjsD9R1FY7zIshz+Y1XBvz/e5YKjVcBry4XgGl2gUBpwQ/OjoKGNSEFzWk/y+dZZAodG05ZH7hFEEvfv+MXAdNalsbD8QwxE/62zmhHbHHkqiaQM5NJt1GXn43FjiugtEqEnAKWYmpu5ErJk78zKYmaTPqACPk1G4mRffKLlM91Wn0p5cPjaFgEr03xkeQnWtdhIj2Ruam1prfI7+zY58oo3O11f10NJVRHwTRTre7/RbxonIoyuLKcPtHmTQkiOi/Ha9NcEYDCEst8+Mw0EmHTS2qDzRuJX7m0vp+etdJjIZe0KdJZrw4H+z1QsiL574vw+eMiYILaUWi5PI3y3idi4D6kkR11uG1ddNix+0XcqH6fu1NP+QJiSx4tQUT4nhGPlx9qW/fdLhV5rz3Q6SwmGuDWcGYkLrmF8OrCpemdsc/brerni2pihhwAVXjBy5QEVp9drvFXDsltma/yHqg1WrFgfb2jE4xaTL8ya0hcYCO0aRsU+QqUHbkyKmTrG708dWZFiUkDPM7Bs7l28aYTbJiXdN1E5nf9Ex6WZDMTNAkQbyU9aJCaWRz3ECTyB3G6zRcWUGGHI2e5eS5JupGiePDxjA+eUrlVXB6mo=
    MONGO_INITDB_DATABASE: AgDBhqHZDq9AsnbLSejAuxcg3Y3fGw7sZCZI2Nvczh6QPrVygtEvo+pdDpWCY8dYimwBnnPQgV2jYywB4zIVLhJVD8UqEijqUbgLTUXWHhpUyy/5ZNeF0bKJ4iLTllt53TZsTuxThX6yNLUku7eL7BqXwK0XTlbz1ihIYb50F055PrjFtob7dCy3m8SWy2GR+ffxhDt1+Bx3vN0sORcUNPGG04Es0OONF7g0CqWzyjRFTMLhs67BiXb0XniU1E2FxT0SwjGFwJUtWZtNQmN0TuXNIuOsw/4y9uhnWXUsHw4B5iVNxpmExuGBYc8y5LJwZZfptbaEetYZg6BZRg/d5d3Q5/oqACW8Xm5z7suHVOF+PVtichNOiRCrxv/NubkHJoOjFys6Sen54/2oosgKiFo/QucYGwnwJ5H0C3OxYh9+SqmlxW1zfhpbIfn3SkM17bUIaTi25x9QVCAn0mefKhcsApHcZTw3p3pNJ9k8BpJwZsM4xr7tijw8liLQL/pfFaEqhZg/KBz25KB7lRpbuHlDFebKxvOe6Zc6ajX8Vw3JV6Z8aBTmDiWKQ6zn2kA5kvzBKxiJbcI48d2Oyez9ePBWhx9BRFXzCet8vbw8TFWeEz03hx4G6tIluEqe1Dk5UK7lD+yJgtg3Sph1qHa57cPcnxQoAiBjII/lADogf3341OPLXQyxgICLfewXzlpG4c7mjoW1NUduYMfo0g==
    MONGO_INITDB_ROOT_PASSWORD: AgBRbUwZPzxwCuMCjPOvT7PgTjsHDNirmF4pkF9+3ptWcegZI2INKXTv+4ol/IdbcuHUSTegI8LPM/gjm57m5WJts2gPh9oy4R2CRHA5h3nJkaiPYgClhU5d2YmcKG2S+TH86dz6SazTpzKr0zU6Tg7L8QZ8ZzLzj3duB9zbFd/fvWb20oknAjbNeDjhgI8SARZp5keuExZ2XzXzXR0Jmte/dxX8Mdpm85DpsztzNu16UPITLDDyTWnApniLRQ808nB1cghx6NkHMTljGcF2pV2Ufrez3gHLv+o91gF3w6CdwYnz19McLMMFU+WR4f5JM00/VxFJj6wVo43U6pbXKi29mqLGzRBF3perHzwSe3dBjyexNB06335avS+nudCJ+KcqILbXDOWZH45A7lKqMdJxjx6Q/s85CF31xHJAYJPxx15huyeJAUrvrKgt3toZFUSfqQnZFT8RF+hht00PU8Sb5Hqrf10x1M6G/lc/WPLq/3IJT4CVzaoMOXiiEwm7A8uVQw2NLkC1qDjmCKHjJen/2J+G5dEF3R3m0Mmh1YK9u2XbDAMP1SyXc3+iAYXqgFOycpZMdrT6dhsX9AM3T3ObGzwV1aYajsuvkT36fZUF+KXhhuSBb6lb8t39IA0XT5xJULv66uMIrzMjCUSAujV2wc8hEoLxX9T4cRyzw5kWm7RMwom7fKYGF/V/wzVfduoAzToBziiQb8u84CAaD2U=
    MONGO_INITDB_ROOT_USERNAME: AgApczMsWTRVXlGVn8MEQEQmyCJHmR20bcctAGVLPZPLUQ0Abky66g1DX7joESG2OUR58DI4t+WYD4CkMCK509Vyz7SZYpfgB38a8CraEJFX8LUuuI2/T0qzQrW4gtd0Z1MY2BhSDWLjUdrIZtuzfgO1sBp9E0w82P78j0XUxTmdvkXPaW7wYp55u6k3UCifl5V6zsTWOrOm8y4OJZN1ms1fPDyDkSvv/9eL8GpZGD3HeXpg/qWYKwQm+gFo7CEkD5pMVEWsc15n7gIio2u2DipTHTsI5R+KILWkeOHxYok9PFIwvqbqNcFsV4RDl2fEGQ3YyBygIQ9nyoopZe2624+RqchOyo9qabUrp9rK1Kc6v9RidXXTSDghC7KAoOO2xY9DkLMUsAftsNSCfZBeBY4jpZzvpG87kLdYayCP6hkEyrwVOV1bg2SYE9Ztm1TrcZyM/UM1uAGczPr4umVvy+987TVvjOlg8P+7kXAKhUVm26f58vhoTdF026fp9hnqNmrUoRnLeJZrTvQWyC3ehw5G5xOGnvwFYgLk7qWQJHbM/J2OOqkg3/9hNGFABjbVXDDBT2ymkNADkVOrOOG4FUuJ5yIz8/yb5Nb9xKKhalsK3Ud2FCmoftQPUDFdBxQvfy1ExGJTmEpzkFpmeIkHzn1Ek4RyziCZ9TcROWruzUZi5TwpQEubb+vj8FsTJPZ7b/WOzQMCydC+/lEsbw==
    MONGODB_DATA_DIR: AgAa9xA7grnMomiyYZG1wxQFcrsUqvV+LoPUSsp6v2TZvcLfzIQnsDGBkhyACKL7vetNtRexUiq6eup7QBH1b+AnTRegfI9ZZumTSeVERnSQIVbRcjDGd08MzRqF6G4qYvEnurX8wAihUNIeFvaC+G+EEwvl/vojSytRSeNU6QORWo6IMVKZyUtahRw5qacw0ntPpk3ANr9kDMBKqVugNMCaEcFz0r14WQ4/oUa1B5BS7N4QBun8624xoG4wmuSTWj7cwK0LH0rwSnVj2vG1jnNhT3oHC/f4IIZJsV5hIR94KnlUbJSl93Gmh7x8XJSKt80qhQGwqUWvJw9wrK7H+UbMipTe2UHR3KlXN51QCtf8H/DYrwCN6bEvOQ1UaqS+Xe98mRSvoE5bzLcE5X+3ZEPPEtxcJpX7afK33PI3NKpZugvkZ4SL0ecTMrSmiVEyEtUZkZ0FGCt+qj1H8UD1YVTEVvftKNgNHLYimq1anbpHNOEkNWarZkoRjm6/IGdTQ/Zm07xWB7BXdAyxDrYVS718RyBJKEcv93yc/4l2SxiQ3gOcu9Dp1Py7akVZNHsyfySdeYokfM6KFm36gwdDIMSJEBNk2E1o4DmTRuqdfGL9MBsPRVg9uXoh0tD/0Y/istSguUQdVMnJrMphFbB7TiI6Ss5RwmTndGdR4h8qZ9TOHTqcnZKiOFFvMrcUzhDjLnJG+TeCizczfg==
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: aqra
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: atrenchevski@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: atrenchevski@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: flask-ingress
  namespace: aqra
spec:
  ingressClassName: nginx
  rules:
    - host: aqra.feit.ukim.edu.mk
      http:
        paths:
          - backend:
              service:
                name: flask
                port:
                  number: 80
            path: /api
            pathType: Prefix
  tls:
    - hosts:
        - aqra.feit.ukim.edu.mk
      secretName: aqra-tls
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: aqra-network
  namespace: aqra
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/aqra-network: "true"
  podSelector:
    matchLabels:
      io.kompose.network/aqra-network: "true"