apiVersion: v1
kind: Namespace
metadata:
  name: aqra
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-sa
  namespace: aqra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronjob-cert-delete
rules:
  - apiGroups:
      - ''
      - cert-manager.io
    resources:
      - certificates
      - secrets
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cronjob-crb
roleRef:
  apiGroup: ''
  kind: ClusterRole
  name: cronjob-cert-delete
subjects:
  - kind: ServiceAccount
    name: cronjob-sa
    namespace: aqra
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker/single/docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: mongo
  name: mongo
  namespace: aqra
spec:
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: flaskdata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/aqra/api/
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: mongodata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/aqra/db
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: flaskdata-pvc
  name: flaskdata-pvc
  namespace: aqra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mongodata-pvc
  name: mongodata-pvc
  namespace: aqra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker/single/docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: mongo
  name: mongo
  namespace: aqra
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker/single/docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      labels:
        io.kompose.network/network: 'true'
        io.kompose.service: mongo
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: mongo-secret
          image: aqra_mongo
          imagePullPolicy: Never
          livenessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - db.adminCommand('ping')
            failureThreshold: 1
            initialDelaySeconds: 60
            periodSeconds: 300
            timeoutSeconds: 60
          name: mongo
          ports:
            - containerPort: 27017
          resources: { }
          volumeMounts:
            - mountPath: /data/db
              name: mongodata
      serviceAccountName: ''
      volumes:
        - name: mongodata
          persistentVolumeClaim:
            claimName: mongodata-pvc
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
  namespace: aqra
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - kubectl delete certificate aqra-tls -n aqra && kubectl delete secret aqra-tls -n aqra
              image: bitnami/kubectl:latest
              name: cronjob
          restartPolicy: OnFailure
          serviceAccountName: cronjob-sa
  schedule: 0 0 1 */2 *
  successfulJobsHistoryLimit: 1
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: flask-secret
  namespace: aqra
spec:
  encryptedData:
    APP_ENV: AgANo3Gdq/oIJGSUkcm0aw8m0LBwQ1921YF6h3UoAQk5T69OCnzoHkKZdS+BDahfkX8v6q3ij4WlbLgGXm9GYxLR6pv4Ow3CDzWTmE/ozcTw4OR5xDFB7hMgS2RIZOW/rupAfgvMWXDxXkyRy2htpRl46SxN4HgeZf1mJNSbIJy9y5neTQ0daAk1s3nwV0LHI7Y7/o/svEL4cHRtZc6ugVJznh3Y6Ed1StCJ+X5BFyvO4GI2fEwDYEUDt4k9cSV2OyOmznSyU+6MwQm1AviDKTwlRrkeKuL94/FwoniITMLxC7gBjaG6tpcvt0eLt309bWFTLZJN31UosN63YHAn/pj/0upK5Ys7aQU3RXtFvmtPiFiufPToiuMaPJQzSsnlTrzsFN/dSLq7/YreucMsJ76AB4wepK0MoG6xwwfazb0rltnf0mxvmQigJtMNt9MEAk+nWm6EY+I0DtDyll5jvOhawAZFkbzSebj355Am8TixfZdu0077xX0HbrpArR8DRYSrfNTxI7ZUTAySEg1HA0zwZdoLTuM1srUqAAtiOvzh08v9901j2yhWrt5ub5FELq+pbUDMIZBajnNrN1jwVehYyvOO63fDXrY+NmG4V72SLJD9gxvL+R4oNtkp0hjZz2xEQ8ndb6l6nUr01DKdFPKkpirsLY7xWFZYebuzZzPqO6dTmn+CmlTY1QqGeV+c73ZP4ayR/pBmZLnj
    DARK_SKY_TOKEN: AgBLgYhuu2ysbtJqEtaPXo0eU6NlXbjpAkqq6b6m8OugsCPlFI+4cFTZT3PXi7+9xznNZVs7QPlcOVUaZaY6PyCnkFrIrj9uqvjVmOiVSt/g/trrILmDN4RfOD/xKCC+5oJr+DrJVOa0/J6NSM8e468TGUVQe9D0JYYXEYv2ZBMKLmfvVi/aBHhywSyZfCZoIsEZPTEsCk/rSucwB3Lbi13pF7FLTai/dnxIcJ018OSJpleZI7Z8jjNHXJfSP1qRPvJQE5QGD9pPOxoqdXCXDlBPtPpVLYuQrtsE6F9DtLrIM6T27/znOu7i6y8FgvDxzhXuXdx0R9kGMupndYbp6H+ZNVSLNZLUr8SgS3i3pAqTY4AS14qBF6NC1OXQUTzxE7+mPkegO616k+KtN3ATFFl7YsxkpA6hz07whwPmlLY4VtCy3i/UQD5RY4p5Rn8anZnr/UH66Zp03V6XSR09Q0B0w8fvI1e/v5+UHtU0+SvVmDuFkKppVohB0XxxZNL8JFfhX+HppASls7hLBuM6kEkw2aUKVR/3f4Xsc7K+Xdjoy3OR4VtYu1nSSSmrcK3cSrpdEHQq06irUwA5U6Ig6oF/lxL5Dh2FCwHApVdZOQorKJ2BcDWze7QDYx2Dv/P6ikvUlxK8pLPZxcJz3kFyZyWTDHGmWeE7lllbP6MwhQVf/QxudiyHuBdX4/f/kSaql0EAm+jKThiAcWg3friSQq/VCARGl/nRvywNoy6STP4Kxg==
    GITHUB_TOKEN: AgBC9Ihap5xo1/02pK/3rirKIDtW4lTo53bypZOhHZuTEkbkYUnL/ISofl4jCFVTmBqLwk1yw03Bzv8QTtQuXttYhS+DWXuWR7+b+8KOwuCXsmTA2pqn18ih/e7v0YGxaNI8AmjriCqiBcww56dR9omeV7cC6y4P67+izzM8d7SXxYfTV/DghuttsIxj1OU2hcQ1U6YcOIsBdUkSwQA/Wcm8b1w75ohNtKDq4fvlvEqEw8jTXM0vyaDvJMSUuERxHOKIghaPRkz2VbZtfxtOXj55pa2hUjD2GBSJrctbth+OcUXH9AOXkWZDcuQpFthrH6bEh2RYEZaVVSogskky8UqbprCZXjmgdTvtb3RkJRJ/C4GMm/QW0v5yrKI5y9KqzkBjxr17H6YNUqJ2Di7U8B4PQYKxpqAs61AIBhRkbFF58X550m9HlTYVlvzD+7Uq4L8WeJ4x/5F/f8yGKYQ0HSeUwK0q/100yAIsd4zvX43RxpRBDBgujXS20UrfGAfFrxvLIMXcmMubd5pKgNVxIUv6FT/R5e0kjmc00Wwv3h1hGFUHK+yQpMxj1BZpo+VHt0QsR5gYtw+R8rNbctcEges5ZYBSfNfocUzY7a9QR2rlbEm0EZnIEGubGLrfg9Ap/8LT6PkfsUMMndvCg7YjZXh9sNaD6Kx0U1c7X0O+W2Yozue1flcOtAx//dxy9XohnrONFOw7qf+eAugXENMBa37R92BX+UnJeBvDq8jp5LbY9mYPTBUfjiTr
    MONGO_DATABASE: AgAqIWUja4YhtvYhj3txEVxWzGXAucKGO8Aay4NN7wc2pYgfaZrqnyDPwfsCLSfvj4GS70ul0jwx3FZ9FhHpTXGbbFB/7aa16z0vbzVszMINUxDLWbS6fUT9o8cCUkc/Gzw9HIzXOMrcztZuLhUnrFD7V/FzrxSguhDfk7VAg9PO5lrRK/8/C3luJLc4gKzUVCLXvm5G3LQqZ+ogULFhc/e5p72WCONKDfzLpNiagfc/qxnrm07YzGx/pTXv6QgNoqDHJbCTcyx8ZUPalNtIuegU2/rlPcBj1J5UuIismfnpL/UjzWp1yJlS/Qg0V7BLDqYsX/7xcVIJzwWb9161kWnxg2PYU20YtRulvFi43JpTXtnJMaYAqeaMbZaORsWEF2fsV3rkCLYx0hWS8bYiuw94Ku4tGoo3hAZy9jt0xWRD2Mosr+G7SDVM0ir9HuPAFp70SLl0F4Nq0g2/q1HUrlTBi8MG8+mspP0kj0wE1hyY/9ZFYlQ6TVMWxEDNL7PB+FSF8WvhBBS7cAYthNm4qY7ZhqR9EP+ctl/kLakHd9D1dA7+ANSfA7NlEI0rqyVkMZf5cwTtVp/9toili3osWTYC8Rw4ODDUpQJY5FjSRuOoTGI3cMCnVJ4BbjlZaRfaQz2WBFO7jjdQVWps6SAjUQFHF5LAa/F27cbqVG2fOrvES+jnOuB1y/eog/NjFTeXJsdq8XCaAbQxj4pfdw==
    MONGO_PASSWORD: AgBIZAMN/IUeOrOK7aArWhqqW/lXvmT12NcLJtOwKQnNA3xWeg1shggXyPRelUdcjzJgAcGdn/d1v8GnYFx9Os5pI2GfQIcD+DbF8Lu8/UZ8nsyQRdPe4CMqFXlda10R8gAhObCVGxz1Jg5c/DcUvxa0wnFoyO2uRdIl37X+QjKoK/owWORmsPDhvNE7/3szIvupXEXD3cGSVK1XsP3TkrAjydIASv22jmjYlErvsJxr6/lYd/k9JGX9EelgCEijdMg2CPENy4KN5aI+Bj+AIv91/YhXodauuJabPJeAzn1nJaqQkn27bW7lFcNMacLjjR2ibSKSOBmfpnnLw7r8Sr5nPOrM9Re0jR9g5YIhnWKPSFK0lEwEQKl5GAuYWVKHA1J1bC5r4p7TLqlgkreYUxQHVzARMVRBVI25Oe25eXezKeQIuB6APk//yz9OnmPLrgw2QgzMYC0ONVcmQRQPo3hlfAgVDhawlFX0Wp+FWl3MmqfxZGcxCAr9KttTxM0IpH3o6FJiece7G4zCp5aXj7QDzrCmnN4RKcB+q5FBdBsOzk3+U8hLgD2XrzybLlpLOsbuGUZRO7MfeOhZ/rbqBQVyhSsdrKmQUR+NkEaqbkswbwFTBVBW1oEGntPg0lEtt8L9AVXvtzp8P96alK/PsN0M5BaqLmrJ3Yjn2HzzzptqZvdtnHbuwcTwKgE/g+X3i0CnXoWkzQVSV+mcXLne1eo=
    MONGO_USERNAME: AgAoZkgiCo9umUTR1O/vhCeJIWdx5Uth/80Y4ZH/1F7+g22xoolIKTUzhi1TxE+wh+xm7O5x7j4+K1A1OpU4VRBkICQRTuVWFSBVQSluaJgqn3cTaxCvX91DfyrGOseq2rok358AdYFUeOAci6+fhd4zeTA6+ptBau5CcHEED+OwkM9NF6/2Jabz6rKGD2ZdriVtSzyHQHm3aa2DX1JcTyrYxSYa86f+oqTlnIawt3aWaUJgx23qZj3tcuupI9bpgs6IvlS40j9RMGkAEdjqYl86PNtXyO36fRFdSvCFG7NylAb8P7VRy2sV7qmmo54gZdwn7gKEB0majZer4fLDnmYPEZRdX9FUi1ygd2RFZc7VCxK6xHcZTTObQv/rHvuhlja1aVaX2q7sBrcJ+c/3aBmw9POD7PpH6Apge3QxAtHp3tTJOYSm5LcPPO11i9Ogfzdef46DuUXxMvwLHxMsZu4G24oB1SNiNkzs9AsgGsulBvpDFMG4+DuGU7we4nWTkuWCSylmOSAwVuQ682Wr6PI0MIzk27mpIlf1VVyFC/MxMwiBkZafiRVd4uncHUncbBml4ziZgI2L9rY6G6cQQuKGwX8U4ul4O3P3sI6ksAT/fmHZ9QdMoQwdc72FIvU3wyKTGomNiP2/a2PSo99KyZU89HFdvY8lqTFD7FBbsZZVK9aMEmumEO4O3clRZirpIma1RZkT54Cg9tm/yw==
    MONGODB_CONNECTION: AgBYWpi4wnmffDtjFB/smar0ZtvrQ6yGnY10p1MxH1Mka1AqCBqXpaRg49c8s+2rcrt6JsKLnDrqQYJ96ChrZidX2YqNauKpEcXmHOpoIaRpH5K/ZdDSbdQthM33SyHhTJqfJlvtAYoOMsTKl+yhSlubvz1u03sxI5tef33AMU83q8OLbuV3HzdDg2tYog8C0y8OODmIjOj8y/AzWGtGOSBpD6zyECez5m9IBXQJo5LfwI7Z+MMXRUw1eIRByRbzvXJX2a1ePfffDYbh7hxiVfVF41otEYBFrUj20ZF/i4gLCKP+at5+kQcpnnmflUapwWyIRm7Wd1SX5nQaIvvdaUIHn4pradwnbse6wmr66+LT8qE5fSSMdeXjVHG30j3/ZMZUx5jX8Kkv/ZdoctQPYhyp+MF/pIsHBT4Od5SantxlXjgfgvcTOd8RHWDvsWDnBbywOlIPVp0SECLtVb+mgBSrQM+kMlGqil2DJoozzBeB4D4yKg2B65A+0TM5UBdP/eXvgzLLyNHJmiDpT/81ey3KTBBMz1USG0AFk4h2bpm+rVFonG4k4RmypLLif2jwV9SQTqSAOkxoUW5nSrSco80Lf59SncpcfVFsFL1cgXmNsr7DkwgHaPYaMYLO1qn3fn2wK4FXG68bgs+OYbqefAqxk4PWviNlp6X6b0wdyo5Vx5ILmmMmpQlm0aRLePmHqVzBrlriKEhF
    MONGODB_HOSTNAME: AgBf+gZCYkhTCwrP1eIxlyiCVh/dIe4qwABBkomUsh+YvGR23Zcwh8XcPUVDoOkWx/oFVOk28MgwNqXK8wsgO9Pd29EkBihuyUY+bl+CiXn0G+J5ubZWMMWOjW15jZ0LKPm+qXLg60OJDClbNBB30/uql9X1vIjUJtihiAJ0ULhJtDhW8rM+0F1LLjp6TeIcppSqynOXjht8fZKgp777Wvhiyfuu+AFkSqKgNkAWRGLdnfwN94hPNI2RHc9/32YMd9GOw3FF5/aoFFdHuOMNO9l9w6Y/V0BHeYUxGWCs31knRwzb8Y9Id/MBeSbMAGovcaZJhh5F26yIa4ohKTmuxpWQzpKwzDkXKOlmBNriuI4GQtn1gFJhM7QIX9pNRzTmJmyAMIMydn7n/7TUV/iZStwuCWxFQdThRrAzVb5KojuVsI1218vpakK0W21gM+q/IcxqIyzjJ14lo7hqlcccfyvG/5TI/pJUhAvKAAvdQ2RAlck0IMz5Ld2yeeraU+OrWEEknqZnPZ6QeF2aI9mGnumxry9ypQ1P4jQy93mpPX7ri1UA8kcWYNsKn17Y3N1OenNfa9egYLUVPP181aGYKcXlFcA69jynBqQI86nJ3GWu+hFDWo17JQoy+82G0LxwRSIPVhkHOL3AsBnXsiqysLiKru0r235K+01qKBnftll2sVE0+QwamwYdGFvwoDahm19L3R+wg1rvO0mjNw==
    OPEN_WEATHER_TOKEN: AgBZATnGC5cxP6v2wuZtEKBqWsWnJfNSGrJ3sPA2fnjN0s0DU17RTCIZaOGbrX2l7KJqd+hq6UK7JFhYVM91dJSseQkquJFrTx22S07T1xSuM8hyVaumkPBAXjfwNd6rK8CXcPE2EOTLMTBIxZ7SoHJDZFt5bMsYJoJNkvE0GTe9xdb28DfxYnBxH4KqaeWDTQQM4uleViwTNljfD2DWSUOiO6yzEJ9impNNwdcFBmJE0j0mAQzyqornfYaH4I9cag+mOHPrCy5eSRdQL/df8KXyqvE+bHOFY7gVP8ojrFGyaiQcl4Q34Dai6+U1sacAr0ZnCwwVVzgq+KOwQQcSBrOoFqzjznGN6asvHr8IBOdJZe1CWgXFXPIL2Bwg1nrFtwlLmsaEr/kBnGo+Jy74RVAa0AevAvKg0Qm7aymt4jdhYMtqVajxvf8CBz7sFcktDbHyJvcWM73Vq8X09/pE8s1NxybjBSeX4a2tA+4W4N1ALZ201Jelv0eEe+Bt/aiRLgj9otLojxem2usUl8fXk4S12EvLoVJ/95E04DfPPWwrRS9XkvrJT7kdEwiUoM0s5XB1Y7E9ft1C4jkPgDoexQ2U7HDBghAtXYmCgfpFWCX6f3BtWWYuWNF7S9NFL/dW1CMW/426uolKHU8xD9l62zwkcLYSWRGl3YgOt1Q5G7psNJuwbPUP8fmVALG+Q2YlSC9LKaBfefZjlzLuMZjtG/BHdt5L0daOepTSNy5GkPWQ1A==
    PYTHONPATH: AgCSfj+xo9+icuWAyXk/UsWWJ9+mPxRk9cgQ0GqyroefmupB76HWZrMTaWcdApXh+vwBRWne72fZOMxjFw3rsF9a2qCSEjd3oVmC8WLj8dbP9+DGvZYMwqx/meL52EaWCNRs0sY+4pvsQ9X9crwiHYhevH+Iax0GvibczQDm8KxrsUap2ESBttVdc/g0E6l1qjgS54ZME9NF0XYUSx/FA4MVzdXCC/fyolCA+XasbhrcUsltBeriRXDDNdVCpvt3CdPWO/sHVxL3rZ0EyNOeBXMbLp/yfULzxAzIzFaiR8S3pw6hNadFiOMjsZ3i1O5EoS1zui64lhplTQiSMh/AO4WmlTMQw0zIL4YiK8eOkjQE3gfmzQAWwhox1XLbIIbx7DbOQM0fRNe6IPqnKbcslfW5ZJezunKFuBu5xNVw2iqSZZYzFnsJxlCE8BxWvZnN3HidNIz/bKPB3HieZxKY/BkRMDYK/eOHI2ESl2AQsD524QTcV8SjXVn856lvhYxu5OluHF4yD9EZUMu7xkXg1MeZL2Y50WL2ts5ZYfsgsjTaxWlKTVZTs/NoBFNcl+whjWbAFzw2TGfQV9OaqW5baa4T/tNqRK1VM5gT96GFMBSGSsWwywEii6AKULAeTp6XVuVPVhwS0CZKrCeJJNDTtzI4tRcWvBWO7U23URbKgeucRKx2Mj0DKDAVWSLkoJ0x/1OjngZb
    REPO_NAME: AgBt0SqUlX7oaubTgNN2tME6f00bxQ3f9J0Y7Aakxi0gU90eu05+XPUpRg7W412C/fwVoBtqwyXKb+dPS43oKh9fXrEXrOAeQqkBdWvuYeH/tRDVfS0VII0n6/nImQNTQ0NFM77+w2OQn/Z8zM6yAov9uJOciHJWtp6MiuUMZJ6ACGwhXHwawRAxW2so7FOiZNfLsZG0w3a1Cqpflsh1lfq6Z+zFMvT08RXDg2NA3TFltCqOy7QWFWBW1oC6z70fuGVWDzLDUDVoInHqZpN2sJXNgu+9OAo1sOmqp15J79iM2tldB8BJEnt+2GSEtkHJwyMqmTmMJ7jMQdQZoi8p0MBtzVBYAslnj2G+Ss76yaGb4RlFMnK4jH7Pog/lAD/wekXTP66ZGodxqbSOtlywModmFNCdQGpHetjG/ljuBdo9+uSkvUfSXAGbSnCq7E3zxjXIm184JgV1sPSZ4Xa59z/sNyE4ko2nAg5lTVRSqCkgwtKAZWPWaUNF9qEO8H99ienSu+5gGO08IbtRi76E0YMRF1vEC+VQtap6uwTwgHCkKfDqDQrkM+O8VS3NU4GXJz6oWr2K66H8RN1S83aWq58VeomEQPIHARssqv/bOXRJsUj69yuhjuq7nTmgmA8PD00XNiKw1ln6XInnVVYXckjOw6ciio+8ciAjup5q2Rol1jIMwzbAKv7pN+gP39Kwde0PjY+PtoqfLoxfBvqld7mjZgen+m0=
    TZ: AgCcYaX/DIuY5UJ3BjuTQpOmuPbRBpP/mYKiv7aRHrCxrKcmn40ItRFp5L/zZ4Tpyz+NMDkIzx8o0oSF0jCGnChNc9cnyj5CRmB1NzGEVKf0NhFd0eIHUbIG3w+9T51QGjQ2kKC+RdT95bm0v93H0RYKLOGNTow1v+B1DOMvaWU1HT+19+Sr+48OR9NGQ5ZaPXcnU6oWlov3JoUL+m+0W5kMMNP8Sw4ObzAE7/y5NyMRrCdLQ0KeBmLpvTifigvWfCsfZScbuEke4TIrW/Fj4JqQ8BU6O7aZYDxMXEYGxaeR1fLHUkdZZv2qgeBY0RcOLdstPxzR3+yiqnFcq3LXGg87souECaiDrM6D5IEya+d/xMcACSIuhKOjX+mNtZo+dVw7HLu92J5gN98ieSJI7dj3N77RrrfL51o+MXuNt6aj6jhs0nMrT6T8C9kd1o8SkIfJcltjr5J0ehcyLcOHDnV2LP9NBbwTwkYd2ECBFOHOiOz48yq8m1gXcZ+6lrRbstb6gy1oJJM1xyJbddxRUTqFz1fqyQlRIN1jIJyT4d7qI8HZogdQhw670NRURtGGKyctc3v7VRhAvbCxt6AsoUsq/pxBMdh2gq4QKRsEwkxmLRX9Wx/r0kv3v18lemO3UCNmtO5c9RaVIISUERgVEPe+6BI0b+Wx1Ph9K5ybLnOqYxxzunK2/zWcBEjtm3p9I3qCAiRecRBsEYs/YOUE
    VOLUME_PATH: AgBJxoNjJXOkp2oNMfm/8I8XuwMhwNVnj9AleKvMBghrNxWoG5v1hi44N/LScdNCA5/MmYoKtBU0rFq+BWX7eYqblmbfovBz0f7kS6MO0Z09mkMrnHPwXCk7TB9kxMTmF3JnRJObopIvHPQvYA3Kvy4f46AS0KNDRtn1hKUFOKyLMOW9+mF/9lZIWGh37iimpX+7db+BpMqZQzbfnhw4+CDBB4/Ly9dEQBGrGpp9Yiu9/6km1fcg+1/3s5forP0qpoo+MYLM+p4z6WSdovKpfrHyTZlV8W9hROUAgL0FZ+16fGYCQ8nqxgPGQvMvQ8lL6qCh3gkw7sAntEDxwoBAXBCHZ6Uei/ze2CWwAHL1oTnex3CoEm1bb+U2Kzrc6CF8d2j9kJBJ1gP+yDA8p61iQ/vcXfn5/miR9wFuB0gwK52p75voCes5fLpyiJ2wUoRAiSWwt5gEYhMrVqqzk7t0BwsZvek5nr9PvUmf06wXpsOPbUU1adC13onUXwI2GbXTlsxeE3ZV71CH5ihpgXrDaHJhGmd9mZm+MCvW7d5E3us/gxxWCffO6I2DmOi11GeHNTKYboAHXdk33GWmbV4v7j2qou6kJax/uGoUJAK/TRQP/bQIZ1RUWIRKhEolCgCLor064Zs+Vtuvkh6r4OPFceZLf/BPm3yIHAadtvi5TUB05VVYVEAR+/AqT7R1Wk81iHkdG0ZxGSOdlw==
  template:
    metadata:
      creationTimestamp: null
      name: flask-secret
      namespace: aqra
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secret
  namespace: aqra
spec:
  encryptedData:
    MONDODB_LOG_DIR: AgCsU4+RjIWVRm8x2p9qe5DcQ12Qtbu1aSI+1loEVg4iCjZJAGB31v+JywqhnPfpCL40zaFboROoROY2Y7Cqrn+PB7opHNz95bj0b6VzmvSK6QIvvRuDsR4uEm5VeVYJWH9rkF4Vm4kVj/EMUJHZgj4F/we7I/BVFcZU/QqED1jVqe/GAVopmwUEOxZaaxAoIUu+cMnjRHf+0ZowN/NPpYMk0TQn1Wb2kYuS99J+UE46PlNoCU8d1bodLK61DAHmyD+43OGM9IZD+RisxE8JZS0gYJ2SEElkSEGm68O2qpRtGcvqp1pM9+c9OGCzJ/729dYwfps9OTaJv3ALM625HPBmqtS/36dnOdgSL0rh7uk9lXdBJgq/3CCKpVh3rROUyzoiwmBzmYl7VQcm8vK93YszkP/LENGJKi5Egr/LdkezxM6dsZ0oQAILECQo0B9wk45Rj4+q3nlv5Qv1j7FyCAT6dR/Z8JmSooXcqZ7HCvkMoEWVDoiSOihDIoFd+cOcT8wMIx4mKDpZmz4pmRe+s8IYtdR/8k+8d3EVrMfuFOIM+7Xc2pzYPJzLGxrPZrNI4y46/qTpbYML+wWMZUumJ9/pNRj43VNjIvP1wK31SesrKjnuqHLELLnY1t4ewaBEp93GTjAYiJadIZ+NMvCENb7onS0NKDrTE5ujWRKd2NuZb10dqFlVVxqjbeQKYnex0ekLpo05DRZv7W8=
    MONGO_INITDB_DATABASE: AgCgTarw4T8VTe9N4TV34U/owXHwo68rgu49+hfO+UNPgez0ynkXnpaa7qoLyiJayISgH7RzMx0UZsUiKjXu4Kdsf7HGpE00OlHXR9aVnIMVEXZHb2bNa/6MtmGCx3bprq4FG6+B3uIeVxqcby/n2g7LByz+GTsMmzMe+6cpXvmM05PyICrZsjEJOQqQ11Nj48sIor1J7JCFGhckwu1PdZDTuzsx5Ei5xXa5al3WuiUHAvZurgHiQ2y8d3gzoMgd8XC3oe7gr1yda3VcKBOESTxKS4X+iKokeDaS7fKziQSFUT6zPA9xEg9Wr0R4Sw1LXw4dBfvJK4DQdgwFf4II7K2L456YYTi3C1/LShGtMifcGgJRGl+ZcNnPHDgJhA9QlsUhunVUHHapnrL3xpFvFxI6dFUPpyMPmd41I4tvHLnNl5XPQPD6/SU8aiHUD5jU9JVPk5XconGGBq/NJZRniPGAnvNdor+xuZHdfM3wQ1DwWjeMFVttnCMESEqKDb/7LyZ3mnfPyt5R4I701OYrrCr/Ovho/BfUIjk4BQY8wOaqRlUnqaJaX1ZktOrngiuCW2nkAA8j8upFMWwOZD3AF6bqg8dGb9AzITvX4qimLXmI/VduEf3gGqBN9WFEBCxE9YI45KZtaU6Y7l1oppP/5/BFE7JnaAbqywVGoZy/AzY0GqXJ+Nu9agVfaRxlFudNexYYKtHHGRFxj3kcNQ==
    MONGO_INITDB_ROOT_PASSWORD: AgAUtqPmhUEab4GTCLJxjqEzJlXMkJp0ZVRc9jWruvHztHhImCHmetcPFpQOiJrW2YIQRcpyPBtKZNBNYR7Xknwj992hJgtogXcG5ai40NVKTW9KopEx0PVesoel1s5FPRptiR/l27ONhRpDjr080j8gelrqR+LdmKDjNZhJxQB5/XrNQWqF/EJM0MALVHOPQriTHtqdwRb7n863AnskW6ikQFTxrdeYy1jM3nuvcH9qk47aTRq/gF2NpogwPnTa7NhY7rthLD/FmReXdvraJU4RuGqi+dCQA9+L4dzc/IBQoJvkQxzafALTABnOr1QWMjTGp3+FBYUEKPoBPycklaJTrEV8Gy/6CBuZNq7jeeaXoYlhVi86fJ6poU7T1RFcbwlPfx/bOTAdBf7ISpjRKIriGdUtz78WMLvP49JGDQ8LTIjRCNsY/aftB1jFUz8WLfrqKj0YahzBDmmSZ+qs9M4Hso67yEKMO2B54SpzgulpYEN9gL1tSasDmFcX0HCAUr/4MQGPuWloCDGJcjVSkNWxW2pIwcI9iBT50mFH3FeZ3jKgz4Cp9BkSmZK3fnkdUD0vrC43x1wh+NVwst8Dqvxu+KPBX31U5OeLy5OBhoq/SzjLoCwiMRLEcdbjUyaPPTawdZSgDCkCD0yqcH72iJB5MrT9TcelRiA/AWyjP7YyHUjUYp2N+xJ9U8+U52hQG+mSc6n8obn0rLihFCsPRUM=
    MONGO_INITDB_ROOT_USERNAME: AgABVS0UfIpM+E5M+xVx8e6hRFftT6oZFuMlvrfEd8tbaKh2gsTqW269tvjzYgsmPgy0a7vtiEwAWWpYS43PdWXGzg7OGk4eviQ6mJ1DVL21aHjCzd6tDVaXvh8GvAhLnbM64UadGpQFqosQ/DD2pyOML+JB2unjrhIp1gqllE9RcpT4JH/nwtfWYCJkGM235Y+B/KCnojSAaeycLS4vW1R90B6L+UCR2e/xBxjSUUrBU1kQrm51DuizMBMlJKgMMPVACBJYXRI5d1He3iGUw+X9DzkIKJfGfRfdbElFWvDUXpNsI/El1BNqctU1auz2oPlnhFtLQd8MIzNhVWyaxpi+D4k6DEdGHegiOz0Vc73tuZC5O4oxj9LbrvocRACijfHadfBWmj/BXMjhiMm+s193LslKnWnr5xll5HvQfqwm+Y81DrmmmVJhFNLcJU+QuJ6UK3TErjFcQBAf4EwE/nAzpze4uW1VFHn/1L5PHi+FUuTEV4UtsHZtORV4jsfCt0LVEofmwsncOyaEar1EZvmY0bRQmhOaXH0kojrHMx080BXvzg6/5KmCHHw40K0eiNbx9Ago3MTQtXWQqvNPqfonsak3GRLWGDu4eZgFulU2OXU61jBOwYbPmbp03NXOkv2pW749bxcYBWq05nbELUItazZgQ8CHWIqCu69U5VyE9hNJL8sEpvBNJ/vNmeaFB5blKp4APqPSRiVO9g==
    MONGODB_DATA_DIR: AgBsE12MCuBoMZgmnE+I+WG3X++joPjbT6pbZZNsN7Fs04B7FrBAfx/t62pU1ZvEZPqFGcJOYafSj5JzLwtAhOhp+0EAZThmDVqygBZiDXeQ0DHRpjgBk/SI8IAX8rnD2j2TLUwy0sQsXpzfzTECs0+iEmBXnWowS0BLzTeOtTjAkj2HlBojmgBWKDulk2+kNmDwe/7tWHGKPr4uP4aCTKwJZig8eBKxkFNuwOGmdtwcqHp/lTiflaUdM9xnLfRndrDmOa4OaTErH0XWsx1bCDXRtMitnYtIPyCWDjBMiI9Z47NdZXyg6ciMOpG+2qF42W1z4JBUiJGJZh83uYb6pfSjVJEckDqkE9lE907FaJorADWzJ6ZHJyuOTLf/anukFC7IJpW6C4Qv6oZYFEBgriuKQAAUe7bapc5jHoHz6/QLzYZXLnYVtvIvT6ZMJvWIq4sVelueLu/UgUrY5F0xbr/iWYIUyzj7BDTjND8SHK4kQFLnqQuJw241p35N+ox1BRWfr3Uo9dNpVjFSZeShzONZVlz4YBKSP3CdVqOW1bKB4RTUUN2VKiqISp9FZT/4uRd8nTuq2nntYpuWGf0ifmlaN/Rb87xcPMm9MkunD1XyHi9v4NISRNaO4IbMRUwFs24uPAYuMYarq1wq0jKfriWTBb/vQ+PspzBwLDWSGMjAvnwPMTmCvxNiUfQJJwBiEGuAL0Q0ap4A0w==
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: aqra
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: atrenchevski@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: atrenchevski@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network
  namespace: aqra
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/network: 'true'
  podSelector:
    matchLabels:
      io.kompose.network/network: 'true'