apiVersion: v1
kind: Namespace
metadata:
  name: aqra
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-sa
  namespace: aqra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronjob-cert-delete
rules:
  - apiGroups:
      - ''
      - cert-manager.io
    resources:
      - certificates
      - secrets
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cronjob-crb
roleRef:
  apiGroup: ''
  kind: ClusterRole
  name: cronjob-cert-delete
subjects:
  - kind: ServiceAccount
    name: cronjob-sa
    namespace: aqra
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mongo
  name: mongo
  namespace: aqra
spec:
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: flaskdata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: mongodata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: flaskdata-pvc
  name: flaskdata-pvc
  namespace: aqra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mongodata-pvc
  name: mongodata-pvc
  namespace: aqra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mongo
  name: mongo
  namespace: aqra
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/network: 'true'
        io.kompose.service: mongo
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: mongo-secret
          image: aqra_mongo
          imagePullPolicy: Never
          livenessProbe:
            failureThreshold: 1
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - db.adminCommand('ping')
            initialDelaySeconds: 60
            periodSeconds: 300
            timeoutSeconds: 60
          name: mongo
          ports:
            - containerPort: 27017
          resources: { }
          volumeMounts:
            - mountPath: /data/db
              name: mongodata
      serviceAccountName: ''
      volumes:
        - name: mongodata
          persistentVolumeClaim:
            claimName: mongodata-pvc
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
  namespace: aqra
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - kubectl delete certificate aqra-tls -n aqra && kubectl delete secret aqra-tls -n aqra
              image: bitnami/kubectl:latest
              name: cronjob
          restartPolicy: OnFailure
          serviceAccountName: cronjob-sa
  schedule: 0 0 1 */2 *
  successfulJobsHistoryLimit: 1
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: flask-secret
  namespace: aqra
spec:
  encryptedData:
    APP_ENV: AgAhKUz3S0ePRYB30wVk9Haq7ykP/vwZTpaZXXCarUSC7e9gYndrxoxEOlUvOLEuExoEYKORkgSQwfLeMGilD1qu8p48hNtkKJJT9kDYjIKa79AvGm/x0i6t3YJyZqV7s6Lhtz0qDc5dxOqmisFwMH4mciOoa9L16gtDeooV+gYwFH6odJbZ8qEysRrsbpyHoahZSKDPzrxMqGMUeXL8NmlbrI/pNEzP2qVMhanCaoUCcGvZYavPd08OMLLEl0BqIz1l+ZA/fxXXb4w/+k1C1k+eHIMfhB3cPsaYvAbX6LVCwvxkhHsh0UI3sdZvOh0sqh4yU18h1u8dWuBnn55+4QgezoUEqb77j8zzV04nIHvpUQmr7MCAlX7skoO9slt4D/KiHI4xxKwIgtYsjlu5P7OMa7KU3TGUK487DUVCGq96pCCjMA9kOVyCGAtnc9qGvsWYylELYz2DEKmTgzf9X4WvteCG4hfaspLxFWT80VQ9uNgB/OE38MfD6mCi5ggpD+GAGBr7c5eHhTkTsX+9ORTm3A9zLKpnAqAib7a6vb40XsXeG4D0A3Sf1kLG/dJA/waZz3/j7Mt2YokS+93saUeOLPn0XnrpUgRzek000cBdMpv7MlGJ8EXHdbaZQP9z6ayzaVzD8h5jAY8WxHIcAm1aclEYjTngTUxsZ8Eg4r8aNOn8uKwkvQAGHwafVmoj+C875SlfFtunBwQY
    DARK_SKY_TOKEN: AgC54P3t//5pAV7YoVADU06KYdXro0F2cv6W+mytazEr331SpEnezM9uZMRY5GmXGxJ51zHGLYfaOV8CYP4VRb7ATad9BQdlAN0bW8ItebItSv565qN+hw+2Kt6ddNG5CDDU/DjhPUSJO4C/mpg91/KW9v9cphiftIpI4eafRBZKBtDypm4T9Ek/zgUwoYhCozPhhwVH2SYJ7Jgt/wag6fUn+TWh4BfH+3Bv/vx9qFK/49Xs3yAJnEMJUyHbsA3jltlbjrhjhGMVL/jGdZ4EuxFXttD/Ayl3U2mQuweKf8pUrn6Y8lMzbQqvX/tDm3RLIJVZmopVGAB480W1ebaCargpC5IeTzbE63YAOeFMB8qaBrPLDN04kAcjBO3ir9C6nPm9/iUVGFi6X5J4T9AjUhvt17HinEWDMmpos0Tr3GRjwuDZcRhrTxP6loUgrvEfjALw4AsYYBrIXEy6GXGldEWnkV6T9KZ9pB+sGDAn9QREhp18gJpzb2UUZertgaGdIxvPNxRtqg5q/nLInVJU3lPE1338B867XEDQRDVePtYBRv7SHPwGTSTnQDkDUPoeevxX7A+smujUZ/O2m4edYg/n+ckdnia8Etprmg5C4u8TsNm5/jyh2EFPLG3P+ESgQgvO16j9lMKz/Wcfo0/Av48+sIh9Nub1Lrru4wddGiLUQwVOvRsNVjBbXgCH2ji+kaOwFpWxhApk7/yeINB/Bt0aqqVUsmF75wMuVv3+zpK7Hg==
    GITHUB_TOKEN: AgDAZ018dFhCvG6tM80cy0NQUh0HwYT3rKx8dSONfoI9TQVFAaGYMvBOvNOssKlPJ12m9D+3K79dDmg5iT3t1g4969H1Rrw7S2Icn2MMcxZyNHeo2sgeuFNoj1x/ilizFRJpuyk8o088S/U9iXW94avRGU/X5KWjY/QXS6e+f0kV0kEFk/pq+5fp44s4SMeDvor3Y4ZIXv6wm47EecEG3Mp9n4epk8Fr0a+Ue27KMflYFm35O6JzT6pFQMSgBWSXMZU6xDyJoVUvFF1ITgBStuLZAJoiyHzS9QPnx3GAH1PG7b4MpNS/dP8RVRs7fsqJZ/TJnJUN5U0+yyFRAPba1whL/y4TN/zTRCFLMpMgvAXyDXmSVoN5xEnznwv1CioUql/zFYV9tqEH4IJTNmZxLuvrATlJd/FmJNgPgW3civxaDhZWai39xpqgii9wQnzENn/9GFM9mTFUL2t/R82G6NCl3Ew3/Qrbd5Yx6N9U/jP0mxyEUtcuchzFm82o1jA8zGgd5EZCp8Tn/te6i0DC8k5HnpYw1ZBwlWknU0UPGZXQEgKlEJ/GxHI0S2x0ZIwqHb/1QDpMEu7tXdwBJGHxA2/d7j15hlAvR2ZtkWffLhFw0cxX7BV0AC+5h2wHqMOCBoUicS2eDqFyklBm1AfEd3e+baN4kiwBP49qRe7moyavSUyu65fiJEK9ZV1csNjeTN0LWkGY4wjwiX33SfXmBDzw23z5RDJGKKBq0bV/tidZ98txJPxQG0xG
    MONGO_DATABASE: AgCzcous9rjmHr0AmlkXHpGXrIIWEQsg57JhxoSJE0Sg1+xSzmi1RG0iFeMB1q/uVhfBg9us4KlztdBwPD0shHC782YqIJQNgMA5AkHr2I0i+ifun/riqst4kRdSAG4EbOVl+ne73OTAgbSUiIWb1r5V5jVvxJsGNQszzFEXAt3PgJlCxux39pYKmbrk1tqvCeRsJ89vCx1C0PcufGBHTWXtjxZoG8D7j331WLTHhkTFkvtgFj3CmfL+vn7T6dg+u7NG3YD8113iVy4QMtvp4+k1LljcA+LGuMddJeXTgFkKwJXcmUfHaR9ec5u+mq7HQFFTLx+G6P8RMxQgB5rFdeR2l8IJHXJtn+zk17C2cwFcCUYnMu86hsWOsxClHRjbil5gkob8FhgtELlyEg/7Nf79rrZM5YnYR7itucxZa7dYCHejnOCuiqUEpHJtpSIK4k2IB6WHQDdhPfIestfDr4b12DhAYTdxlfd+BH9Shp0Lwzi+v5Kocpr2kt3hCSEpwUqEsoKIDRcDyRtvAYJmIS6wG4LPIjZfIv7I7iUPEKVy0q4suFmAGoY/hl3n9mMAsPTOOcwTXYxFSrQacM+hBe+DMgRlyxrm0aHSoHtyONc4iqZ8J1lPucvY5NqCZnma8x/A5gnU/UqTIvKWw9YN7BPixrRMFpjoFCILhxdDvoFKSDBwMkUSplLNBfR+nX3i1ZzrtpwLa3Zwa4YjHA==
    MONGO_PASSWORD: AgCvbq1UO0wooTsuNXHuzCkKx5/BQ85F3rAzBh3CPpd6XAoFlyQqB96dbFWufa8tMmH7KvKwz8fz1Jqbpogf6ltgHGm4pi3/R/ZJifpcn2u9Gn9TZg+TEa/YWAikYEz3u9CfbBgETTc5ScSnSof1i8RHsWfU57Fthpd2glWvmZDJJDn90qpcVI3+OLMjmCjVakShWfXiLMfDxfetzgL2zMk2tjcBUXfaIKUwlrmQHhONNsGJtUEKenmXU6oO5sngdUBWE0I6N+KR034uNRXj6xlvTKaVqWiTNbwm3X8iENBIbLHttM8jfuPJRccdG8qdDZHlogvreBjTx7la84Hqjt5mnp8Mq0hpeSqJJ1LUKh3W9MoCR+w5lp+6w3U6FZe0Dv0urKbGyrwesEd2lN5nBIeY3ndx1PDFPpOtbCJZ50zRZuNa/745aPW1YPNuUi+Z+9AGB/mCRE8F1E6BhfGCxEUYAnCtH4+akn1MlV7760cl9y+NNZ0P1T5m9Grg4ivPpGYply0mutdS94CrOpK/pgnB6W4og6dEJFIDnAnaKAVvVE8Ply2JkvU+qkynY6Wg23+8jhlCbspMtK3ETVhGMZKVIPic5ln6SUyGRBcAtzOxw/NEBokio4Y37iOCd52HuEH2es4fV6KP8pG4qtexjfRQ45vzejgIFz7okElmzlwYVKX/1PNGhRR4vSGHenwMqudBl3A21uCO4YUsQ67EF4URGh+wPYrle38jlQ==
    MONGO_USERNAME: AgAzhzV8OY94t7fUL5//m2GuUIiKX4e2xfj/bse/6VzgU02ywZOia1ut9iSjfDgNiWAQDovHh6gcjCFiD0dhuAo/0xHHiPlk710HJZLFVrevdt8xnuck2481y3xPT4fhbsYNrR6Aj4l5bG3akYX5+KY5V7KhJNin6MLx0t7sAl0SrDsjMKh8fn8GxhZ1ld9qp9/eoyoaVaFPu/WpJHqsnezSFzHNCFRrumXp9egKXyIj83rYjDpIoMIHIlLpXU/LO5nZb+WTW/KdFG/7k8MXHUi6fXnUNIOmBsrcGueAPLLiNomY8lIavKuAx2VTNaVH5E1FMbIDkuBjNN+BC9ID25AvDKUrbBDPZThEN/XgxmAjW+52p2UzcXQJY0DPgmIwGrpDDYDU5eY7KnrxSdvau0kIx8TshOLOgSGD+4SwJJjbFWiN2KjSfZnT6B4/uXNhublSWGx6ysD/v/kyQkoUYrSoaWG+lKi0PH9+EwlWTkJbPASXi0ZKveJHqvGVeVINSlOCpT3884WAb9rSy2JH9SBHvq2adyGYmKDZjKYz32b4GG9maVXaKHhrc10gSXYARTiR1yN4Fl1hY4Tb+7+QvZXBWLwK4QZSQnL1kLocOazcj7AeREg6Fpr4bB0R+dUfLXZ4sY0IJCc3bp6K68rTDLi8HmxghW658bJ+vBB99AzsMVLC4IF0Y83+fZrDT7dMy9ZqBoZt4l2Y4BGzKA==
    MONGODB_CONNECTION: AgA8pqvRNzGkPe5U/dg+V5zHao0eLPj9qRx4S0bX1f+QQCoHdnZ6k0e/2Nn4Tys3+izSkQnJ6H3t68xp/V9l1xyGX2X1NP/cYHqlr9xpQWtB20eUqvCBrL7USK13YZzLkU2G1sAumMNcgLHhZhShIFfwRoOhFfSVmTcCH0F6R9+WNt2zUCA9x2IX3ioEYXgqfJCu56l/Jbe0px5Kyi0MwMuCIqgxx4idh8Q/jwVASQEgDecmnsF0J3+jgw3IYfIBlvqQeGSxtajmHa7Yb9IRaaugkWpu9IC/Z+U4eKwAETBUJZqUbGjQGykfob100QMD6iHv3n73737vT+h8Aai9PyKR1ggMOzGGZyfDVe/Ti1UKuDaLFElLWSk5VT0xQgTsQo4zRMjrYYrpsww7gR/2KlmqQgvIE367TMGv8fIjm2uMhfiNcCa7ZvdjjJwPTppk8b4ou4Q4dA15KiTEJ/mKWufgoidvrNsjszPSluIB3l/rMMvCEeppSnWNF6QhqIh0AHFKI23DAf42EkLp4p8JgqJgITJZCBUqN02PO5MC9hjPrcWuvL1VOC4MhyHLmjX+u+RpPsDkSN9JhDFxnmanaRHmcnR76umDnDXY+D03hC3ptA2h+sBoOrT3qaSiNgU+7grO/j8JrfEK1cVjPnG4c6opuHRRhP+HNe8Y8iwbDvLow3H/KBHzo49UbZI15mcJI4OH3Qty1dDr
    MONGODB_HOSTNAME: AgA/fQLKMfXxAEYfdyIoTNYrDZCtcc9fB7YJZn28ctaB4GrZDr2xr2EMmxa9aAjf7XRTf1OynQujioTkXBe20SaXjh0yLlvYta/SKpS2IzMTWgRFD8svBbU/19jd30H1pLhrmnkkE9F/pDmi6PKz5o//2yoARgumB4q6D22Z7bHxpr1GgymQb9916wHyw2B/sq86+DDO7tXoT9/4I8ubamz9pammOCvvdztsYfSTtjWfeZO5GfM27tIo5aMHpOZ5dL28x6xbQ14U6xtT3F37IYQazcQRrUsD93eoMwVGfgdtCBE/VRduoIB/lWu5+Fcel5vsVQGU6tzz5LN5grv+lN/lJ0jI+nW5wvwivcV+OB+sp+RdIAo90ratf7Pj/2macXTw+fkjSUBONniAdiNKeLlOncZHxP3oR5C0me2ZlcpZ4ysFfNDJ+zgdsSLvvRv/1thtrpqHAu1jLSZMmWdG+u5BOPjD82VMTCOSh8RzQjSv1F6Mw47br1gReQyvFBuwIZw63YcV1g5zdoOjd28MPYdgJuN4Mgub+CzvsG/U954i3XyaNb0S7jC3JwniMq8dn6X3HblXR+Xhm5RlS2QEnUHRgLrsZhbWge4q+28HWRKgN73pc22ie8701QKfJ8env9PBDWrydGrDlE4jmmMQXZUo/PBL+C7fjimqbQvsZohMWyfhCJBDKQKHEfslfjQxostWGZyejwX7SnFAew==
    OPEN_WEATHER_TOKEN: AgC0oPxj3tU0LkLHCRAkHYzs+hqStDcJShdXNUMR87ybf8M4fHvZd1KL9pxYc72Qf7o/41W+zCsopmTxD8NOv/RYWQ7xaapnlmbsJhnujXSlzL8mcaHHok+tIScYXoibvZCKSVPDl4fZ8GzWa/crXpR3V/mrmt5G2rMvWFPPcVVjmS8RgIl06tCWtajV8qYrdkA74EcOnFf8o9s7WrtNXfI4PtQgRDSuDNxDEiJ+KszyeQ0dTfs0V3mqVLxjyETYrxoh6S/6+TE7Ssd5mRNVO9JkWzogyNtHYBVbgfAtHfT/wWSRIM/uVK8rXfcd4R53JE4QUTvzKOMBwmbklKtLjTfVzHXkFHaQQwyIMrRbVHD4ok3Hre+YQhHsKJAZFwWUCJ36Fc1OA7S54Ez4hlApzJKjuwlh7+t87H5M6oz6FtJT8eyk8D0CWliYWT8h9URyu14zElFTh4Wd/LTXy5UNA6VPUXxSGOjPhQqAPBeZhPeGpegk/mHENLD4ZR+03m9ZVdhfkGmK/SxpIFvVLCRgZwuEd89xOxDY4ph36lVyv61vXOM56RTZ+0veUU2P9eozezt/1QJ6aEzbyASLDfxjqa8wqBysla2y5eoVJplg6cI78bBxUI3+F9lJrgu3BGUoSIJrn9B/PffqF5BM+UqOsVOD3ufz+a4I/LREjX/4hb9ebBRRz3TwbKRVMezW+kjcdHwX0V004dcAgAbqDDppTpS3tspYSKXgaAbXOm3REh3PUw==
    PYTHONPATH: AgCM5T5BoNIDvw/fLChAAVk/0ImQTDAAh/xCO1m9kY/Duu6c0EcdRnk8dBJN6m4b0UJeRodEaIwOY+FTtEYI0ADisnN7laLkWM6dHWNZuNMaGig77L4PXwFzZ9Nm6GYNvm6ZcqOuSJ5A2GlKXSE5QI6J9HMAwvW0ktmZO8LUcpZ4NI5A7L7Tr6YfFJ+fQ0bpfvbeNY5ZoqRktIoroir8kyqvgDCEJxR0joiMur/tlXkIlVoHwvFr1dMcp/Cx2XmVgCHWQABl+spvMJ6vWx7Gc+kkiiwRSkg6SH3H4IArYubxDBn1osixVOrBZVGAZB1HwE1xWkj2cENIpue6ROSNYIFbeWjgz4m8iNQFOxv4x7O5egvWWeSkdOTQlBvMevMpIwnV5Cmc2QLQeqZwYq3iCTKF0JacJIK1Uu1S8B+E6GktH0r8AiKDiGTbjMWg859bngsvIVxeyFNzgtmK5jKG7xmN1rYEm3mMtX/LzPAPeM9QdXp9LllO7pdUzVQSVQbdsndXTFSPS3c30UUzTwXEBdA6XSdXJwaiW7CeiQHvf2Uv4AUthINZ+dfg5TiPXLPA5wmiqS3LOcl2tXw/APihZshxe3ovhHBMLdHYuN85DtYYwwkHQheBfUL+R46iXEQp6Krkaq/4E2klwIT5s3J/w66jZ1BvEwbFYpBeNMiFSCJuG229kSvU7vIEgXiV2q8WUVMMurqL
    REPO_NAME: AgAb8s7/ftLzSgJPTtgEdGm03hTjq3S/HLOu2j1iWwPF0f3JysMSN1gZb5bs4AMFEqgg9dKymOHQR9/0wRMYEPyjh2CjNUEVqDpmGK46q10kbsC1HngJTGZkql6T81W6FwP7rwX/Tng47/vOyrHONfhdZJRrjXMdaVIu1wZPu5n2BGpk2Lz2EekncrzmhTwS/1d93qipTTviHu9PopPDjSaAOAWqftvZHIRiG4vYaZLgUYkybvRPliJSZoQjIPeM9v6fRleQTrF7WDeoMyY8B5fBOfqAdvZdP0ebFF2yazLPJ4K7Tv8455C0xBtPglaFOOfx7FlmzYg+KAkCMKyraf9gCJ4/xhxI3AIRDNrfLmN7uiTWaA9YqsGNWv5MdJ78TOhgn572rwEV/p7ZvCQ9NOX+soepDhtIJME87bTeyI8wIWaI4R9B/n3Zde43Yg2oxwNFFNdXxXDEL5DI+AQy5Jr/is2bsJGWmLlsBuDHSnbYvyTR+gOAhA7UFjQ80TXxpthBjtHMa600mwRpPwj8FGLVw9KPjx9hMhgOrOieE9FrDL+DfrbfKqkOEgyVh24QOktQT8lMwzVhcKgrvUAZAHNq8X57nPJ7acesMaGX79v5Lr2rClizIg2Ba9Lp5I+xA8RRYitul3XqRYd11Bb1/cBFd/r0qpUMNuck25zr/CM81uMJ2nq1ieDJXst2XlrYw+xemX5iF+Ubob7LDPFLofathUhU25k=
    TZ: AgBv+YZZOV0sj8FvcFNfnytCdZqHkr66jWdRKrHalbwmEdLoeeJ7oUxKLijw7sD6h6iY/yCh1VjaWFuAd8pUvBa+o0+GQyezYhuLueaVbC+r599zDQQXmdnQ34rTiYYPFBtBqkSxkuKiTlzuNDbLCN0qNmOHFHT9EEdAivrMr219noUk3L0oebcT0UzwZB4K/pgUfK5kCoU8Sw1l0MdpJSV384qKjBtnYCJANiqjQk7ckfdOLEVVY/dqf8Mg6nVbJdvgSnNW9O8LX+nRyq6e/+ywImLt7bFBR1PfpNmkOhHc0S/3TWOR0viq1GrTd7lZevXgqc04x7RCb+UiS6d2Oroqnabs04zsaC0fqboHZK1P0VI1fh/jlWtmk3kUVv+v3uncS9sGbDlj1ymKviZqLh92B029a0FyAJbg1hdmSMhYVzy6EObheHVD/dXi67Ywv97ARnXCFb3gNl9NR6y3frUfaghQ6knRN5tlmyLm5xa4tWRfoAdmMdNp8snjdMYloEshUTfOKACLHFu7Rb8EvuhT0OzrI2fmIWrQxgHfn1Zg6jAbMzTmfVnb9zqvYKnKm1nzafJuKj6hL0djEec6Q9MUI8CXsFCLlIgS//EpEI3Rtg0ctYa/ZOHyLKZdy9Wr1ysH8c9NTwgMTv8/OXvQqLKOd9NB9Ud+D7hmAnq8DsV/spObSX7We4JrqxijhvQA+WeswOIB5eOBYtKyLvYy
    VOLUME_PATH: AgCtYFPUkEKWJDGDSninpTDOAFhFXUrjCgxt+dEB5iDTEhNmjkyxAvzmhMG3DM7HNXlwjWfUFFuREeORWCwD6TxyiaQjFHAivDcM8LTzlDSKtJraOjqbtx8cZ6nb9Mccf0+Jj4WNQDKsFtcJ2xc8Us+DOVLbGn37Mtob7NheqTBnVXCpbZUD5yfIUoN5cVyx2J4vZMGSbUdQHBO5dLd+5sf9Ptcj4MLEv2X6ygoipadO8oZlYO/K1cB8BhRcH/2EyQK0Ab58bUHF4CJF3e+bFExb3BS7ZFf4ypNd3rHgRkTnbpPJZCZ7YdKyvQEhk93EN/BAoaXreNFv+NJY71fQlnM3+5QdOag4oJDi4grvCVdofDn2tg3n0Pm8OWbsRLz+KC34rSJo9AedTaimOQYKoaZs7sFywK+JbZ2ymP1G75rPNS9D3HkMISmzVez9sWMbAb/Y6nhHsWvdPxsOqC3dpBhccd8f2StNXrjnD9EleMnE+2keakLz4q+Q84jHl/AI0LZiUO1xiXlVMjx2FEKY5INg8d+x7SvD4Wd+lji0z4g/fwpBIur91JbxfYofDk19eMG8+rdNsQUQ3afPcbeeVKFyNKak/aIZaDcUkG2jZFml7zqTGWVz7O5Dfgl+Ru32yq0Owsy8hvhCNttoGoA4Tx104Z9jV97DJIHNHRC2DziiwZth+p4n2vplR336iluVZf6nw0+qEh5TUA==
  template:
    metadata:
      creationTimestamp: null
      name: flask-secret
      namespace: aqra
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secret
  namespace: aqra
spec:
  encryptedData:
    MONDODB_LOG_DIR: AgCRbhoYO4N2xN+qbdWxeJFL8a5u7QFL693JKQk/PypcHCSmw7iT8auAthYALdKJ0BSsBV3m2XOe7/MHX6rcDMSk3U1hnnRd4sil/kCkLGDmyd6IOAOo3J9DQjaXfjLCC+sTVu+vvJkpxsJ42JgWJ6DyWRi+2eP3gYV7fjgD8UvnGdGw8YSKEfBBbjrVOPTsZ243kxDsHDNhdy7U9S3o6nkYEh9qrMvv+RCqtDoyLuP+35o/XSrQdyVRWbfdQavcqIgZepXyWDAs3invOQoRcQWSNIs+wE9Njr7GccqqWHhlj46yDUW2ztfvS+VKgvStT8iP/cMIvd4Xtpeh0lkEbGT/P4S0+n7a6r/XlKO4AfO1SgWPjj8lFuphPzUvJtBW+imVayGYtOWyD4BB8oi/lvwnOAwKcblAZKJYYC6OpPrJ0Yuh8vn84Txd7lIaW8AdH3y0shoex9Jej9KXNEysmcvPRx25EJuWQxuGs4vAY93GxC8QD3Zfw3htc1WzM6RBabRxCdaJDzf9d4f1pJGv8i9bmPCJ+/72914pnU0K52hbdebJZj2pS9KcLnVxQ7bKrSzZ3R/JpCzwVye1H60oKIyBYf4YuqR4kFhGz9Pb8CRnCxiF7DgdTPvrjscxel+9RGTlINSo9WETy6w745FGfA79J9ZNNhaJI5nvtg4Hm0M6ycbpTL89e2ti4X+kneKlQDmkog97YdvKEnA=
    MONGO_INITDB_DATABASE: AgCWFYCFYFj35FUZfu2kSCYwm4BgnkcaYJdV7rFbmCdLC5JfDph+Kyvzxvig+yQm9U8FTEnB0u3qMl3cvfV3kZ8V2GYFibR2xGU0drBZRzi1k6lB+ziHtKX5R8goR1aC/JT2rNDv23VMpl/LSL8Ej5hU6SJkThGmrWlaKL1CTbhs7Z0V3EBnF/3nHqJJcDN24TjCNynBGbVt5WvPOtUh+XIAJqqw+ux+a69dWJ1+xnre3Vf3sHjLEvC1LAr6jeNw0lhjGpfmmp+OtGRJ2y1uDVikHQdEAUqpjTHIT9tKRzpUhP8ROqey+czdOavGf8cBga92Goss+5a3z1sSAsQMvmf41d7oyMVP15fI8SeTRbfKxUHwiJzMlwwHSIceTsI/0/Y25IGWrD9sXHyfVLDVYFG8hG2sjMMAdXg18TRjxIbSLvgNGaNjUp8m7f5R7orOVt2QC06Z963mcyPlk2Oplaohj/Yqdgr/brNtmm1+KwgjhH0mGzAJKhTWVtFXpS5fFf3abijxah8HMF1Sut0bNtwGf3u+CaWAMEoWmbn7n2KAL+PNbC+TSRkYRSs1sXpk6qN/BXYS6O5sIoHkP+Awun605gkUijX/5iowKFkPOz8u1gI47jAubq2LHhwg4s0JmSjKJctXCNUtXv+XHyJyJEUtrYSCNhaOwAATwH2sMX5og5KTv0nrKpV/UdD1uvvhna+CemAxzULCOlC9uA==
    MONGO_INITDB_ROOT_PASSWORD: AgBcUapnAaY297MVnrlw4zEvh52Po/JjqodLjWgPgAj5RKrcTTpiA4jsq5NoYG8a1wKKwn1d2GcqOKzxx18dQGjINEpxl10oy4HV7Y7dw9cFebuXYr88SUR/BULhJwyWVNDBFn1wsZ1NMSke04Na0Jy072fuTR+9VSqazrrPhxnwcUhN+5i614vBgZ2F9ElHBW8om7h94WXut++lB7/cG0ETnIoz4PEaLOyoODgaT5xcWGMQBl1BiPEZmdSvqF9VKLK4waKyFJHzYVz0O2jTEa3I+Ykpsk6nFW81lCoUykm3tFDAmobFWDX1mPzkAQTGTqspAEtM88ay617X99jQp3HOg0bDjAT4N/0NHh6Hqe5kr7P7PVIRjByVr6vxaCkA6KHjcwYucTINyTBeOfn5n13iM98gfLDTD7UX5e6cm8wK0RVGcn2ivoeiUJANkFHRm2OZ1ztXhRPcdkHCs+++rPtYeZNW5xZqQk1YTajm2nrmU5R55+pLd5s7dNfbqi4qwWX5DG2OL/dw6udEhZMni+gUq3OW89H+foH49XIb6HG+OHDCixFwzgOtTlbTewHnXLSONnVEFNY21IfF7KdZZLemWLNYeW1Ezremw2gwmW+QsCC3kBi7xG4KEohSmyag1ORPIQU/M+RtzFvCBOAl7foE/2E0uM220ZADOsRFFhZeD1jATPbvXe9gEilqLv1D9Hlhm5bW5x64PJyU8UvsJOnW+bULBxPxWAcY+g==
    MONGO_INITDB_ROOT_USERNAME: AgAeL+DLPSW4JW5JlwInutNUh6/wQKJTAjPo8SzQF5AzJF9rvRFwsVuaUmylNCpxTDKKVNVFs55/lzINEpf1yYc0rCaZiNHbBJf9iddfdFYXwKKVJSb6hCdnuh6OqnE9kRRjqYIKAGwXOiobw1ORKN2SaTuVfVy1oB/klrCL/y6EsJDRIxXEQbAWYH3B1L6SwBbMYWsumNplHD6phpSb6W/B90HWm4RCwrS5/XnvO1g/fBYY5Yj5Pjg6mPlWHLljqNj0g3aFlRJPu7t7mNeeUA/Ag7j0lR85tl6zs1Iw4n6jLZWuzq3YxF8dl+H6eGAdj+GXXZNkdEPNQarkqpU3ou3a7HtM0vS7vncVQPMMieKDNZOZ/CUqVvfXMaiFjL5zf1OpGjc20z3O3zrBNyulJjYRzBjSWSrdpVcnqVvJ48dMQ9pbO8V2J/AxRtmS0n9ZxoTNBadWZq1qh/yiRGRAR1jEULrDnxOJrt8j+b6goWZpWew79uc5VftvlP7Pf9EBz5VtxHNG5r8kf207+ACEvD4bjgCeDJo5iw6JG2YoexHGj4+ekZZk3WoUiKPKL/ahw7ruStZh3SM81X4fb7Q/C+bfsZan8jM34m5KUdCaWcb86xBtbnqHPk1N5eoOQUuksPAmEOTV9rDcgN/O2JJF95VIb0xyy30qomD9N0BGI5bAbCf2asCqDGl+5cnKARGlZw49j9gWvWat0AGI/A==
    MONGODB_DATA_DIR: AgAeBgTX4LZqm6PqV+9GJhzQrUM5jhKrYaUpZCTI89yo6Ffb6dnZZzg0uVQ17ao9axs7zXnrrqlvIwiUEIJX+gUqsudSxXPo1T5y4O6bigse6jO+eQB+BxcrqiVgOdTq+SeEJFUUXrjZZIVM8UhapmCF8ORMe64v5ugiey3N5adoZn022mAOyI7B6KTEFqhqJ2OsrYQX1kp0eWwJHuyOIjfjsa9y67e2By7QHXXCV18Rwoe8pvhcw8cbnGSJGQBD921dd26agdAmSVMFDq0wvcLP+XTNFbYt7OGJ0yHIQOJoJrA6wyFdjWhhKWkwU8xuWcwTNTANZkMZFhtjGOUY9hJvvauxCIqiGPYAv9068p/691Mf1An71sIX+Z6qIrO9k1nDJ2W0x42EBpMtrMXVQSn/+3kpMTwimqVq4rtvQ0Lp0bElL/22TnJ1HuZLlD6ceccKjRjqw9XvbWODne/u+9fkJFfZ3UbwwIf2TRSAsQW16kwvLs1Ao00zus+vQihgec4gNdvpuPxCDO8GykXoXt+NTF0cpHhWqfV0xVxwdI52MJekYzZV7HrUUYukQKH0HRE9uRepJhV3lG+lfvtalYkhNnKbgpEJ6FBaKizRN1JN65h1KmcCFjc6aVJN6R6e3BsLN3dbl8Xd1ZvgF8A6Ecrgl7mRwZ1S5/VJKdol8IYschXhTTOsJLez5iDbsnmpQm8egPipp2VBbQ==
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: aqra
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: atrenchevski@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: atrenchevski@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network
  namespace: aqra
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/network: 'true'
  podSelector:
    matchLabels:
      io.kompose.network/network: 'true'