apiVersion: v1
kind: Namespace
metadata:
  name: aqra
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-sa
  namespace: aqra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronjob-cert-delete
rules:
  - apiGroups:
      - ''
      - cert-manager.io
    resources:
      - certificates
      - secrets
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cronjob-crb
roleRef:
  apiGroup: ''
  kind: ClusterRole
  name: cronjob-cert-delete
subjects:
  - kind: ServiceAccount
    name: cronjob-sa
    namespace: aqra
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mongo
  name: mongo
  namespace: aqra
spec:
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: flaskdata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: mongodata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: flaskdata-pvc
  name: flaskdata-pvc
  namespace: aqra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mongodata-pvc
  name: mongodata-pvc
  namespace: aqra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mongo
  name: mongo
  namespace: aqra
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/network: 'true'
        io.kompose.service: mongo
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: mongo-secret
          image: aqra_mongo
          imagePullPolicy: Never
          livenessProbe:
            failureThreshold: 1
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - db.adminCommand('ping')
            initialDelaySeconds: 60
            periodSeconds: 300
            timeoutSeconds: 60
          name: mongo
          ports:
            - containerPort: 27017
          resources: { }
          volumeMounts:
            - mountPath: /data/db
              name: mongodata
      serviceAccountName: ''
      volumes:
        - name: mongodata
          persistentVolumeClaim:
            claimName: mongodata-pvc
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
  namespace: aqra
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - kubectl delete certificate aqra-tls -n aqra && kubectl delete secret aqra-tls -n aqra
              image: bitnami/kubectl:latest
              name: cronjob
          restartPolicy: OnFailure
          serviceAccountName: cronjob-sa
  schedule: 0 0 1 */2 *
  successfulJobsHistoryLimit: 1
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: flask-secret
  namespace: aqra
spec:
  encryptedData:
    APP_ENV: AgBkJDTjV8WZ1WKtwRuSbGT7g81tKaNOE1rtjwKWsOv+Zyamwd5JwTYIbLdGagAeXhdnDgxbsb0JZch9fWMiFfEE+Gmh5XhSIAF9rC/h0IgyBTUQ5ad8Gmy+RJ9QKVsMraPFOx+EYvtDiG8dyPSqJI7ywK8rQGYRdlGycsC3IBhAHTgv2alIbKklykFFO/Ns+N/k8Z1+FY8L69Fuwl3NCzxFk9CLk4o2qPl9HNDTZUHOLwC12yItAvlh1y3deQmPH8hbGJG1YgfPgC+caqMKZKZgpMNEuOkWa3shlCd+v+aPNwDgybW/cSXRRtYfDWvrVC8drx0CUJBxVsNcBw7SILKmm4Atw4U6KUsB/NWu+HLYGm4A3szRct8L6J3NbEMElD3P5mV2aihntWKjcWVm5JPdDalj6ZqhdpV0uw/B8iOg0eLkQFTi2SGenIJQcCPyFHIfBG90zl7LfcKfiEZuulGJ8Jylc/1Tfpc9+fqIO/qwViD2W3so+DK5lpAFfF/S4a3Mvp+jvw+EC5KakRpH3M+qf/ddHT3Q25AaEqTdh6Dd6Lp8LC1M7JlP4pqjI9UadIIQPk4Vtqo08kC3QbgQUUpiE9Z8I1SYv3xdAz2ct9Vfj/TtUfuGAojdLiSdKVa3CpPN6keZoUgyemN+fMemdXTB12uFky0jyJiCKG4jY5NuEpFMi774GAZXH1ZzX6R8MRWDMNaB9liUoz6U
    DARK_SKY_TOKEN: AgBXa/wDlPSgjvCapF2ayHmlSneiZCW8SJ+3nYkqtwVspZLAoPefN3xYpUbSDPT3KRP6thJV1CTMA/if4QibDVb0Ol4vQKwscLCSfmXvU9rg0Lc+nuSRCX6iNCpD5d9yPI/lx3PFtkt0KYIY7juSvW8YqRrtCCXsWsHfb+ihzhiPYF/c8eijqfJWhv6aH/FyWo0rpzGGp7kXwWLPi6HcsmcIiVP4DWq3N1UeozmmVytBuGmqEHwDiMVaU7Nhg22psJTiwtddLfDPOH2oURJLw5LC0H4286aEYoGMZnFk6GE0UAQ4hIMCwO+Tec7ZupvswqDOn4OjNDISbCoEZj+QPNs95Jih59bL1im4DSXeG44T26z//veIAGsJEW+/CDzUm/eghgZq7GXCMOX3X74pjmpLAt1U4IllupWwDxEnd0w0QqN+mcFG56ZWzpyS4JlwkVmE5ccFwmPAUjtRK5skU5gvPL6sY/lc+Ghp8GB2WW3WEeFvbCZTvASdrl6lNZbquXeVOuvmbx+ElC8kCUZoc5in1UxWQdWC0agFuT7VLa9ULoasqViyX10IzYXETsPJygJqI+Z/v30UC5yMli7WQQ9KxNh8X4FBDewTkFAqeG7aTU4sN5shERhwHEYrZmjLeu/gtzMhbllZ5jv33y9l4MwGzHnBUuf+a4JGorep5ulpUMR3ysxm6QEMC5LHqyExHBqn5F23XFEVYOQCuu/5kcF6lfueqKPckcaySGL8nkgT+g==
    GITHUB_TOKEN: AgCctdsZgSYg79nytygR9BXfAsZ5D9tGLcOZzZJnBXG6zWm42aTFdnsAhyfwDqP2Sqe7WD1mEQUJljj0/W6ISrB03Q9N1hwjRTU7Aeacipk7Wn9wZ+7m8vP1ZYiTn/KEE6K725bwdGrr6vaBuGYRA9ALIC31qAp7+3tw/YjA0JlMmc5HUhhzLIN40zeSUB5Xbg5qEvUgABEGIRNxjk1gevhefLXRo0DgKIgk+6l+PkksoPeOz49bUe25myO0UDV6kyN+kFzocpZdJne4YFPE7/vHq4jCPLFzL5nL1VOpXXtNmdfWyge8aloh7bTeq2gcBR0qupw6SNZyzJph4B63fh3jRf+v4U7S0dRj/iM4RXmH1l21S0fzB+LeB2rvYGfDMUcu+En68SO3bv+onnmI90zOOk0Db7pzc+96btcNpnJ5/AMulw6DNTWT0BPZvDB452YVvnh/tAnyWiWDvjiynQicJwNunhSwZ9jpjTmwdshUQDMIATG+Yo/czNkAYrbzm3CNOGFNZSpyHWi+n5raJ806OENNInsR2zot23EU6ArbL/s82g62QrW2fYLcm24ZZIVNCVAFy0E8zrzURx6qLy2wjJsg7Qyq5zqs2K8GYvg8E6aiJXB5vSHMLTvEtP4OhLIHpDRB4Neu0a2ygsnSb19nGFQpKeHHxGcqq/i6vfB8PRWTbBGdO1i4QB+Eu1Ao1/DhiAAPYSTvKIH/6NeFUc3YRGORUxxjHR5IdiXtsmqrv2c5X0bcgrpx
    MONGO_DATABASE: AgBHi78UDne6dhOQHXgZndtFL2IO4x4BXCoh/k+PLYw/r9N/5RTZ9kOkl0gTYMWqYxulAtsqunqq4zkmjVKwTFHBTwTkEH3z6v6cCAHchEPPiZkXXQLwDnGOMzOEXrYcd93RUD8rAPe6PKjxhdfFx8XYik98iLKnwNmXSrPOar2iUJesIlyjwbjA6cupYvTaBuK0JA7X9CWGI39cPnqR5tBj1wjiS85Hyzb4gn3cqTu+lEk9OAUfQVE2LIdc50CRwnJKXssAnHWJpPcW8JHOD3VQtnnje1UIWewfEpvgffyXtgQ/I1IHG3/3P5u0oOJtirnEq/EGJjUGk1BfUFBm/DgP9rydRFe/9yw/OJROH1n3pVUfv/ajWiXqSGilbbo58Rd7lhPERk+7VM6uVQ+nQMgEEd+exoC5NM+Yy8MMSTdGJk4u/2g7SlVryP1EQyl4ugszwLN7bC1+n23UNaW7kT7xxJ85cHuCzs+5gNvJqPSGK+tPw/oEKZnJzmOMTPJ0OyqWTC31SMvoOkYxPY9rwkxCHhjT1TwXNpdWHpM+fA6kQpY5lbQwRwSbf/Yz/d71xVMuHRMZQsLqJMPiYltT21a7zv9+F3oKNMdU5oewcMz7kyE/dWHoU2Er7veNbmszrOfQ/7WbVgRjpu5o5pSD4hxmrAiPyCirU3RG+BKxlshBwpno8hm24o+qYrWe/muUmCBEX+7dYjKCewTH/w==
    MONGO_PASSWORD: AgCIRzc4UN059r4FSzpOLw4hBcTuSASP0iSJYlJ59DUZPkDCilrdEYsNcQgXPjiBUe4AVddTiY5Zt9iiZRPIXA1xGVTtzDrKvcfq2xUrA7sD/F2jAhsSo7+zRCFrFtBNzUSQdWOEtsOMf7TEOEEktewdnc/+zfXVL1qoe5BHQESMuq0rTvqNXoMJAAseh5OAyh53MBt4p4rRvjjMlun55+YhSM4WYWQ89kjocldxFLF7s6xnj4QwA5E71UCinuULykPEE7oYnnDaaJK4VKc/IkUPRz4Xyx/DVKQ5ten0xz3w7rZLnth2tLByJFyrs1Ba0FyUnXUE4jFUaagTv9Doap2Uc7FEb4kJkwnLYi7rvSYurdmSauxiN5XY15yTi8yMUliIGAr8Ott4mMM3p/6PI6obRg7vGw3B80+6I2cdKN4et0bb4OVE58eRCJdKvX/45NP3vsSuUAkBIv4OsUXm56/SICjK7xhENp0CZ56vH/3zp/SfVPWZVI3xdhBVtDIa7IvZF5CjQiUi4RV6AEuqQPgKgEjJ5S+TG9UTKNQnTFQMzsSVsejkjqZWli7+eMsTOyu14Vtt0f++FUfHiOooPKtWgOOCEp7gS4LS8qvhinFqDITnhawh6Hp0dOe3nJ+ff0kdI/iVU5OcQ4q1SeVPq3Y8oue3h+1PZXwxU1Vvmd4U4+qemT/wv8VT7IHXgYuK5Uz+vO+0ASJuZQO3s24k7aOWHeDjaS0m2xpFNw==
    MONGO_USERNAME: AgC3tKRgAY0EclplTQag0b9Kij5rt0qs/QfXmS+Cb7G+iWxPhtPPQU9dLhaby1kzjq2WdHp41jxRim77SpwZNryptoFb1eOg+xN/Vj/i2ZkASEbl2a7/NxftJEAYF0prwo+ekArvRfQ2dVaky25dtEgBW7o5/T7e9vzSK42i2Z+nm0mQeKVbxi2H4YOTHmX43sxhhmGH3bQpblog5HZx/FHnpzvaW99kcDRiHZlswWCLvi5gdEhVIoSu8ZXmbZhGBVtO9nmo2/GZQ18W9xdm6iGyWKqQll82GMZ7Xwzi1j/GwJ/huziwuCiFzia7Ia8RngV9K8vG0Bu4+v22bNAQikrFTTagU36P/9VQCXIBjV0HgB38Qj4MOTAkWrjX++BOQLFRuA+tZ3CpexrTSN2Nan6RkpQxHJCa8jAskXLBeALYtTQoiOtHS+hflxyi5/47CCkogawEAYjuTmtDtoiYbXAy4U4K0jtkF2d1oNdcpsRP83LVQtJHDbIi9SEYZCpGHZmUK+48XcmBTUVbqRPBzEfIa1Fp9bA90GkPSbPXoJDsFOUvvxikx5svQ0C3aitWyWsjyaNyTWjP8sZXbIWsEBEO5NuTufWGmhFv5CU+XYZjAY4GrrPMD4tVIApFIoYUbaEMYknQNQ/qzjp/I6IUaF78i8R4mVUoZMnWSfvxqPA034uf+0m878U6jJb7hUZcSOybaeErtfDcfQz7ug==
    MONGODB_CONNECTION: AgCbUXSqa79n6qT2DB663qMrb3eQ+chCeRsq8HRoTgcq7B37AKg5k74ZeTc7z14tk2rkeDTsH1CnF3W4tzT7q2psqFo9POyYqer2VVI9AvuHHXjyzoQNjdkH88flvcsvc6KmMbvBCkwSL+qmV1sdtnWxL+JDpKueUn1bmqetFJWD/1wzcPhSAPzjbh7RuQQ4Eujsx7L6MJ6j2h5sRMS2YTbpwks/ItPjC4xsBIQvAxek1/lc+8bw9v/gJ/aOijvqEwbLNfdJD+ZpPrwHWj2nOFLF+tpRCo6EzmJuEhiCfO2h6+E+SY1DwQRAl5IelADtdvflBX1cZ2FHIUoxD3lCQiQLtyyKKKPedOVmv13zPlZ1HquFZK8QPPuCOudSfxQ9kP+E2qCHL77GWCfq8d3EA9RFeH1pB1Q3z/WuHO2qYJ6c5cFv52AmQsZbQ7Uw6kY8HKWDskNIEZXJW/q+Fc/67DJa5M7r/lYVAV/iQibq+rFoh51YV5rlBlYrDROVIEtw2Jn0bQs61kqHIg8vud+NbRRk5lkSpt1wVo48bvFtSzsSvX2lbzjB6rzHhITG/R5NKNCMjog3Sdipg6oP16NzNyYsP3Vog9CoVKkBI6+TmYO4Z4K0hKIov671Lcp4ujD95r/ryGXXdJiFjHj5pnmGME0QLZ2DYrmMnHI6pDXxv9zd7cI4ffmaTpcoUpYC6It65sRHROEsn8HS
    MONGODB_HOSTNAME: AgAb82hMEMzWH4kFHRPFVS4KFQISZ0sVAPij/l1PEgg+d0ZByuQeehvbxiYMjc40SkjrUs4X5c7LdqBS1WuY72gnGZZdNL3PGsoDVnrsJ0bBr4qTAPd6P0dr6f3rGuHdifUDqL5Ln0DhlI3Ze4uZzvlrBtQ/w/Ny4AyEdeJjjdbbBfdlDQfZlGWyGY/poWr7Fxoda6Lc77G3tG7X2gTFdtiGy66kdCPZyTMKtYdyc2Jn/t8Q0o+vR7jyDnl0Y9ZETzrtDUrkTKBaYwxq6M07BdEkmi2+9lkgDVNevEqIp8iSuEZDw1tBncrOFnivAushhF5NLDxTDFCDZjrOgjGkrqndGAxlLpICeKHVl7AUdp0gOR4StB5VFjTPJ8is9bm8vHEoOXl965479zPZCqB7M9AllvrNRw0UTfDUN9O965l9F/95p02GFkySOxpAQB7m3wXvT7DWhRm9Q/s+KDV3oZp7S04XJgQ4vHuklYgDMMEzcWiWnF1+DU5XtuFg+ImO75lm/XTStiY4pYxAJtLaA31pSO0llcPuphjbHjbRt65QOx6saes2+zZuYXyLOQLe9Vijen5vgvrFniXOGbt12NHnsWYYUcEn+0OlbfX+T2A7GwJbka4as2ZaNyALjhP+NwmTToX+KH1zyCVwFow3ALdTWVFAwY7cEweZPRAgIxhwjZbQpNWY4LPlYI2RRq3Wl4AYEaMdY0TAI7VkRQ==
    OPEN_WEATHER_TOKEN: AgAKKcHLSSDIjO8Lyuku7PW/kmp9YJFyGfIpSS2VYe0Q2yVCSG7bARfYl/rwhGXecuzY3+kT8cdTIaQkHyIA7hJWzlEH3ndb5wtF1/ClvInJFpfPhZw5BFPYz4/wzOLBwSMPyDKcEjqShJgZsXzKB+FX7BRw+xgmj8MkJj1W3+G9jMF2kgAHof5KodplGWMuyUchK++Mul/2pn+WKnCcVsWnCft0q3tiHRT+y1wgOsR8KHkmDgrCpQc/SOoS5wRsDmVtDVfWx4V+IZx6lqTL/8lCeyVaXbc1PmxqTRbJoItvNPHfwXDt1/7a3PUdn79PYFMzJH/IWO4Lh21KUfDq8AWc+KHDOvWgUy2U4EskXTk8YOPNPIFEf+BM/JRluWcvcNmOGku2YjIVFF30P8XJrzqhucjrnuXOUcvCkJNdK/xc0BGfSxTq+YZQ1psg9ErZmNMgI9pHdRMlgv3mkcVsAYEg6A9dJy+5hUJjL3MCemJ+I1YGSIUOM6Lvo2VDeCEcxdTPhhUEnP9QWUFp7qSJ55SF3n1pp/bvTbOFUVkhu7Ez5VdA1lBfmUkQ8nJxx/Jzts6hTWfW0tAx24d08Q9P+38HWPjpp10jaN8EXHhLYCMmlaxLWMeP1AjrzOxIucPNh2ERG18OY3H+piM7OlYV9dYBjB4U9mVUYXTCg8weJ+tRlp26PREshGbOqb03SPfe7NlWzAPyvx41v5tNyIPFQ24aPh5quFj3SQO7Xc4aCRhmdg==
    PYTHONPATH: AgBrg9p8yLEE9dMEvjGAPxjhzt9dTb6mfZzDcpWBBc6pDAkzIp9I0kBHZZi2dEtgEex0bG7daaG3N9EoBznqSt1JAl8tx0+o7eLcCN8mzuWebim5RaPlZlewGifnQI0XHkWkwuZ7HylNkcPZDag2AtmpWBfJb3tiTbE3+wEvDUVXHYW/mRt+ICd4QSI8rau/dqYg68OKSHDxqV3UO4tjfbVz0xmKTijKIIAqTfIZP7FUaojEfVf9AxVE5qc+U3GqEra0dgOjFHMwXB+n/zhil+mI9gG3+0tLUyByiBuEJSP5m3phACwRJvha/KBDWAXWoP3c+SjwA8J1o7udUrjDJ8SIFqhdSBEkK9ASOW3+JqHWmVEkl+pr1BseO0kDUeRqu8RMaUEv5AZERKBNOiyjW7FlWnFk5uZtgPT/O06VwNGLZcIeF0+g9cvIdoKmFW0LXz+r+wgCMOjpHlfAfCVRl0Y2Jy4EbZY1DUNCldXFzAkEza1K2PKvLJq22+5FfkS8mAQuukbVcVpWyj0gTBVtztV8fzO2psqc1Xh22qMa2tfZe1Iyk72WK4tb/GvbT55OnSsipQCUw3eoayLTyd+CqAThSrODJSzMXHFlGzntg9M8V7DU56vS4brZ8ogcCiRQtlJs16aX8c/H6exWPCwhmsZLklhLzzIFT5jz52Ru1l+qvNrfbT/UMns7zPnMHHtqYEHnhe1c
    REPO_NAME: AgCaaam+3+4OdfHW06QH6oRofPa+lZ5GBhysgtbhq7ZpATKsaAjZQaucTZKZhfjrEHsdcNs8X7rSuPuscWasSFyMo//hXuuCekMrKpIVYZ4HgYRHbDrXEGJbsStMMiWxN5RwmEik6liZzzFUYmGVaA5cMB08w7rg3q+lXLZ8ISUyz6cDfaU41FBK3RyJ6cYQZi3BdDkdTSTS1d8CBtfLcVInSxgqHsqJA5/tXrr0IzM4XUe/5J9uEfdWpOPDkhhGJXZYzJou/pAEtNtsZjEefEL4GdTYJFjlpiPSvs2Aib9s3X7/6mxdjNH1pTdGV3n72saI5ioOj5WkPF5eomBrYzsiYypvIpzxlVtqlpzLE17W3aO/jVI5cokllMckiAJ8JFHM8FhmFC1cPNJ3phAUwC9QD1xPvmc24LS8NyHqqeD5FmPUhdKi9cw68Iw+jKaqc0hQ0oz/YxnfOyvTPrO5OPEI30N2oP0Mq+JjlYiaEfWSSLvrLuVaOf8kbVh7Nd3FhySiOTfxEwA7bD5ogTaNyJtsz4CnL2nFJrlTGP+pFqUeqSdck61VIHizg4oHrRBWEg27lmcfjd9qgTcEErBkubZzawAApGv+IGqondSXckE0SFNxzNM/AvJABeLXt0rxfNEJM7tyvbmHWrNEplbIEhHRM2H5RP77bmZXHcVDMZpvXrucMCcb52Pml/17XhdiQ2p6zjyZNAGZ+I8G4QXXvGlq/KP7UsE=
    VOLUME_PATH: AgC8An6DihyO0+hTyfBAnRkKYlJF0LkqkdZETb5CXRspUj1EDZM6/dlfECzBjQRSaIJy8hW2SHwkg0Hzh471Wlj8XVpguwkHAypAlMlobfmjCkF59FhXdGAgstCOphkr3fjWMYbGOHmxuhcMChSEy/pMJe0M6nPazOY9EViG+Ewwmvx3y9Qlp3DQwZRnvby/BBi/S10Ix+wSNHwYbSgiMW+TCa8011ZGEqg3VQfuNwucqFy6ual5ttBkx+D0FfidLQF5fJSDGAvTEnVHBhj8sjYzBYiKL8XH25IRNDCJ7mJtwgbpE3T4TuL0RRzzrK76CL1TTAxDdkNeef4yb8/hEOk0fblsmx1Yj6PB3AqIsmXhFmcYx3E0TOEziApJnHsilmL2QESfrB/wsr6lXyWg4jiJBA/OaHPTh0mv/GRYWdiLT1ZtZsaBLGzDz5u5MGSvAerJVY2eY6mzOr7WMfk9GpXizP9tNoK1F4fCroIy1erfUyuIXFFLijFjHIjEjhD2KNPr8vJ9dQaUCfws6g0mqKJScrRknCO2B6wCUZ9Tsoa0CkSy9XzdL3KiCCZ/0D1N3M/qQva2xpA2UhcrNau/QVVwRhyfnv7mbj0Y+KaPVXpPK4BLnxNZYgVdGEVVPsFd3PtfcTt1s/betRaTemjT3K19ZppX0v+qhfnl+YizyixGnfrrYGeqxBamzt/D/6zbq+8+4OQ+UMb+rQ==
  template:
    metadata:
      creationTimestamp: null
      name: flask-secret
      namespace: aqra
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secret
  namespace: aqra
spec:
  encryptedData:
    MONDODB_LOG_DIR: AgBIvzeozmmCz/y97ViowfcDkO12jbK8tVqdAYHyF/4IzJ2F4xSseK+ZD3kq7YaR9Bw4MomPSg3Cag0s6tIc1fYGR78eqvdfQRhxCyC0dHujv2f+R0gwyGw6XbuvATU5FWjeIJ4ZnZXHogF+kGIGRx4S4IbBBbmGTQ8o1IC+BdgPnN8wjiW9GBRFQ0p/y1L0FAN6OGA1PmDiawoHOAZytTeKacXQrsQCqMqgc8YqM6ayetWKl2+bJHB7l4KKPwHqwsdmupMYIamK21QD5CXxeMQMtCGdjoiokMFv3B+l+A5lOiOPrxu3yla79P2OWM/PQxiCfyoD3Z+INAHPSTR0VF1aEULEKpl08ZranKlRBfprACw55p7epXSXBpvMdFc9AhQTvXFTOxJqU7HmB4g7pEXGipwkus0Gr+2AxRkVEMmkdJI5GtsUSFyYrfpXhbOud0v4V5FHa9qFZkKcFO1uoHsd6i+sOkn7/+jCn/89RASiztZaXm/0IgZJmH4yKXsovnJ2fst4QoZ+NMi5F/aWhlEtxldY8D3uT+r1iGW+NlBJc4eVewLKl7O9gHqLpWJMViS5atNGZ21bnhU6WQzgUQzsCdUYtrGSSEb3rkzo4EwCHXfA78tooA6Dl3/NBUV7U1Tvt5qeGb7fBBvXTNuNhYsohL50fZ2KIMYn4y2ArIPH3af8gWMDqzPsD7ItV3CwGS7Dabxhdh1BrlY=
    MONGO_INITDB_DATABASE: AgBITMwRqgyf3OgjDSEjjdSe4tSEg0OIC0QeKvqciBq9YmjM8EndSY7dUOVWu4e40i/J5qVnMCYzGzM/3PmN5fS/B3mQKutf22FtBs/kc1yXWYWu4tys8ST0gQYHeGsiALRLYleBBC/K9f0b2H0Xg5GIs/NfAdPtMlpdSWybIsBwu+EhZcjn6t2GJpcfou/02spEVEQ8y4+jbwK0mzuW1RWtm38pEqt7z7gA5WZRJ3SiZzzWIIRDN/v6KqW1W65V18M01CqCYknKY1oWwVmHnQhKW2ks65XmSb+yv36LCi32ATYtJY84Yb0N1w8OxD0nukorOtCdYRIfnG6nad0zhYve00i7yNKw9VBMRl90xf7DNMizVPAn8J0EtfmVRrxlq9gdFnjGLC+o2PvUWbcubucnAWm/OmxegdObX/H2afmjZlPuCBuc1K7/BU6mMk4Zmr9sWblvcgWc3t4YUL5FWGTq6gPJgwfYJjDSX4XaOnI8TGI70L9MmUe8YdLRmRf8qkIKOLt8paC0xi6r9jZjEPgvpjaDeEWVOYnE2AL+PlRNusJQdRhiWQbsvhr3Xu8wVCc/5W04WK5gVfCCtD2mRsIBsXmfxIS7MItVhhMDz3XPvb7OkYP9oYUQpadgTqmZY0W83kzaRPWpPLLAeIc9H0MRBb85TwraHTJJBgZC68d+b+xrCa7MGP+pxYG8AGVdU201QRFp1Zn4/aWB4A==
    MONGO_INITDB_ROOT_PASSWORD: AgAO0aDJu8MVMy9sMpXw7EVKiddhikSZXgAy1sOolqKjSgPl8NzNJDfpzsAYbnopXE1qL6Vv4/JPYRbl7lXUHlrisMsr4caDGBJjSbdc9Gdhhbfuy5pgDwnlFv3uPUwWoG6LU/GQXG58hu5mTaIZuD2sjTyfM4e5M3cFqoan4Mr6YMNyu3f4bOYgjaLgRdR8nE4CKij8odGHYS2MG+LxG4irXpEevJVZwD5MCiW379/GfkaDNlF6Vj7Zq2rN3HczlaXbdD+zIeI+eAAAcACY80X0amK8YHdJxxt37Y6PPu+Q4hwvFAuvSGt+eIg7z43Bbp3BGVaSIwxgQ5Lu1MrER/SlOUNUvMNcjCigHTmMMbS9SdITh7lQRelREpDiq+chdQJg5cGbF7mEp2WeiEMFq8c1M6iMWOGjcBrI5i9tqitutQoagl9F8jVpPcoeoQ/IJEHu7nO+O/gfwyIuEGDSbhfJA4HsJrzcjP6fDepp44YIpkBKSWlfv7nmtp9GjSYoq8c7Twz5A+YXprQ7guoIoBVqtn97mMWw3s/YY85jcultkXmN7Bagrv+ySqXH3NUKkqArxe694IE+QodQYsKi2ty67tb9xolRm+NQ7bJ2amqNZQ7mhnst6wAzaWDz0lh0/MIINEC4wr+I6tv7Y2Tvy32iIk3do8JZADy5uOl2nopdy/oz0gdr9DwMzDzYfm3M+xXSQO/eXD42cHXm7U/tqOdpkL8f5n7gqxyPWQ==
    MONGO_INITDB_ROOT_USERNAME: AgCIqM08i/nRndteMXdLDyFrOVQQN5v7nIQ6tV9BawMeCCmjqTyR0QHy6AGTBugySDh//klcXEqQ3tBPvj+mF1+gsoid+N9vjR9P2k2AriYQB6kXzuWi/gPohvewuGUJp6FUMPMhHJX7pZRq4tbYegQUqY2aVmop7qWdLr4KpE77r4rc9NcGapuy6in8LAzBjibmcpPkRuD95peo/mXtTiEqZ0cLwxCt3Kq44nhlLKx0xT/y5d1lLNd4XG0MkUv5G3pA7z5Bt1LI9B89g0yLiGDhQHzggxTQLEZ+l9c/AtTNwBWkcJZaaVTaK1Ut1vSCOtk+TAcFhzdcuZcE/v/9ZDFT5DKffC6PwLpbBTvIo62qQ+GqST2gLpuqrnN9VhuEyZwnf4GAzpW9mxK2sRsbipkoBcE5JCLkFTAyHCq8+5gZZmrAuKtErNpDki8V//8R0fnaUMISu7b1KKGmaTKYj3xyTeK8B2O14VVtHkLihox0FsDsFopCkLOfBVpnMWp5KPpByXTHzX9w1VGcJXrGRJyFeiYDh/gqpRJcTjykzEaYBhFQGUXzhAFdO7BE21zbqx5Ws+oiwwxxazMKE3+N1u4/U7999nKgkv9Xg1jsb9YX+bCTpsXywp6lB3719mwb3BHGFfAw986IjgmmnDf65MoezKkOGxmX65IXruvpgjRCyVRYAaSvpLBkaOD38NbPiye/bQjkuacDkq1/kg==
    MONGODB_DATA_DIR: AgCG2cFhcdeAV/alTaJSu0o7E7ttC/4HHWmxpj7qa8Vk24ErlD8iUUoW5AW4o+ERX//8WmpI5xXakOQrZoYID9DMtAsjiwFzrV2PUCJTQtfTwfaP+9F9G6rxb9tk8VnyC7Aqzogt9bvuCqWzsrjxn7HBtev5MJiSRUSETYJKfiH+1KgPxc0y6S5AcHtoFRwG+LLQE7Y1ntlBK08j2IiYoMTU4qpmwLNC1/o5rPPnH+v7bck5c6Ch6r8JlYDDqCWTuCxerUFmDTGLmXBoDrc6XkhYQgfoKo+832ElZ8hVlv8aQWsniCkZYKNLUMF+H8q8mstDaD7LKG50bl/rSV4SE8/+AEv9FRZcLxXvsVStAtaq9ptF2o5xCIgdCQcA4JKZs3orBDRqhRdXRjTP7AnxSImMiyszLsQGiN4LkVKYx17hiMjtH4Mdd9Q8WaQH63evycc3yZZPcs1Zz92ahHcdQ0jKU50+0QWja9vOiroW+//vJr7Ai13Gd6qUU7lSljX6bFIcAjt8Ot4ME2q7hUN5BwXRkf4l+YrIXZG6F+hLU0AUbb2hiL465uxsW/l+dvDW7A31OPyAZgwSmdhcsUKP000e5/FQVq6xqT5ZQe7e111F/6VkEk5VsND6Og+ktH9ve6mIX3+TDBBzjEgV6T61qViKPSyhD1WCDDWEyDCDT73iVAUG/9ALSCJi7+AEH+mGBibgut4CAfiMNw==
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: aqra
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: atrenchevski@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: atrenchevski@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network
  namespace: aqra
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/network: 'true'
  podSelector:
    matchLabels:
      io.kompose.network/network: 'true'