apiVersion: v1
kind: Namespace
metadata:
  name: aqra
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-sa
  namespace: aqra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronjob-cert-delete
rules:
  - apiGroups:
      - ''
      - cert-manager.io
    resources:
      - certificates
      - secrets
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cronjob-crb
roleRef:
  apiGroup: ''
  kind: ClusterRole
  name: cronjob-cert-delete
subjects:
  - kind: ServiceAccount
    name: cronjob-sa
    namespace: aqra
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker/single/docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: mongo
  name: mongo
  namespace: aqra
spec:
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: flaskdata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    name: flaskdata-pvc
    namespace: aqra
  hostPath:
    path: /mnt/aqra/api
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: mongodata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    name: mongodata-pvc
    namespace: aqra
  hostPath:
    path: /mnt/aqra/db
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: flaskdata-pvc
  name: flaskdata-pvc
  namespace: aqra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mongodata-pvc
  name: mongodata-pvc
  namespace: aqra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker/single/docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: mongo
  name: mongo
  namespace: aqra
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker/single/docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      labels:
        io.kompose.network/network: 'true'
        io.kompose.service: mongo
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: mongo-secret
          image: aqra_mongo
          imagePullPolicy: Never
          livenessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - db.adminCommand('ping')
            failureThreshold: 1
            initialDelaySeconds: 60
            periodSeconds: 300
            timeoutSeconds: 60
          name: mongo
          ports:
            - containerPort: 27017
          resources: { }
          volumeMounts:
            - mountPath: /data/db
              name: mongodata
      serviceAccountName: ''
      volumes:
        - name: mongodata
          persistentVolumeClaim:
            claimName: mongodata-pvc
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
  namespace: aqra
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - kubectl delete certificate aqra-tls -n aqra && kubectl delete secret aqra-tls -n aqra
              image: bitnami/kubectl:latest
              name: cronjob
          restartPolicy: OnFailure
          serviceAccountName: cronjob-sa
  schedule: 0 0 1 */2 *
  successfulJobsHistoryLimit: 1
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: flask-secret
  namespace: aqra
spec:
  encryptedData:
    APP_ENV: AgCOF7xm/oy1rLNkU07pmXE3dQaCUI9JrsIq2xoUBcKNsPn4IewjdaXy3q+Q8wkQ/bncQ+8slaz30hFU2YryC1+UES42MuftK2lVcXge4OEZc8+E848dVFVApJpL6kCnSbckWKnlzM1Q8zP0aWT3yy/kPSARfklObD9Z7Rk0nIGSjuc7LnLhdWHTdf9LDRjxnTr9upwOCnXUpO2cziVggHt9ycZjxdRzeSLIsm3M9WVY95F28q1OqRs0zA3scqFxMyBNsPnSUpYHZlkYMVLA2hoXHFshT2N+klDh9u9J+J57lc5wY9y6hEdLKh3ICzLlLXNHYExnZ1TtIRuDLgtJ2+n015DpSxJKduKwwcvGFvd/DRIZtgEMuvmvlJxVDQKVvjdmGmv4hQ1d84WV85IWbDo45OBP9z3r4VlJKCdgZfz72yZWoRKFHgnDVF5CsujdYtQo6P4iMMzysoEW92+QbZ+a6G49zoL07PQp+7fxAxuI8QWybKIJ9I1VofeTmzcsGW7xQJJL9Svwfk59O9ND0XQjKgipN+0/Kxz4x+n9zQTkLzlaYYF70WJYsUcoQ+tYbXRqjVYVvn4YN/qCAsmxaYU9ImfA60U8C1XgZdZo0Q/E7lkdNrmkMJ8CF+wGovNC73objCgxDkrRMUSToWxk24j7yESoDmF6M77Z5ITults4sHP48elYqVIMHGlg3rjMwPwBbvfTZ1fEqIek
    DARK_SKY_TOKEN: AgAUZu4SxiJxD5b9Ou8bY5aI8xHDjQqFG8hu0czJcEL9L4Zpo/cEl0Bx2BVlLa1ve7VIIDLJO3dzceU1UeUw2exJXsx732US0TlBz7txIbAQeSdmrJqVDBZP3cirxfTo7J/sSckTxxruILPktD7agNLpslcKqAyLD0HaAIwbo6h0jl05ZxPtvtrG+8ffvg6YaQyoy0Lose7RzxPq0K349uisIzIz8Dm+Ht23HgdZLCkxZOlb65prDLffs4iwxCgPxLtheGyGyXhhymgq2IKrHOOyaXaD+ge0y5/f/9o/QAjJxr1UYrD+JBrO/e16N2BVUhAxJDDgaHH6Vk5LN6QK54A7zoXvEa+W7N4+W16bPZcbnNjQBguEiDmsNpTJJ6W8Kr4T3eWzvCqPxE7Hp48zE2xgqmfl5SP92g4M+26XjbJZ+br1d203dNobIDWaWW7JHfAq8Gs+9D7HZD2EZraZdsstsL3pMlEK8moKXerA4SWwSRS0dMA7LgCe21Yci9rPScvUXrwk4isUo1RvkBXRan6qD+Djaz4v0KhMQBZPhgy55MPltls8/q4xWcOMxl9377uOKz1MzF+/Z/1mCglASohv81M24pa+rVfmgpkx5wByftFGaWgebxq8cK6KO9VkkJ1AL+u3rOyBP9JDYA65CNbqe9FneD75xxPSnAQn1hIJB3HuoksZY4U6ScdpRDvIBWdtnZvNsm/ieztcvF2WPy+qx55g30AVmmqfZ4Totk4Oqg==
    GITHUB_TOKEN: AgBqZDwmH5VyLh8CiY/hSdvvjSRBacHbvIHCF5Rsp6yikenbbuacxCz0+Jj9vAYhEFhbp1ltLnU/fNHAPQIZ+g1+URx1jTmej3KKxa2EXKMQjPBmya2p7WY7sW5tCd7W0JI163HQH1ku9zlUI8gK9wTj8ueavmnvCCNgKTXCI1ASEJTqLvQaCa2CQc9cn3XzgbMWxqdmd0MeJ4MSDeeGbBL8f5k3yXPwzeiftFjRG12vdKskdd2sVOhvLWudQCbWADvwGDcpnS7P2HkjZ51T1XcrRQWKf0grkncG/suWIlfV4PrQKyyWxrvl9qKsTYFON6B5nmb/XNAR8BLK3cKjwhdXB8VNqkAockpN4exhgC5pswFnNFGva41gz6pjDvJIHAogxx97n/N0W7HFjPIw0wDkUQMKUzu9KNsaMI6Q3w8a5iu28TuovGKEZar+3pqpBDyd1E2ve0gOYiVf4OIUhMdd//U45kAw+MKjPgQ6KhufNYrlocHHIzhxRVra68tZQ08situjAPb0H7YOma+YiWi617ecY1e2NdM6VL8x7EShojcyNpioFUrwHd00CcC3X5x1zK9cS45bBnw/INtU0xDbOBccXw/73+ifl9jQvgWlNN5GJE6vxoUQpp5Zb1JgL+tzEkHjA/IaNamhyyULr4HKSuE1z+xoUTHKwRQz5aenPeOUlR5mN9oElnFteJMkbTtDJWKWUNw/1uduIUivjT4xNWvplWbbaxEPwB9ROCyu7d4eTLgmQ3nA
    MONGO_DATABASE: AgAp0KRyQa04qlLd5iiOrNfuStxwTRrk5v94V31DuyPpJufBvCPKQKymwsk530Wqnhp1uFpanKkHaVekg0PdVZDD58ROt6Mt07EatLmxvOez3WKNMGn42INZN9nBv6U0qBFomRKinG/Xux9JXkTG0Dpg8fFJAQDhPWWyzQ8PvhgSRhJlA2QGMtE37cFYnUmXUmmd+vdJpDTg1DJfg3fG8XFptHuaL61Qp31p/TMz4pjY4y4+TQvUioW4DHEXTJ7bqGymGBGripzFM1fCBYS0LooJAWOd16zSpINC0n7Df6vEEn8pzuF5qy2B4juxde4XMrQahJSfQyE6OdIL9Uq6u933XKLFD3UgcK6Q1v4FYJ6DBgjsr4cWBfMxiRiSaUkht2etmbLIXHPSruuf3tlf16g8vA6YrBh4bX1yA9ERZ8L/jHwBzlnLeydpWWdZVrBZAwuwwM20mCt+Zc8eJkC4EU+eVB2/b6yFCUZcySd+lMSJwEcbf3KJbngt7owHqlso+3JjhK95WgX+u5ftpqvL1+xplxvfhSsUP/8wJ0zy0ZBfRHT2chldLzpXxB0bv67ZF5JoDoFx7tbdaJ1y5TTXFGtb/N7padJblv5re6DwL5qXFV4so9lQrRvC50xb+OFcuUEGAYkCtK/6Z+rVQW2A5t29Ey8WfF9F8iFmW24CsOjx0ULnC1ewvKqtayTsMAouhr3pglF3i8WXx4ocrA==
    MONGO_PASSWORD: AgAjr8PM5H25TlY79fFH4HUoBJh4haR0biemYQ9lHJ2IwED+X0IPMJPaYjzzf3IDxmq3jmLc0lhXuYKkMJXnDsdtSTIOmkmTpoQ5WNRv+OuSw1Vp/P61IRtLPV9jyfDX1ugXr4rH6VRVhbP6y5KrQfEreiCB5NcAlnpRwZFMhoo0dMMqE8SNI+0rtXdG8n2Ibd1ENu/T8wxoeci+mulFMQ2CEsVXNeSPk3qXXI+I7++TaaHPchbPU+KlZefYNhIxh9DvqmXKLV67MWsuER2CRrXiC+Gj2kLsBiJQDCchiduGtu5s1mnWp52uuX68D7YMwT659YNbdyOQ0XGXP/EwxGipIAm13XUhOC+8mkTbo4KGeXBfi6GvsjcOoy14q02wWvTdGvVblzlMJLW7kgDijuEhUgBmMyqtBBRQZRfj8SMgrTv6PCNk5VfTonvAbmtwYKH3WMtE9SB8C+JJTMosB+cMjSZaQGraUUyG6ju6BxxkJAepy16/Eyu3qxkOWKmA5lRx6buXQSPzGSXg856YnWWbS6qDl/OMqwvpOWHV4Yxi+2+krLr9silIyZESIX0m2zy5DvrKClolrM9lGA+j/VYWVAJmbXAxglc+waEetrV2zGmij2HJNufehRzUKBKf61HMxElkHFfRfmyNf0j78qqR2L4Dn4sFQOcmiFIYUtS+zOZJ4s5rrRasXIeoxK85NBtD53jblGqmhMx9wadzfPY=
    MONGO_USERNAME: AgAkXHfKFHkkJhI8J9TmmycN59iml8CxFjUakBVJTOrfX2oq+n0fbYzfGhL1AIWdMJtxqr21c4nSYz/lIzDpEEGYSJ+lPkaHI9RVAh1qCaHRQgoFjb3NQ6v7zjhyVwrjbkjiSAJgog/VbYzshJF58Zg5TaX+vs4Td0gvd3Hjxh84YcJkJ4S51vm/NVJ+yp+xLCUVjMf1RDJs5mwKwFygTJ5gESWTv1YGSmeyOLUTgi0qnKbBszScFuGLdmWmxJ9yJ6J0TRYRysayuia52R8ByDKUUKMbqh4aQyNusO7e6G25UmKpWZ4YLlHpZRQ1vqLAO5XcVQeWYlaLCMG5D9U7LMfwiQ4JKgt075NeAEUJDh0nAZZX4PrH9OBLmY8X/+neQJE9FjQ9GUEyn36CGv1PWIPfpsnCrpWrMccgUIi5sMfsP9EtplOC5kXeJMmumD47Iu25rgEnLejzuG0OMi+Twzs2Fv1lx3QpQ+NAjNzDb/mYVVO3hkUwxBUci1z24x97/JdrXCz8s2ZMmDAcG+o04pPiNVCzjZRk1wmCWldstgry5YN1Hi/fJS1o+1NNA8Pn8nQKTJoXHweLcusYFprptu2qJKstk6syZ7nvu2guAwVbamv3VOHWWjmYeFdw5VtpY0qF87xw6QPjWwSSVB4Yp0c+lydx1ZskdNpUaNhzJmqYcJHutBbrvU1caRjrK3knxQVGBDyCpJTYg8W55Q==
    MONGODB_CONNECTION: AgB6sVgleiOGREJcleUtKXzDj2gHe8e/IkhSQv7WaGFplPwKYHDbBvvVG86zYepp98MGnshYjNWv3DvkIbIMAYFJhl7ZAb1+lVdBEUnir6OVJGJ/ygs7zvTRUIm/i8w17lWnjPqT+L7CiRXc7r5FbVDu6K88V7/9cYF3a5apCPXtLtpnpgT9ys8cr6dGYO9NSmjBTY+o73z4E9s9x1nHHM3NUG/Z8ot2X+Yl1NabkUXcEEUwuSrXvFXkeC8Bzuq0t23DOEcyKWap7d3cxPYDrwFIr3+/cihD2daiRJkXDSjFb1/S8nX+2XuOToGIBpxnbdvEOWvVIjHoAdVrxCfSXKa0Uu3goTK/ovKTvas2xf3NavflJ5csDVqqFC/54AAeW6hah3KHY+q2BHS4lPv8IWqPCQC6jdJHwIV1AoKC02igMfXhkjj4fYx8RJLjN1ZHnvNU65JPUTrEmudbqyCwvnXCKZjUGEk18Lej+f88IQDqEJLRulJTAXDy7LBO7MNAkXggp8kr7Eq6arSP6f72OJzS3JD3MB/JBtxJSJ1yGUi47KGnIpGZoWAKYaBGZUbdvRdLHl/cXY8tuLec1Lk+5X4ovMq3YRrZBHLcvCzmQmCKWWd6neUUk1CZI8DnshwAbkxSbXcm8OYPHctjb7t82RrGwMiEOml3uKOWUgu5FV3NL3Itwn/r1Tj4QjGRvb8nHExJtsj333h/
    MONGODB_HOSTNAME: AgBsbarLPqZPUyp42VoBGa3hacgmMuQ/tkIbEJmNGJB6Qh3OtgBG2n8jPLiUnY+Ajf3Vbw/hg9kFEB7qHuIUbJl5tOHMSj5OUV1dDm1XfJU9XwG2J2W4C4ZMZzpSikBPGxYN/aXJh+IdC46EP5Lf30E4CDA5DKcac1L4uiYR39mkhOm8/MAxXj+UtPZD+g4wohQyx16qe41EeUbKwk/VUXq2rjcFmJTrsKC2JH48nO/fRuicoqXumXIADEEaHAz47zhJoy/ekzNRY0zJ4ntdjqMxMo1b98/bBuhqGABAVss9JQImKKYw5PfAOr92VBBwwtScbqnh80G9ddE42jArtF4PxS1XuDQmcN/1x08J0Ptb3rTvkSI370WwK23ranjPkKoSyDy3vjhbue7OMoXmdOF9HQNFiIBV/GOFrakFW6XUqqORCaXcbH/WSiP9hGhlA1tzMd1GT9wdk+PWPB+QvjgGor9pg8YMfMZXFiXpUXRKkyn71fP0JuAA6D/Rk2TqSzOI1CUeO4a1AUjYDTnutymo+tRnxsHrrmRxXcHUcYZGQZf1hMgVwNBENKWNXNwUWKx1m7FB9b122qNcU4Ph09s39LcMHp4ftloR44cDsUwK2vsvJW4qGLUStnQML6A0AuEdGgj6rTNW05ATq5isRdMnDPwiMKcAH5psH3erhv3NNdqw9yCaSrrCNncTXYzEecNyihFBAcQClpUhmw==
    OPEN_WEATHER_TOKEN: AgCqvsZEBmPtKy/xDhVvOnGjnnRciwpc6dD6EFdVARrsslgOW9BW1BhKb15QzyA3OFLK5KqgzkN3jaJWd3w4Eczkx7RHeHdnGxVcDAJgZkxpkBdopvkvzO/Cg8r1in1CjHulv52PuhepenK6Y2fBn4qCZh4YB6K4GecSGD56FPHEz7JmuMoom0GmihukpqFT2zEVw+bY0hlsaO3ArTSznt6sC9zsyEtGWcNpUwRyH+q4myhGDTOaxWV5SNMxPBCxmeXk1mHrA327qJyOlT1sODrf3KAzPKDHXjeFzus+KUanZwph7GE6WuIMqb1sK/RRga4VyubaecQack4tBF4JGfNB9we+GrIgukeBBzNHcvOJcS101HqzwRcNh/X9V2ABF60CGKfCUIHIHiJO1MfoyDPr6PwK44/yEQrk4NXI5BdHHrecCdxeFpyh/fM5FknIPY9zAOkcLFh3KJgqo9k3TFw0fwl3m/+qhPgCxUIs/XDuAgBIHowRX/d+0Y+32yBmIEwyjp3ct6R9pGlRIOeweRncpRUzLM+4y7VZsS1StS3DtYIkCpl2Lv26AghWS/qYsgo+X2jGwY8CuRy9t7zB6Ge9r30RAP/Iy63AJe8O5Moi3jqQRIllVtcUQiNx5A4nMG6Zc5ifSmw+7hGUSkzCVFiWoY6BFiDQddNCQ7dZZZT6eGyH/wSzDw+8P+ZTw/tF1EejWbnFFOY171EmwblBR3W1zBTplEforU9ft4u9OzQiHg==
    PYTHONPATH: AgCobehePyzdpC4SWsvcwgxTa/+p6SImwuM/1Rl3vETUbNa/Lvbza39nxjqal9KhskRqKKxeFy9AYsj5FFpVI6vabVCaoU+JcdiuYAodV8lsNMgh4qo03F8rr5lfJYGo1hufXYsdxMdLwrA/I+bQuzhSsltwOUTMttE1IGaMCOCDz1sBOcRXRNoXNxkafLaQI1SN8x3SPLUPo3sycG1siwi84yA3TjP3S4aaYrf2HIeWsxRdP9T3Z7bUx/xrPrfBpWCyil6DwAoKrOGR/0HdDyvZJgPy1qrQXI4rGJgoEzFD/eAtoha/zFCIvXOq3gdDEQsvSBO2iUozsRjqDPEn1kwcVrB78WSGMfl+8PclKysU7n8SswRTzyowrEkDqbzn+fOd5ix1W1tISC5anjVyKNzbAI3X23PWcDKJL2NQ3Z+e09SxsF0dhcRxSQDQMf7D471O8/SSHszIy4GwStPB8ibnahOri3DMfMY5WlyXE7gr/QK+58j6I+487LDZC+U9Qwr59onpE6VfxPnY+DbOSbqII3P2Usx37tCsY27reN7+JtmR6Dw71S3jghkE+skEWUpRepKrHzoL1Pu0wjxHlilOXU8D6MVjUtnsFG14GgL+SndmilTuuJdYWuBQ5z4ffK0qPLMnJxfPGP2OAYN1hhYAbxL3419oIIvkJJEeMGICgRHGeyqY5pyZxZPuD5JKhhvAoh0m
    REPO_NAME: AgBc1r73KEF0L2uOe66nutywBv53Vje3bzXLeQQvYsDJf/UADpXf2nY7VnhvfeI3a1U6JBectRx8yJoxeZOuq2gqndYMgfVPH79mAEz0Y7UyY6NXIfFo41ksLrVVS3DUGktDfErt9JWXZUS3VC8TddFboICKIIuRsaLJQ4dRJoq18dzqkkZr43asc1XRtOCzkp5U7ZCTUdY1gHlPdCCPOZ/dWvFsB/63vvfdiRVCrx521jLZt1VKfltWzI4OiCfc18hCF9+R7j/GLhcpKprwzkNZTmaTZOA45Gwlb2wX4t+Mz4jd7ZBqhw67ZWW3R9boWs4pQUmGsl9rjmwf0U2GduscizSGT9Z2EyfUiyFOlHj2j9b1Eyo9uCmO+nfx46bv5tJ22DX1++ToBof3Ak0xw1AkP3oSCeQg9SJ7l95Vw5h93dZTRcsgCh3yB2aBnXhV8Xoyyea8R4F7kzdUpVP3S7oYl8WAGdLWyosXi/UT4XktXXJB2Oh3e2bGZ566uOeK57nm5f2Skc5XG8pEo8fp6+flXNO5ATQRj4AYYJuGn/yZWbRow3fazD9AOwZ2b/Ja5ha+6BwVy2bQnTG6Dl1UNSvVEQocPE5XA1u79cvkmlAwyk/PoZMot63ijSwZbkCzSbxJT5gsBFhOySRufWgYzYkG08WoKvI7t81eWkd3OeGTHirco+r6O7Zs+YCf/Q8VEcsEBupVr7LeUYsGwnBoh6MuuFpwJ6w=
    TZ: AgBZO5wM9l/GIaKaJ3s3UQyBiSqxMCLCPxPezMi72oDjtQ+1Clq1FTsEbsptTuU1UYr2tBFhIgWKHao8LBYqBnIBOTCqv5ToBBI8Johd13Mnfroo6IddPzeiZLd+2DVI0VSCim+3G2MydvBUngYVDITUi5RXSCKz2yYqXxVep8w026r6hIbWq0YmPt2t5Z9yNopSSg7Xlhac5wNyNfBZyM1HqNMlYuYk16E2tYm+4+21LjcnB5BBUiNxQHoTbp6Be+AwtfqeWt4yd/mDMoGGL1IaKZ9QF92vvZwg7Iang/5IRxyRND+mSbI2myFvPQxWo/evZmZz6ptEkrxVWgMEXCFhi/kDtrKt8K9DkVybTYsk8MxhnErXJVkxDb2Ot9fWz/MyRed4BKWkyf9Hy+yY9ilfDGe9AuZcVH3G4nGt+Sd335SSdcBfPQHS4URYaZWZaTuARNEZC+TnXVfTmHwVyhONpKBfy1I84f+Jj6oI2qaMv3ExHsdWe1wlhrS9hJhnlwFFDSSdQb/PMPOFbwL9XJ5c1Y6+19Qml2i1FodnpWkFcOHo+2pJ9IF3im9vVJxFDEWfIu9Mj+5U+IpNGFUB6FrP3mfQVkhGVkeQm/o6DUmccA3bmF1Ka7URWZoNDiH6zgtRzjf1UFRTPx8ByTA5MLE4C0FciDP1qUvXzk9vuclb7TaZc6Ih0dh4/+fWE0n2zTqFFjcMH4FqzpO2NBfJ
    VOLUME_PATH: AgCGxe1JsS5/xCs7FHvIxZDBdx9Cgs0kywvE8WunmirClcQhNXmeyjuZAX+orkHqXJTCUoFRfEc2Pywlj4M5kPpEFABkvTlEEriICg8+k653kUDJCZ21QqKkAUEdG6/y2aqls40dMx8+OA/gUyWWdtMRELvWCj1ADxDdnBanSTEVq/gtwgDZ1vuGHQcRlcHds9GU/lBwensXcC1WDHpZMeaCvXgqkXyZsm76r1moMHVcWaKmP3luAmoySCyvt014xJpwrXo9vlIcfic0j5wdFnYsIAyaK/FWfkg8S8gbfoeBGEHFpbxctbY3De6PuinZXIJvQqsn47vSm6WEaElxMi03ays1ql7lKUI5Pzyf+7uJzsr7bVTZUq6R80y+52z+vVdLoQ4DFuUJP9S1FuxP+53QEvLWLh+yb/sGqHXL4MIecJ0DRzB3VZf196oGVakaUhnLpzEId6vpfOBrRTwu1d9jBnOcO40DLMPXGRNRjbekjZmdWHXEPb8EHcsndQp4fmxGHGrnLvVvSpP8t7qPESggCDNBPTjwt09NZGSIhtmr0SKdST5wZdm7nT5z7XLbpz8gU1hdzyyeaDDgUNgE3ajP2cSW/BtOs8nJIBwenXmoY7ObtJeS5PJ8BwCZGOgWEtAXU/ejMB11FM3R4VE+S0/tMI/tEsk0BH1DU01GaLv9bIMUse3ZMoEn4aLxoDumb6AP3//IZRMjKg==
  template:
    metadata:
      creationTimestamp: null
      name: flask-secret
      namespace: aqra
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secret
  namespace: aqra
spec:
  encryptedData:
    MONDODB_LOG_DIR: AgCUXFiT0o/2qDYkbBCj5T1y6eNpVY1jOacqyXASwMgie6kXjzYmoDJw76SDJNs+iKoZvPvwpoS+L+t9YMgExVS3OrFR8y4bOnzUF9mmF4W9ptTpOqVQQ4kJ68K9FVydB1lzv+VBH99J2CmAkb1ffBPI9tfle9Bb0RIDxu8n88bzuvLw4ml2VAfze5nLy0Z2Z3Be0ouQdujBmuXnwigotlNNrxHQn21DwHu5uvj+6pMUd9s/Ai98/8KUsOFjMNJOpBrR4vdIsB9EqF5/QrJAm7Ecc8khZGJBKdBYtKXbLNrJ9NzNzd7EILwQukmEl/5DDQpqIug3cwceeaIy/8pyytjnzpd/YHYfNmNBQ0ul18r1ZAsJgOQ007mDVsOansW+6LZdmHhmP2frhd+4Phlfvw84vfO9y6f6tDJbJJrdEbdhCR7zD+3pj10VhZLV//CsQmzvC5SI+bow8oTozf/tWIknLSFKfKXrnAY9QBkI0RMBCAslMZcOJ684eLJ70Tv9r5mJ5/u+EC9Mvp3uwYaNcAjOLzDz2vFuSgks+ysbMFxhzsD1QtheYjHjbom35HN5xyBTQdDqqnDPs7sRUmyCvYJ3EEESM91MIcLLub89+KhCy0DcW7C1dByMt7w9MiBPH0SqymLsARRDPlqoRU1FvLQTLoH6z60y4PexfSeUWo3c5Y+HD4/onnBsNzA7EH00AViUOX+HoW+uEyk=
    MONGO_INITDB_DATABASE: AgBnJOvY+7SucD+vqa9beoF4B0DuR9iT9dsie5/SsX0wnjSngWSVAk8hXZiLpsSusaHcBEhuKxRWtwZNCKCeie9Ist5zDT4ENyHQemcvGnEnSqkyi8MwepfuqbfUFcw62WmjJdvH+JCY/gP6JWibV+5cid/qDZQIB1ZVtQqrr5AQCwEsY4XTGJ41ilURhLTOPT3YxO9XFFhPdpJyWs/Fh11B4EkDQ5o4jldx2jq5iDymiOGgZycDAClhGvIXO3mO1CTmgZhLX+nrbw5DtKz2yXIQsKkev8tQFB/VeHRCigeoI3cQv259VRE/ho8s5ZF6l7xCeAFldv88rMQ7jF0t/TIUQGi4cp81zrVphBUEKTL3qc9pvvQ4PVV30vXAhV82PZwuCo7jLjqgwvYsfov6KxD4WNNKU54aKBRQMwtRzpDu0ogj6m29Q9TXI4npysvC8dDPdhpGPst6CJqaxgegIZzjF4YrMskjiq53S1U7Ip3qndFijubUcamCom24J1wjFb+W8n/xkUI6SFm2OXa399+FSNhK8RV0uGXxvDh30yLDuIvRJ7Yp13y0AYth09T1suYEAgm93AEsXM5cHey5BTxRv+vz7pYhDJT53vFkYzPBC8M95t/Wj4KuM/89Rbwf3sGSn7S0PJyERwUvA441gl1GWM0vfVuy69hCg0hHmCcuPe+9jHwxu4IW6RSxvv/xRzSAuBp5xks70pwWeQ==
    MONGO_INITDB_ROOT_PASSWORD: AgBJBGmLs5QH3GSDOZkIgRzi9KLDKlcNIgCpRPaLsMIlVUwyX7fw9wNf8xkH9h01iPst+i0PcQQiMR1a2dAT99GrERP/tSb3EVg7wrTZgq4fHPyRTep4vqp4jzv4Pyiew27qWGId7gddFWORoue/wlME6U2MgAn26EbAuOSlqowqNt7hdz6gSI6vAguPr3JnnevqYe5KsCJ31qkjHBEbmEp0g2YanCa7n7f7MOPDyBMcqLTGMrcaZszNZu3aLlb3RTK2u7wGZZtd1L8SM/ytnFPw9bCTouFGArXguC2EVDhLYx7OWsBv6uYQY9Z7arBnNYWC2JMbkBKR7By1TUTHX0F/1Z2cHFSDxtSLitjTGkfL1FfourQ9OXiK1Hsp4aCtKiRwQBnNBMGGNIwM56YvHKLX1dDSPjqaY5Ijk2OYWLbIZr/HBjoeFC54cLYlixVBWr3c7BXxFAOOWsjVunN/S+c+kHJfVThbsQvNP0P4gcnIB6K8l63djqBph8P3yt4L3asvoOLGCdER5oZOHOjYepHPlhAtszYfcBhqhrIGMKxZ+1NiMIxAD1gyxO/X6HP/Z0Ummsr9gf9E2Fawc2SbOLn0vitqZCrXHaWIOUyZ/X2IKlgh0E6CC2BPnUsiVaF0ap+mUgH2WpuPMZoKjIFHs1KNVvn+7H3mpl69gguGwTa2wG4WjYKuPA9H8mKwdQT5Qwv7JniuoWqB++yeFKixER8=
    MONGO_INITDB_ROOT_USERNAME: AgAISVFDQnyAejqVv6pScL0T/MbuHnHjRARmHSFbPgS5nQZJ91rUONKQl7nbSUCHdJauGGb3McJyhvM1r2MpPAUVPJJjo8oy7hb+/GPLn16emic3JK5sn35+0FG7FZNU40ng4B3OoZPSrNUASFBbI/IiLdhKhWvDa34qhGENULmyNErpOHhO8j33PqHmc9T9yh+jGW/YRLrsHlNvLfNTIdqzvsRHUGY3dD1sR7R2QkRAbMy989imUNLYcOXbisVh+nxPDH7el68s4o8Ld6acJZ6BAX0UM+1rx2hrJICItvdIbdSsN413CuzBCR/s0nQIftlbk9T2dX5FbN4ePy95uGIxjoYv22TlGGPozwPMRwhjLlHrpghIVNoNdFTPwvLaHJDdYnryA7PuF4lk7cl4FgULbloTOymCrFwwin1cNYGX/gAaUPRJsHJogsOIXmUcZhFXmcOWgQbJSbp26lDKnTB/pL13t4YlEKy+uSBbYKOrVksUnDtxM+2yjk65AlU0tdaKivrHMnG0HXvpWJGaBSZzAOp1MhlYNaTHmd3HzjbUgwlXJayqfNuGjo6TUtWKl1UfcAaeZcbxP60ix1AX94MnnSHggs5cPZKGB4GfBJsTBmxsq+kbQmD8lt+Nhgq3PaH+PkhVvz9G1cTADQPU+vbGOb6y13huRqqIcjKkILfUB19EdUUckv/qCYAsqovUlNwklDRqLJyRhrKLqg==
    MONGODB_DATA_DIR: AgBMJs8ZjOBl5a9PVX2vV5YRa385mHmbKGewJP59nqX10Rp5cCQ3RxWifbB5b/iSfGoz2XyBZVkTW/drorewS1Sq7U09QuXdFloPbRQOtkQP/pMUSw1y4qIkdTpuBTUgs4p06zwn2+aQM8yRyR8bQD6cwgcRa1yCUvbPr6H1k7QSBnIr9UDdK7tdiDlMNzrfUHW1EKwvhj8w5KuZWeHi35e9Dhv2LKIPAIEstoBPixR0CJTejm6xy7NPpK4p7pgvn6ugIs48I91+PKN0jTaIdc4Wiu0AVL8g3+dpnFmEF5ueGcRf8uitAAnX+/K560K6THNzHFtWWb+Wcmox11i2W/Zk2BcagcTUELK1fjBL3vwaXH23RO4Vu1+lZSn5/z0rwMJ/fkTSQiJQ7UK2U+/Oy2vfuWpqVRwdkgL/GmEgTFVEYU+u7ckNIzKGTrgxa/5wH53jkIcuo7PgRPFLXhnh33mM/2aoAazWp5Eo9Rh3t0YEpIiaxm3NiL2zKeKddajS1bjWqi/ricoDcfuEK6aVaLHJaCJymLqCbnjjjVrro5XooBeJVQoQ0YH6nuJYCKz0sIiZkbqx765tHrln2NECm8qBeSQhGbQZyHfITCkcaNa1TaEAQGBmYG9Lbi9x8fqoaXtwaempYazxrFw7phzCYvuJxRcdYe1RRN2xC3yUS1G8qMRt5yPEa472lDOt/zSwhDS0+3miA842ow==
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: aqra
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: atrenchevski@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: atrenchevski@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network
  namespace: aqra
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/network: 'true'
  podSelector:
    matchLabels:
      io.kompose.network/network: 'true'