apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker/single/docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: flask
  name: flask
  namespace: aqra
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flask
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker/single/docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.network/network: 'true'
        io.kompose.service: flask
    spec:
      containers:
        - name: flask
          image: aqra_flask
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: flask-secret
          resources: { }
          volumeMounts:
            - mountPath: /var/api
              name: flaskdata
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /healthz/live
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 300
            timeoutSeconds: 60
      serviceAccountName: ''
      volumes:
        - name: flaskdata
          persistentVolumeClaim:
            claimName: flaskdata-pvc