apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: flaskdata-pv
  namespace: aqra
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: '/mnt/data'
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual