apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: flaskdata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    name: flaskdata-pvc
    namespace: aqra
  hostPath:
    path: /mnt/aqra/api
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual