apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: flaskdata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: '/mnt/data/api/nginx'
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual