apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: nginxdata-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    name: nginxdata-pvc
    namespace: aqra
  hostPath:
    path: /mnt/aqra/api/nginx
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual