tags:
  - train
#    description: Train regression models for predicting pollutants
summary: Initializes training of regression models for predicting pollutants
description: "Initializes an operation for training regression models for all pollutants or a specified pollutant from
the query parameter."
parameters:
  - in: query
    name: pollutant
    description: Name of the pollutant
    enum: [ "aqi", "co", "nh3", "no", "no2", "o3", "pm2_5", "pm10", "so2" ]
    required: false
    schema:
      type: string
responses:
  200:
    description: Initialized training operation for all cities and available sensors.
  404:
    description: Cannot train data because the pollutant is not found or is invalid.