tags:
  - train
#    description: Train regression models for predicting pollutants
summary: Initializes training of regression models for predicting pollutants
description: 'Initializes an operation for training regression models for all pollutants or a specified pollutant from
the query parameter for a city and sensor specified as a path parameter.'
parameters:
  - in: path
    name: city_name
    description: Name of the city
    required: true
    schema:
      type: string
  - in: path
    name: sensor_id
    description: Id of the sensor
    required: true
    schema:
      type: string
  - in: query
    name: pollutant
    description: Name of the pollutant
    required: false
    schema:
      type: string
responses:
  200:
    description: Initialized training operation for the predicted pollutant.
  404:
    description: Cannot train regression models because the city, sensor or pollutant are not found or invalid.