version: "3.8"
services:
  flask:
    build:
      args:
        - USER_ID=${USER_ID:-$(id -u)}
        - USER_GID=${USER_ID:-$(id -g)}
        - USER_NAME=${USER_NAME:-$(whoami)}
      context: ../..
      dockerfile: docker/single/Dockerfile
    container_name: flask
    depends_on:
      - mongo
    deploy:
      replicas: 1
    env_file:
      - .env
    environment:
      APP_ENV: ${APP_ENV}
      DARK_SKY_TOKEN: ${DARK_SKY_TOKEN}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGODB_CONNECTION: ${MONGODB_CONNECTION}
      MONGODB_HOSTNAME: ${MONGODB_HOSTNAME}
      OPEN_WEATHER_TOKEN: ${OPEN_WEATHER_TOKEN}
      PYTHONPATH: ${PYTHONPATH}
      REPO_NAME: ${REPO_NAME}
      TZ: ${TZ}
      VOLUME_PATH: ${VOLUME_PATH}
    image: aqra_flask:latest
    networks:
      network:
        aliases:
          - aqra
    ports:
      - "80:80"
    volumes:
      - flaskdata:/var/api

  mongo:
    build:
      args:
        - USER_ID=${USER_ID:-$(id -u)}
        - USER_GID=${USER_GID:-$(id -g)}
        - USER_NAME=${USER_NAME:-$(whoami)}
      context: ../..
      dockerfile: docker/mongo/Dockerfile
    container_name: mongo
    deploy:
      replicas: 1
    env_file:
      - .env
    environment:
      MONDODB_LOG_DIR: ${MONDODB_LOG_DIR}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGODB_DATA_DIR: ${MONGODB_DATA_DIR}
    expose:
      - 27017
    image: aqra_mongo:latest
    networks:
      - network
    volumes:
      - mongodata:/data/db

networks:
  network:
    attachable: true
    driver: overlay

volumes:
  flaskdata:
    driver: local
  mongodata:
    driver: local