version: '3.8'
services:
  flask:
    build:
      context: ../..
      dockerfile: docker/single/Dockerfile
    container_name: flask
    depends_on:
      - mongodb
    environment:
      APP_ENV: ${APP_ENV}
      APP_NAME: ${APP_NAME}
      PYTHONPATH: ${PYTHONPATH}
      DARK_SKY_CREDENTIALS: ${DARK_SKY_CREDENTIALS}
      PULSE_ECO_CREDENTIALS: ${PULSE_ECO_CREDENTIALS}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_HOSTNAME: ${MONGODB_HOSTNAME}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
    networks:
      network:
        aliases:
          - aqra
    ports:
      - 5000:80
    volumes:
      - flaskdata:/var/api

  mongodb:
    build:
      context: ../..
      dockerfile: docker/mongo/Dockerfile
    container_name: mongodb
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
      MONGODB_INITDB_DATABASE: ${MONGODB_INITDB_DATABASE}
      MONGODB_DATA_DIR: ${MONGODB_DATA_DIR}
      MONDODB_LOG_DIR: ${MONDODB_LOG_DIR}
    expose:
      - 27017
    networks:
      - network
    volumes:
      - mongodbdata:/data/db
networks:
  network:
    driver: bridge
volumes:
  flaskdata:
    driver: local
  mongodbdata:
    driver: local