version: '3.8'
services:
  flask:
    build:
      context: ../..
      dockerfile: docker/single/Dockerfile
    container_name: flask
    depends_on:
      - mongo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - .env
    environment:
      APP_ENV: ${APP_ENV}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGODB_CONNECTION: ${MONGODB_CONNECTION}
      MONGODB_HOSTNAME: ${MONGODB_HOSTNAME}
      OPEN_WEATHER_TOKEN: ${OPEN_WEATHER_TOKEN}
      PYTHONPATH: ${PYTHONPATH}
      REPO_NAME: ${REPO_NAME}
      VOLUME_PATH: ${VOLUME_PATH}
    image: aqra_flask:latest
    networks:
      network:
        aliases:
          - aqra
    ports:
      - '80:80'
    volumes:
      - flaskdata:/var/api

  mongo:
    build:
      context: ../..
      dockerfile: docker/mongo/Dockerfile
    container_name: mongo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGODB_DATA_DIR: ${MONGODB_DATA_DIR}
      MONDODB_LOG_DIR: ${MONDODB_LOG_DIR}
    expose:
      - 27017
    image: aqra_mongo:latest
    networks:
      - network
    volumes:
      - mongodata:/data/db

networks:
  network:
    driver: overlay

volumes:
  flaskdata:
    driver: local
  mongodata:
    driver: local