name: Deploy Flask API

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: .github/workflows/atrenchevski.ovpn
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}
          client_key: ${{ secrets.USER_KEY }}
      - name: Clone or pull repository
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.REPO_URL }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and deploy
        run: |
          cd ${{ secrets.REPO_PATH }}
          git pull
          docker-compose -f docker/single/docker-compose.yml build
          kubectl apply -f kubernetes/mongo-deployment.yml
          kubectl apply -f kubernetes/single/resources/flask-deployment.yml
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
      - name: Cleanup
        run: |
          docker system prune -a --volumes