name: Deploy Flask API

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print Current User and KUBECONFIG location
        run: |
          whoami
          cat /home/atrenchevski/admin.conf
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
      - name: Connect to VPN
        uses: kota65535/github-openvpn-connect-action@v2
        with:
          config_file: .github/workflows/atrenchevski.ovpn
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}
          client_key: ${{ secrets.USER_KEY }}
      - name: Build
        run: |
          git pull
          docker-compose -f docker/single/docker-compose.yml build
      - name: Cache Docker build cache
        uses: actions/cache@v3
        with:
          path: |
            docker/single/Dockerfile
            requirements.txt
          key: ${{ runner.os }}-docker-${{ hashFiles('docker/single/Dockerfile') }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-docker-${{ hashFiles('docker/single/Dockerfile') }}-
      - name: Deploy
        run: |
          kubectl apply -f kubernetes/mongo-deployment.yml
          kubectl apply -f kubernetes/single/resources/flask-deployment.yml
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
      - name: Cleanup
        run: |
          docker system prune -a --volumes
