name: Deploy Flask API with MongoDB

on:
  push:
    branches:
      - master

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  GIT_REPO_PATH: ${{ secrets.GIT_REPO_PATH }}
  GIT_REPO_USERNAME: ${{ secrets.GIT_REPO_USERNAME }}
  GIT_REPO_NAME: ${{ secrets.GIT_REPO_NAME }}
  KUBECONFIG: ${{ secrets.KUBECONFIG }}
  KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Connect to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: 22

      - name: Create Git repo directory
        run: |
          sudo mkdir -p $GIT_REPO_PATH
          sudo chown $SSH_USERNAME:$SSH_USERNAME $GIT_REPO_PATH

      - name: Check if Git repo is initialized
        run: |
          if [ ! -d $GIT_REPO_PATH/.git ]; then
            git clone https://$ACCESS_TOKEN@github.com/$GIT_REPO_USERNAME/$GIT_REPO_NAME.git $GIT_REPO_PATH
          fi

      - name: Update Git repository
        run: |
          cd $GIT_REPO_PATH
          git fetch origin
          git reset --hard origin/main

      - name: Build Docker images and deploy with Docker Compose
        run: |
          cd $GIT_REPO_PATH
          docker-compose -f docker/single/docker-compose.yml build

      - name: Deploy Kubernetes manifests with kubectl
        run: |
          cd $GIT_REPO_PATH
          docker run --rm \
            -v $PWD:$PWD \
            -w $PWD \
            --env KUBECONFIG=KUBECONFIG \
            lachlanevenson/k8s-kubectl:v1.25.4 \
            kubectl apply -f .
        working-directory: ${{ env.GIT_REPO_PATH }}